### ISSUE TITLE
support for graphviz neato (and other layouts)?

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor-diagram#100]
I tried to include and format using ```neato```:

http://www.graphviz.org/Gallery/undirected/philo.gv.txt

but I couldn't find a way to trigger processing using ```neato```;

The command line format would be ```dot -Kneato``` but the override ```-a graphviz="dot -Kneato"``` didn't seem to work.

Is there a per diagram override I might have missed?

Thanks

**Comment by pepijnve** [comment]
Hi @gliptak,

Unless there's a way to specify this in the dot file content itself you won't be able to do this at the moment.

The document attribute that you can use to specify the location of the binary is always the name of the binary itself (so `dot` in this case), but the code does some validation on that and the `-Kneato` suffix is going to cause problems.

Support for the alternative layouts should be easy enough to add though. I propose to do this via a block level attribute. Something like

```
[dot,layout=neato]
----
....
----
```

**Comment by mojavelinux** [comment]
> Support for the alternative layouts should be easy enough to add though. I propose to do this via a block level attribute.

I like it!

I'm also trying to think whether a role or an option would fit here.

* role: `[dot.neato]`
* option: `[dot%neato]`

If neither of those feels right, we'll stick with the `layout` attribute idea.

**Comment by pepijnve** [comment]
I wasn't aware of the role and option asciidoc syntax (and asciidoctor shorthands). You learn something new every day.

I think initially I'm going to stick to the layout attribute. This keeps the style of setting additional flags and options similar to the one that's used in the ditaa extension.

**Comment by mojavelinux** [comment]
:+1: 

Regarding the shorthand, it definitely saves a bunch of typing. Here are the relevant sections in the user manual for future reference:

* [id shorthand](http://asciidoctor.org/docs/user-manual/#id)
* [role shorthand](http://asciidoctor.org/docs/user-manual/#role)
* [options shorthand](http://asciidoctor.org/docs/user-manual/#options)

(Granted, those sections still need a bit of work).

**Comment by gliptak** [comment]
Looking forward to try this out :)
