### ISSUE TITLE
Mermaid fails with a 'no such file or directory' error

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-diagram#107]
Reported by @JmyL in #91

It failed with the error message below.

```
asciidoctor-diagram: ERROR: Failed to generate image: No such file or directory @ sys_fail2 - (/tmp/mermaid20160407-4250-17u1yt5.svg.svg, /tmp/mermaid20160407-4250-4drkwb.svg)
```

'.svg.svg' part looks weird for me.

The test code is here.

```
["mermaid", "glove mode flowchart", "svg"]
------------------------------------------------------------
sequenceDiagram
    Alice->John: Hello John, how are you?
    loop Reply every minute
        John-->Alice: Great!
    end
------------------------------------------------------------
```

**Comment by pepijnve** [comment]
@JmyL strange that it fails this way. There's a unit test that tests exactly this and that passes correctly. Perhaps something changed in a more recent version of mermaid than the one I tested with.

Could you let me know which version of mermaid you have installed and on which platform you're experiencing this problem?

**Comment by pepijnve** [comment]
I installed the latest version of mermaid (0.5.8) and adapted the SVG unit test to one using your exact code. Runs correctly for me.

I'll need to know more about your environment (operating system, asciidoctor version, asciidoctor-diagram version, mermaid version and ruby version) to reproduce this. From you're profile I see you're from Seoul.

Locale settings may also be relevant if your machine is not configured in UTF-8. Since you have a `/tmp` dir I'm going to assume you're using some Unix-like system. If you could run `locale` in a terminal and provide the output of that command, that could be useful as well.

BTW, the `.svg.svg` extension is a bit of a red herring. I agree it looks weird, but that's normal behaviour. I've made a small change to the code already to avoid this that will be included in the next release.

**Comment by JmyL** [comment]
Mermaid is version 0.5.8.

I've tested it with docker image, melfas/asciidoctor, 
it is based on asciidoctor/docker-asciidoctor, I've added mathematical for stem support on asciidoctor-pdf.
So operating system is fedora, and I'm using asciidoctor-diagram master branch to check new `.asciidoctor` folder, ruby version is 2.2.4p230.

And output of `locale` is here.

```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by pepijnve** [comment]
@JmyL thanks for the information. Looks like that should be working. I'll try reproducing this with the docker image you're using.

**Comment by pepijnve** [comment]
@JmyL as a sanity check I create a text file with your diagram code and ran `mermaid -s test.mmd` in an instance of the `melbas/asciidoctor` container. This fails with the message `mermaid requires phantoms ^1.9.0 to be installed, found version 2.1.1`. So you'll need to install some 1.9.x version of phantomjs in the container.

This message isn't reported correctly because Asciidoctor diagram expects processes that fail to return a non zero exit code. Mermaid exits with 0 in the case above.
The best I can do for this issue is to modify the mermaid integration to check if the output file was generated or not. If it wasn't I can raise an error with the contents of stdout and/or stderr of the mermaid process.

**Comment by pepijnve** [comment]
With commit 66ee491bfac6c11faf77aeed70e6ef8160c17e23 the error is reported correctly. Since there's not much else that can be done, I'm going to go ahead and mark this issue as closed.

**Comment by JmyL** [comment]
Thank you so much! 
Big applause from Seoul ;)

**Comment by mojavelinux** [comment]
:clap:
