### ISSUE TITLE
Images not being generated from commandline

### ISSUE THREAD

**Issue by cocowalla** [asciidoctor/asciidoctor-diagram#108]
I've installed on Windows using `gem install asciidoctor-diagram`, then I try to generate an HTML file containing diagrams from the commandline:

`asciidoctor -r asciidoctor-diagram "MyFile.adoc"`

No images are generated. If I add the `--verbose` flag, I see a lot of warnings:

```
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/blockdiag/extension.rb:77: warning: `&' interpreted as argument prefix
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/blockdiag/extension.rb:82: warning: `&' interpreted as argument prefix
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:41: warning: mismatched indentations at 'end' with 'def' at 30
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/meme/extension.rb:34: warning: ambiguous first argument; put parentheses or a space even after `/' operator
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/asciidoctor-diagram-1.4.0/lib/asciidoctor-diagram/extensions.rb:33: warning: instance variable @default_format not initialized
```

**Comment by mojavelinux** [comment]
> lib/asciidoctor-diagram/blockdiag/extension.rb:77: warning: `&' interpreted as argument prefix

For some reason, Ruby requires that a block reference argument be surrounded in round brackets. I observed this in core as well. This line should be:

```ruby
self.instance_eval(&init)
```

**Comment by mojavelinux** [comment]
Having said that, those are all just warnings and not likely the reason the diagrams aren't being generated.

Could you provide a snippet of the AsciiDoc? A sample project would be even better.

**Comment by mojavelinux** [comment]
...failing test even better still.

**Comment by cocowalla** [comment]
I just extracted a sample into a separate document, and it seems the problem is that my diagrams were wrapped in a source block, e.g.

```
[source,java]
----
[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....
----
```

After removing the source block, it works as expected

**Comment by harmv** [comment]
I see this problem too.  This has nothing to do with source blocks etc...


I use the following adoc snippet
`$ cat test.adoc 
:numbered:

= Title

== Chapter 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum`

when generating html I get
`$ asciidoctor -r asciidoctor-diagram -v test.adoc 
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/blockdiag/extension.rb:88: warning: `&' interpreted as argument prefix
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/blockdiag/extension.rb:93: warning: `&' interpreted as argument prefix
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/meme/extension.rb:39: warning: ambiguous first argument; put parentheses or even spaces
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized
/Library/Ruby/Gems/2.0.0/gems/asciidoctor-diagram-1.5.1/lib/asciidoctor-diagram/extensions.rb:35: warning: instance variable @default_format not initialized`
