### ISSUE TITLE
Require asciidoctor if Asciidoctor is not defined

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-diagram#114]
At the very least, Asciidoctor Diagram should attempt to require asciidoctor if the Asciidoctor symbol is not defined when Asciidoctor Diagram is loaded at the top level.

At the top of lib/asciidoctor-diagram.rb

```ruby
require 'asciidoctor' unless defined? ::Asciidoctor
```

Doing so allows this check to used in other libraries as well. Otherwise, this check fails and Asciidoctor doesn't get loaded.

We might want to consider adding this to any "public" require, which would mean in each extension.

**Comment by pepijnve** [comment]
Fixed by https://github.com/asciidoctor/asciidoctor-diagram/pull/115
I added the line you suggested to the top of `lib/asciidoctor-diagram/extensions.rb`. That file gets required by all the individual extensions so this way it's fixed for everything in one go.

**Comment by mojavelinux** [comment]
Excellent.

If I may, I'd like to propose a slight change that I discovered since filing this issue. The safer way is to check for the version constant. I forgot that `defined?` can go deeper.

```ruby
require 'asciidoctor' unless defined? Asciidoctor::VERSION
```

No other gem should be claiming that constant, so that's a sure fire way to know we've loaded Asciidoctor.

wdyt?

**Comment by pepijnve** [comment]
Works for me. I'll make that change right away.

**Comment by pepijnve** [comment]
Changed in dce0ae755257941e00fd3b51c84e4be0e4d8cad9

**Comment by mojavelinux** [comment]
:+1:
