### ISSUE TITLE
PlantUML include path resolving not working correctly

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-diagram#120]
From https://github.com/asciidoctor/asciidoctorj/issues/473#issuecomment-232562896

As it looks now, the include path is relative to the path of the *.adoc file and not relative to
the puml file that is including the other one.

But if the *.puml files are in another directory than the adoc file it is not working.
If there is, for example a Testdocument.adoc inside c:\temp
c:\temp\Testdocument.adoc
and the puml files SimpleIncludedFile.puml and SimpleIncludeTest.puml inside c:\temp\puml\
c:\temp\puml\SimpleIncludedFile.puml
c:\temp\puml\SimpleIncludeTest.puml

If the Testdocument.adoc includes the SimpleIncludeTest.puml with include::puml/SimpleIncludeTest.puml[]
and the SimpleIncludeTest includes the SimpleIncludedFile.puml with !include SimpleIncludedFile.puml!0 (or !include ./SimpleIncludedFile.puml!0)
then after generating the adoc output with the maven plugin I get an error 
"cannot include c:\temp\SimpleIncludedFile.puml".

I can add the sub directory to the include directive like "!include ./puml/SimpleIncludedFile.puml!0" to get 
the adoc rendering correctly, but then i can't use any puml editor/renderer (e.g. the puml eclipse plugin) because
they (of course) do not know of the sub directory.

Am I doing something wrong, or is this still a bug?

**Comment by pepijnve** [comment]
That's odd; I have a test case for exactly that type of configuration (see https://github.com/asciidoctor/asciidoctor-diagram/blob/master/spec/plantuml_spec.rb#L74). When you use inline plantuml blocks in your document the paths are indeed resolved wrt the adoc file itself. When you use the block macro though it should be done relative the the puml file.

I'll try to reproduce this locally.

**Comment by ClausRoh** [comment]
I have tried with and without `./`, but it doesn't matter.

**Comment by pepijnve** [comment]
Ok, that was just to rule out the eliminate potential simple causes.

Could you share a simple project (maven pom file, adoc and puml files) that show the issue. Saves me quite some time in reproducing this.

**Comment by ClausRoh** [comment]
Sorry, at the moment I am busy with other stuff and the structure in my comment is just a sample (no real files)...

**Comment by pepijnve** [comment]
I'll create something simple and try this with plain asciidoctor on my development machine. If that also produces the error I'll be able to fix this quickly.

If this is related to maven and/or asciidoctorj somehow this is going to take much longer since I would need to set up a development environment for that. Not sure when I'll be able to get round to that.

**Comment by ClausRoh** [comment]
Any news? Could you reproduce the behaviour?

**Comment by pepijnve** [comment]
I haven't had a chance to work on this yet. My volunteer time is limited I'm afraid.

**Comment by olivergierke** [comment]
> When you use the block macro though it should be done relative the the puml file.

Can you clarify on this?

I have the following:

`src/main/asciidoc/index.adoc` (using `include::models/foo/bar.uml2[]`)
`src/main/asciidoc/models/foo/foo.uml2`
`src/main/asciidoc/models/foo/bar.uml2` (using `!include foo.uml2`)

That gives me:

`cannot include …/src/main/asciidoc/foo.uml2` in the generated document but renders fine with e.g. the PlanUML Eclipse plugin. If I change the PlantUML include to `!include models/foo/foo.uml2`, the Asciidoc generated output is okay, but the editor fails to render the preview. I've also tried `plantuml::…` instead of `include::…` in the Asciidoctor file but that doesn't change anything.

**Comment by pepijnve** [comment]
The current location of the test in question is https://github.com/asciidoctor/asciidoctor-diagram/blob/master/spec/plantuml_spec.rb#L179
Unless I'm mistaken it does this

- plantuml source contains `plantuml::dir/plantuml.txt`
- `dir/plantuml.txt` contains `!include list.iuml`

I just reran that test locally and afaict it's working correctly.

@olivergierke could you share the build file you're using that invokes asciidoctor. Perhaps I'll be able to reproduce this issue if I can set up the same environment as you.

**Comment by pepijnve** [comment]
I just added assertions and now the build broke on Travis 😄 Either I made a silly mistake or something is broken after all...

**Comment by olivergierke** [comment]
Ha! Nice one. Does that mean you're good to go or would you still like me to prepare an example?

**Comment by pepijnve** [comment]
A small example might still be useful. The test now fails on Travis, but passes fine locally with the exact same command. Being able to reproduce the problem on my development workstation would greatly speed up the process.

**Comment by olivergierke** [comment]
I've prepared a (hopefully) minimal (enough) sample [here](https://github.com/olivergierke/asciidoctor-plantuml). I tried to strike a balance between minimalism and staying as close to my actual project in terms of setup (still is a Maven based Java project). Happy to give test builds a try if you can point me to snapshots of `asciidoctor-diagram` or the like.

**Comment by pepijnve** [comment]
@olivergierke thanks for the sample. It reproduces the problem here too. Time to start debugging.

**Comment by pepijnve** [comment]
@olivergierke I finally figured out what's wrong here. Your code is using an asciidoc level include. That causes the referenced file to be inlined. `include::models/bar.uml2[]` is equivalent to

```
[plantuml]
....
@startuml
!include foo.uml2
@enduml
....
```

the asciidoctor core does this inlining before asciidoctor-diagram even gets a chance to process the code. There is no trace left of the fact that it was included from an external file.

To make things work the way you expect you should use the diagram block macro syntax instead. Remove the asciidoc bits (block style and begin/end markers) from bar.uml2 and replace the `include` macro with `plantuml::models/bar.uml2[]`.

**Comment by pepijnve** [comment]
The unit test was failing due to a typo in the test itself. The case of the filename to include was mismatched. Worked fine on mac due to HFS being only case-preserving, not case-sensitive.

**Comment by olivergierke** [comment]
Thanks, works like a charm! I've updated the [sample repo](https://github.com/olivergierke/asciidoctor-plantuml#update) with the crucial bits of information.

**Comment by hidehalo** [comment]
> @olivergierke I finally figured out what's wrong here. Your code is using an asciidoc level include. That causes the referenced file to be inlined. `include::models/bar.uml2[]` is equivalent to
> 
> ```
> [plantuml]
> ....
> @startuml
> !include foo.uml2
> @enduml
> ....
> ```
> 
> the asciidoctor core does this inlining before asciidoctor-diagram even gets a chance to process the code. There is no trace left of the fact that it was included from an external file.
> 
> To make things work the way you expect you should use the diagram block macro syntax instead. Remove the asciidoc bits (block style and begin/end markers) from bar.uml2 and replace the `include` macro with `plantuml::models/bar.uml2[]`.

That's work, thank you!
