### ISSUE TITLE
blockdiag with pdf output

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor-diagram#135]
I've tested asciidoctor-diagram and blockdiag (png output) to produce PDF document via docbook and dblatex.  Unfortunately the font rendering in the produced document is too bad to be usable.

But blockdiag can produce images in pdf-output if installed with the pdf option, e.g.
      pip install "blockdiag[pdf]"
The installed program can then be used like:
      blockdiag -Tpdf test.txt

This output format however doesn't seem to be currently supported by asciidoctor-diagram. Therefore I very much wish for an addition enabling to write:

    [blockdiag, afile, pdf]
    ....
    <some blockdiag code>
    ....

**Comment by pepijnve** [comment]
I've added PDF output support for the blockdiag family of tools and graphviz. Did some quick tests with the docbook5 backend and dblatex. This seems to produce the type of results you're looking for.

**Comment by pela9** [comment]
Thanks!
