### ISSUE TITLE
Shrink plantuml jar

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-diagram#137]
PlantUML is a pretty heavy dependency to embed in the asciidoctor-diagram gem. The asciidoctor-diagram gem is currently about 5M in size of which only 256K is asciidoctor-diagram itself.

To shrink things down a bit I'm considering the following

1. Compress the plantuml jar using Pack200 compression. I'm not sure how to handle decompression of the pack200 file yet. At first I thought of abusing extconf.rb for this, but that would require finding a JRE at gem installation time. I would prefer to avoid this. The file can be decompressed on first use of plantuml since we need a JRE to run the plantuml code anyway. I'm not sure where to extract it to yet though. `/tmp`?
2. Shrink the plantuml jar using proguard.
3. Shrink the plantuml jar by eliminating unused code. A quick review of the plantuml source code shows that it contains a lot of toy/fun/experimental code (e.g., a transpiled version of GraphViz, an FTP server, a telnet server, a working version of oregon trail, ...). IMO it's silly to ship all this code that nobody uses. Stripping all that stuff out already reduces the plantuml jar to half it's size.

Some quick experiments show that this can result in a gem file of about 540K. Shrinking the gem by an order of magnitude seems worthwhile.

**Comment by pepijnve** [comment]
@mojavelinux do you reckon this is worthwhile? Any thoughts on where to put the extracted pack200 file? Pack200 files can not be loaded by the JVM directly so extraction is required.

**Comment by mojavelinux** [comment]
I'm always a fan of making things more lightweight. I wouldn't worry about hyper-optimizing it, but if the effort is low for some big gains, I'd say it's worth doing.

**Comment by pepijnve** [comment]
Probably best to deal with this kind of stuff upstream. Basically what should happen is https://github.com/plantuml/plantuml/pull/94 Unlikely that will ever happen though.

I'm going to close this issue since in light of #67 it's probably best to just stick with vanilla upstream PlantUML.

**Comment by mojavelinux** [comment]
Thanks for following up. I trust your decision on this. What's most important is that we arrived at a decision.
