### ISSUE TITLE
Add Powerpoint support using Apache POI (Need hints before I implement it)

### ISSUE THREAD

**Issue by basejumpa** [asciidoctor/asciidoctor-diagram#139]
I could need some hint before I start the implementation and a pull-request for using **Powerpoint** diagrams directly as shown below. 

The extension would wrap the command line tool [PPTX2PNG](http://poi.apache.org/slideshow/xslf-cookbook.html#PPTX2PNG) being part of the [Apache POI](http://poi.apache.org).

## Question-1
My **question** is whether I should use as a blue-print for my extension ...
* the plantuml/ditaa extensions using the detour (?) over this Java.send_request mechanism or
* the mermaid/umlet/wavedrom extensions and handle the java-call as a normal command line call.

I created the repository [pptx2png](https://github.com/basejumpa/pptx2png) to show the necessary calls in both windows and  linux environments. There you can see that many jar files need to be added in this call.

## Usage
The extension would make possible this:
Either as block macro:
```
pptx::somePowerpointFile.pptx[slide=1, format=svg]
```

or as block (here with other attributes):
```
[pptx, slide=5, format=png, scale=0.5]
....
include::somePowerpointFile.pptx[]
....
```

## More Background with Question-2
Behind the scenes it would just convey the **target** and the **attributes** to the **PPTX2PNG** command line tool; it's [sources](https://svn.apache.org/repos/asf/poi/trunk/src/ooxml/java/org/apache/poi/xslf/util/PPTX2PNG.java) nicely show the possibilities of options.

This command line interface Apache POI does neither support stdin nor stdout as channels.

Furthermore, unfortunately, there's no way to determine the filename of the output (unless I created a new command line interface or use the POI java bindings directly with own java program). With PPTX2PNG the filename of the output is always

outputFilename := inputBaseName + '-' + slideNumber + '.' + format.

So the asciidoc-diagram-filter needed to cope with this in some way. I'd appreciate here a recommendation, too. I could either
* take above hardcoded file as a temporary file (the output-directory I can determine, so I'd use then the temp-dir as output directory) and do a file-copy to my resulting file or
* let asciidoc-diagram use the resulting outputfileName directly.

In my opinion the first alternative is better. But then I don't know how the java.send_request server thing could look like.

**Question-2:** To make it short, while I'm listening to my own writing, I'd prefer to handle the java-call as just a "normal" command line call and not implement the java-send_request thing.  Would this be ok?

Thank's in advance for some answer,
Alexander.

**Comment by pepijnve** [comment]
Q1: the plantuml approach with the Java daemon was put in place for performance reasons. Spawning a new JVM instance per diagram is fairly slow. To avoid that cost a single JVM instance is launched and used for all plantuml (and ditaa) diagrams. The downside of this approach is that we need to bundle all the required JAR files in the gem itself which makes the entire gem pretty big. Issues #67 and #137 are intended to resolve this, but I haven't made much progress on either yet.

Q2: The [Mermaid integration](https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/mermaid/extension.rb#L47) has a similar assumption on the output file name hardcoded. If you can't specify the output file name as a parameter there isn't really any other alternative.
Just FYI, the java server bit is a mini HTTP daemon. I implemented it like that to not have to invent an ad-hoc protocol. The HTTP request path determines the type of diagram, the request body is the diagram source and the `Accept` request header determines the output format. The generated diagram is sent back as the response body.
The code for the daemon itself is at https://github.com/pepijnve/asciidoctor-diagram-java/blob/master/src/main/java/org/asciidoctor/diagram/CommandProcessor.java
The PlantUML integration is at https://github.com/pepijnve/asciidoctor-diagram-java/blob/master/src/main/java/org/asciidoctor/diagram/PlantUML.java

**Comment by tigger** [comment]
I would like to add some additional feature request here. Specifying not only a slide, but a shape in a slide, e.g. a rectangle or a group, would be quite helpful:

```
pptx::somePowerpointFile.pptx[slide=1, shape='Rounded Rectangle 4', format=svg]
```

(slide could be optional, if the name is of the shape is unique)

**Comment by mojavelinux** [comment]
I like the idea, but I worry that this expands the scope of Asciidoctor Diagram too much. Perhaps we should have a separate extension for drawing tools, something like asciidoctor-draw (playing off of the name OpenOffice Draw). wdyt?

**Comment by rdmueller** [comment]
would be a nice feature. 
I've implemented such a feature a bit different (and not very clean) in docToolchain. Maybe my thoughts are helpful to you:

https://github.com/rdmueller/docToolchain/blob/master/build.gradle#L208
https://github.com/rdmueller/docToolchain/blob/master/scripts/exportPPT.vbs

The gradle build invokes a .vbs which searches for .pptx files and exports all slides as images and in addition all speaker notes as AsciiDoc. 

This let's you use PowerPoint as editor for your asciidoc and keeps both together.

...and currently I try to add some reveal.js magic to turn it back into a presentation...

An apache POI version would be much cleaner...

**Comment by uniqueck** [comment]
Based on the approach of @rdmueller , I wrote an extension for Microsoft Office documents. You are welcome to participate and implement additional features. For the extension see here [asciidoctorj-office-extension](https://github.com/uniqueck/asciidoctorj-office-extension)

**Comment by pepijnve** [comment]
I agree with @mojavelinux that this is outside the scope of what the diagram extension is trying to do. Diagram is about extending asciidoc plain text documents with embedded diagram also written as plain text. Converting other data formats into embeddable asciidoc content is kind of the reverse of that.
