### ISSUE TITLE
Wrong format selection for graphviz blocks

### ISSUE THREAD

**Issue by wimalopaan** [asciidoctor/asciidoctor-diagram#140]
Recently the behaviour of graphviz generated images changed. Since recently the generated images were in svg format. Now I have to specify the format explicitly (see example: first block). 

If I omit the format specifier, I get an pdf image, but that cannot be included into the html !? 

```
[graphviz, format="svg"]
----
digraph G { 
  V [shape=record; label="<l> a | b | ... | z | '\\0' ";]; 
  Zeiger_1 -> V:l; 
}
----

[graphviz]
----
digraph G { 
  V [shape=record; label="<l> a | b | ... | z | '\\0' ";]; 
  Zeiger_2 -> V:l; 
}
----

```

**Comment by pepijnve** [comment]
Oops. That's an accidental side effect of #135. I'll get this fixed asap.

**Comment by pepijnve** [comment]
@wimalopaan are you sure the default was SVG? As far as I can tell it used to be PNG.

**Comment by wimalopaan** [comment]
No, not sure. But it was definitely not pdf!
