### ISSUE TITLE
Feature request: Is there a way to support data uri format (base64 encoded image) for HTML output?

### ISSUE THREAD

**Issue by raghur** [asciidoctor/asciidoctor-diagram#143]
As the title says - it would be nice to have a self contained document as an option with the image being in inline `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..." />`

**Comment by mojavelinux** [comment]
Have you tried adding the `data-uri` attribute to the document header?

```
= Document Title
:data-uri:

body
```

**Comment by raghur** [comment]
Awesome... Thanks.
