### ISSUE TITLE
Loading diagrams from external files always treats target as relative path

### ISSUE THREAD

**Issue by jvmlet** [asciidoctor/asciidoctor-diagram#144]
According to the [documentation](https://github.com/asciidoctor/asciidoctor-diagram/blob/master/examples/features.adoc#loading-diagrams-from-external-files), the absolute path should be respected, but target is always treated as relative to doc directory, as a result the target is not found:

````
graphviz::${dotdir}/graph.dot[format="svg", align="center",opts="inline"]
````

gradle script:

`
asciidoctor {
    attributes  'dotdir': project.projectDir.absoluteFile
}
`

Error:
````
No such file or directory - D:/DHP/asp_core/pipeline/pipeline-initializer/src/docs/asciidoc/$D:/DHP/asp_core/pipeline/pipeline-initializer/graph.dot
````

**Comment by mojavelinux** [comment]
I think the problem is the leading `$` before `{dotdir}`. Attributes in AsciiDoc do not have a leading `$`. This is confusing the path resolver.

**Comment by jvmlet** [comment]
Thanks, @mojavelinux , my fault, too much SpEL.
