### ISSUE TITLE
Mermaid participants generates duplicates

### ISSUE THREAD

**Issue by di97mni** [asciidoctor/asciidoctor-diagram#146]
From the [docs](http://knsv.github.io/mermaid/#alt33)
>The participants can be defined implicitly as in the first example on this page. The participants or actors are
rendered in order of appearance in the diagram source text. Sometimes you might want to show the participants in a
different order than how they appear in the first message. It is possible to specify the actor's order of
appearance by doing the following:

This 
```
sequenceDiagram
    participant John
    participant Alice
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
```

generates this

![image](https://cloud.githubusercontent.com/assets/311406/24393773/a8eb905e-1399-11e7-9198-c1e0ea0453fb.png)

instead of this

![image](https://cloud.githubusercontent.com/assets/311406/24393788/beec882c-1399-11e7-86a0-20a04fc9e9e2.png)

**Comment by pepijnve** [comment]
@di97mni asciidoctor-diagram is only a passthrough layer. This is a question for the Mermaid community, so you should ask that in the issue tracker of that project (https://github.com/knsv/mermaid/).
