### ISSUE TITLE
blockdiag: can't create rackdiag diagram

### ISSUE THREAD

**Issue by jniggemann** [asciidoctor/asciidoctor-diagram#149]
What's wrong with the following minimal example:
```
lorem ipsum

[blockdiag]
----
rackdiag {
  // define height of rack
  16U;

  // define rack items
  1: UPS [2U];
  3: DB Server
  4: Web Server
  5: Web Server
  6: Web Server
  7: Load Balancer
  8: L3 Switch
}

----

lorem ipsum

```

The reproduceable error message is `asciidoctor-diagram: ERROR: Failed to generate image: blockdiag3 failed: ERROR: Got unexpected token at line 2 column 4`

I use
* Debian Jessie
* Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
* asciidoctor-diagram-1.5.1
* blockdiag3 1.4.7

**Comment by pepijnve** [comment]
You should use block type `rackdiag` Instead of `blockdiag`. In general for diagrams from the blockdiag family, you should use the same name as the corresponding CLI tool that can process the diagram.
