### ISSUE TITLE
Cygwin and UTF-8 in diagrams

### ISSUE THREAD

**Issue by tYYGH** [asciidoctor/asciidoctor-diagram#150]
Hi! I use asciidoctor in Cygwin. All files are UTF-8, and all is working fine for pure asciidoc. But asciidoctor-diagram somehow fails to manage UTF-8 characters:

```
= Test

[ditaa]
----
/-----\
|« … »|
\-----/
----
```
![diag-3e4f4c2390f3147eff18a6469397e2d0](https://user-images.githubusercontent.com/5556825/27381973-24f6f1c4-5685-11e7-9a37-49da086394d5.png)

Judging by the number of rectangles, the number of characters is right (ie. asciidoctor-diagram is not working on the individual bytes). It's just that non-ASCII characters do not get rendered.

More information:
```
$ env|grep -iE 'lc|lang'
LC_ALL=fr_FR.utf8
LANG=fr_FR.utf8
$ asciidoctor --version
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-cygwin]) (lc:UTF-8 fs:Windows-1252 in:- ex:UTF-8)
```

I ran `chcp.com 65001` in the current shell, by the way; before running these commands, and before generating the html5+png output.

**Comment by pepijnve** [comment]
Unicode should work correctly but I've seen issues with cygwin in the past. I did a quick check using your example in a unit test. Works correctly on macOS. 
![diag-780be31f6c80a701af5550da6e2df5d0](https://user-images.githubusercontent.com/225326/27385743-f10af09a-5693-11e7-93da-8e39b9d69feb.png)

I'll try to find some time to test on windows with cygwin asap.

**Comment by tYYGH** [comment]
Might be related to #151 (although I do not use the Java version…)

**Comment by mojavelinux** [comment]
@tYYGH That is correct. Asciidoctor assumes input is UTF-8, and this carries over to extensions as well. Some systems don't default to UTF-8. In fact, that is the case here:

> fs:Windows-1252

The -D flag forces Java to assume the input is UTF-8 (which it should if the goal really is run anywhere).

Why there are systems that don't default to UTF-8 is beyond me.

This flag should definitely be enabled.

**Comment by pepijnve** [comment]
This shouldn't matter for asciidoctor-diagram specifically though since it doesn't use the default encoding anywhere. I just checked the Ditaa integration code and as far as I can tell that's dealing with Unicode correctly as well; no default encoding assumptions.
I haven't been able to reproduce the issue so far, but perhaps by setting the default encoding to something different than UTF-8 I'll be able to. I'll give that a try.

**Comment by pepijnve** [comment]
Yep, that did the trick. Forcing the default encoding to ISO-8859-1 gave me this as a result. The fix for #151 is one possible solution, but I would prefer that the code is not dependent on this kind of external parameter value. I'll see if I can find another way to resolve this.
![diag-780be31f6c80a701af5550da6e2df5d0](https://user-images.githubusercontent.com/225326/27927484-32e85cba-628c-11e7-9af1-c82894e2eb2e.png)

**Comment by pepijnve** [comment]
Turns out Ditaa was doing some rather odd processing to the input data. I updated the Java code to not trigger that code path which fixes the problem. And it's a little bit more efficient as well.

**Comment by tYYGH** [comment]
Thank you pepijnve.
You say you updated the _Java_ code. What about ruby? I am using the command-line asciidoctor tool, not the Java version…

**Comment by pepijnve** [comment]
Ditaa is a Java library. The Ruby part of asciidoctor-diagram calls it indirectly using some additional Java code that provides a uniform interface to the Ruby code for both Ditaa and PlantUML. It's in this integration layer that I made some changes. This integration layer is used both when using MRI or JRuby.

**Comment by tYYGH** [comment]
Awesome! After gem update, it now works perfectly.

**Comment by mojavelinux** [comment]
Awesome news! Thanks Pepijn!

**Comment by habamax** [comment]
Hi @pepijnve , @mojavelinux suggested to let you know -- looks like there is still some problem with unicode and ditaa diagrams on windows.

See referenced issue from Asciidoctor-pdf #1000 

It might be also connected to plantuml version of ditaa -- I have just checked and it looks like I don't have ditaa installed and what I tried to use is actually plantuml http://plantuml.com/ditaa

I will try to reproduce it with normal ditaa...

**Comment by habamax** [comment]
I think I have tried the "real" ditaa :) with the command:

    ruby asciidoctor-pdf -r asciidoctor-diagram -a ditaa=C:/prg/bin/ditaa0_9.jar "C:\Users\maksim.kim\docs\test\test.adoc"

Not sure if it is correct way to do it. The result was the same -- corrupted unicode chars.

**Comment by pepijnve** [comment]
@habamax i’ll have a look when I get back home. On holiday at the moment. Could you provide me as much info as possible regarding the ruby version you’re using, the JRE, Windows, Cygwin, Windows installation language, etc in the meantime? Helps to reproduce issues.

There’s no way use a specific version of ditaa at the moment; the internal one always gets used. Afaik it’s superior to the ‘real’ one in the sense that it contains a number of bug fixes that never got upstreamed.
Upstream ditaa is kind of in a weird state at the moment. A rewrite in clojure was started but was never completed. Chances of getting my java bug fixes and improvements upstreamed are pretty slim...

**Comment by mojavelinux** [comment]
If there are instructions to follow, I'd be happy to test as well as I have a Windows machine in my testing lab.

**Comment by habamax** [comment]
@pepijnve It is barebone windows 10 without cygwin.

Ruby version: ruby 2.6.0p0 (2018-12-25 revision 66547) [x64-mingw32]

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Windows language: main one is English US, second input lang is russian.

Active code page in cmd.exe is: Active code page: 65001

**Comment by Mobe91** [comment]
Same issue here with Windows 10. I am using the asciidoctor gradle plugin (https://github.com/asciidoctor/asciidoctor-gradle-plugin) v1.5.8.1 with asciidoctor-diagram:1.5.18 and attempting to render a ditaa diagram. My input .adoc is UTF-8 encoded.

**Comment by habamax** [comment]
I have opened separate issue #233 clearly stated it is non-cygwin related
