### ISSUE TITLE
AsciidoctorDiagram doesn't work with Asciidoctor 1.5.6

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor-diagram#154]
Rendering a document containing a diagram with Asciidoctor 1.5.6 and Asciidoctor-Diagram 1.5.4 fails with a Nil error unless substitutions are explicitly defined for that block.
This is because https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/extensions.rb#L410-L417 returns nil instead of an empty list.

To reproduce try to render this document with Asciidoctor 1.5.6 and Asciidoctor-Diagram 1.5.4: 
```
= Document Title

[ditaa,asciidoctor-diagram-process]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        |---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....
```

**Comment by mojavelinux** [comment]
We've identified the problems upstream. It is safe to say that Asciidoctor 1.5.6 requires Asciidoctor Diagram 1.5.5 (the next release).
