### ISSUE TITLE
Add build job that runs against Asciidoctor master

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-diagram#157]
Add a job to the build that runs against the master branch of Asciidoctor core. This will allow us to discover incompatibilities immediately, when there is still time to fix them, instead of waiting for a release, when it's too late.

One this is set it up, we can add the asciidoctor-diagram repository to the list of dependent projects so that the build is triggered automatically whenever a change is made to the the master branch of Asciidoctor.

Both AsciidoctorJ and Asciidoctor.js have builds that run against the master branch of Asciidoctor core, so you can use those projects as reference.

**Comment by pepijnve** [comment]
@mojavelinux on Travis the test suite is now run against the latest released version of Asciidoctor and against master. The JRuby runs with master have issues now though. I think that's due to the Asciidoctor gemspec. Could you have a look at this? See https://travis-ci.org/asciidoctor/asciidoctor-diagram/jobs/253360783 for an example.

**Comment by mojavelinux** [comment]
Oh, perfect! Would you like me to trigger the build when a change is pushed to the master branch of Asciidcotor core?

FYI, this entry from Gemfile.master:

```
gem 'asciidoctor', :git => 'https://github.com/asciidoctor/asciidoctor', :branch => 'master'
```

can be simplified to:

```
gem 'asciidoctor', github: 'asciidoctor/asciidoctor'
```

**Comment by pepijnve** [comment]
The longer style is intentional. The builds are still running against Ruby 1.8 so I'm stuck with the old style named parameter syntax. The `github` option is actually advised against in the bundler docs for the time being.

> This shorthand should be avoided until Bundler 2.0, since it currently expands to an insecure git:// URL. This allows a man-in-the-middle attacker to compromise your system.

Any idea what might be causing the jruby issue?

**Comment by mojavelinux** [comment]
> The longer style is intentional. The builds are still running against Ruby 1.8 so I'm stuck with the old style named parameter syntax. The `github` option is actually advised against in the bundler docs for the time being.

Gotcha.

> Any idea what might be causing the jruby issue?

Stay tuned. I'm trying something.

**Comment by mojavelinux** [comment]
Okay, here's the fix.

https://github.com/asciidoctor/asciidoctor-diagram/pull/158

I think the problem was that:

a) gemspec needed to come first in the Gemfile

b) the BUNDLE_GEMFILE environment variable is more reliable when working with multiple gemfiles because it works with bundle exec

I also added a single build against master since it probably isn't necessary to run all the RVMs. But you could add more than one to the matrix if you want.

**Comment by mojavelinux** [comment]
With that in place, I'll update Asciidoctor core to trigger a build against Asciidoctor Diagram.

**Comment by mojavelinux** [comment]
Enabled! See https://github.com/asciidoctor/asciidoctor/blob/11eaf590d4ed2eceb5003e94de69791f025736d2/Rakefile#L142

**Comment by mojavelinux** [comment]
Technically, you don't need this line:

```
gem install bundler
```

Travis guarantees that bundler is present when using the ruby image.

**Comment by pepijnve** [comment]
I know. This is intended to update bundelt to the latest version.

**Comment by mojavelinux** [comment]
Got it.
