### ISSUE TITLE
Asciidoctor-Diagram fails on JRuby

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor-diagram#159]
I just tried to build a new AsciidoctorJ diagram.
But it doesn't generate a diagram and just emits this message:
```
asciidoctor-diagram: ERROR: Failed to generate image: Ditaa image generation failed: Invalid path '/ditaa'
```
Same for plantuml.

I couldn't reproduce it running the pure Ruby version.
I also got it working if I change `java.rb` to always behave like running on a native Ruby:
```ruby
#if RUBY_PLATFORM == "java"
#  require_relative 'java_jruby'
#else
  require_relative 'java_socket'
#end
```

**Comment by mojavelinux** [comment]
Do you think this is due to a change in Asciidoctor Diagram? In other words, does it work with Asciidoctor 1.5.5 and Asciidoctor Diagram 1.5.5? Or is Asciidoctor Diagram 1.5.5 not working in general?

**Comment by mojavelinux** [comment]
It would appear to have something to do with this:

https://github.com/asciidoctor/asciidoctor-diagram/commit/538662b794475c485bdf14e3cf6ecf7c5634f659

But that's just a hunch.

**Comment by robertpanzer** [comment]
I just ran it with asciidoctor 1.5.5 and asciidoctor-diagram 1.5.5 and it worked fine.
Something must be different on the Java path.

**Comment by mojavelinux** [comment]
Actually, I ran it with Asciidoctor 1.5.5 and Asciidoctor Diagram 1.5.5 and it failed in the same way. So I don't think this has to do with the Asciidoctor core upgrade.

**Comment by robertpanzer** [comment]
Oh. I ran it on a Ruby 2.4.0:
```
$ asciidoctor -v
Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```
You didn't by any chance run on a jruby?

**Comment by mojavelinux** [comment]
Sorry, I meant to say that I ran the AsciidoctorJ test suite with Asciidoctor 1.5.5 and Asciidoctor Diagram 1.5.5 and it failed in the same way as using Asciidoctor 1.5.6.

**Comment by mojavelinux** [comment]
It works if I use JRuby from the command line using Asciidoctor 1.5.6 and Asciidoctor Diagram 1.5.5.

**Comment by robertpanzer** [comment]
Ah, ok :)

**Comment by mojavelinux** [comment]
My next guess is that it isn't working when bundled in the jar (which is what you seemed to have been suggesting).

**Comment by mojavelinux** [comment]
Yep, if I make the distribution, then use the asciidoctorj command, I get the same error as in the test suite. So the issue seems to be when it is bundled in a jar.

**Comment by robertpanzer** [comment]
Hm.. Then I have no clue what could have gone wrong.
Even the hashes of the ditaa jars are the same.

**Comment by mojavelinux** [comment]
Right, but there are new jars and asciidoctor-diagram-java was replaced with server. So clearly what is happening is the server is not starting...because the path is actually a URL path that is not resolving.

**Comment by mojavelinux** [comment]
I say clearly, but I clearly don't know how that actually works ;)

**Comment by mojavelinux** [comment]
For what it's worth, the graphviz integration works. So we just need to figure out why the command server isn't running when the gem is loaded from the jar classpath. Hopefully Pepijn knows ;)

Pepijn, to test, just clone Asciidoctor:

```
git clone https://github.com/asciidoctor/asciidoctorj
```

Then update the version of Asciidoctor in build.gradle from 1.5.5 to 1.5.6. Then update the version of Asciidoctor Diagram in asciidoctorj-diagram/gradle.properties from 1.5.4 to 1.5.5.

Then run:

```
./gradlew build
```

or

```
./gradlew distZip
```

That will give you a distribution in asciidoctorj-distribution/build/distributions that provides the asciidoctorj command. 

Hopefully you'll be able to see what isn't loading.

**Comment by robertpanzer** [comment]
Tried to look into the server, but it seems like asciidoctor-diagram-java is not the current location of that code.

**Comment by pepijnve** [comment]
Let me help you out with your detective work :)
There was a change between .5 and .6 in how the Java code is structured. There are three jar files now, server-<version>.jar, ditaa-<version>.jar and plantuml-<version>.jar. Those all need to be on the class path in order for things to work correctly.
The jruby tests are passing so I'm not sure what's wrong right away. I don't think the gemspec is wrong since you can get things working using the socket based communication strategy.
The unit test suite is passing with JRuby as well so I don't think there's an issue with the in-process communication strategy either.
I'll try to reproduce this and let you know what I find.

**Comment by robertpanzer** [comment]
Cool, thank you!
If I understand it correctly and my brain doesn't trick me, I'd say that these jars are currently NOT part of the classpath, but they are inside the classpath. 
(Meaning jars inside a jar or jars on a path that is on the classpath)

Are that generators recognized as Service implementations of org.asciidoctor.diagram.DiagramGenerator?
If this is the case I could probably collect these files during the build and create on file inside asciidoctorj-diagram.jar.
If that doesn't work and the classes also have to be flat on the classpath I could also unpack them into the asciidoctorj-diagram.jar.
I'll try to figure out a way to do it, but I don't think I'll get to finish it this week.

**Comment by pepijnve** [comment]
Exactly, I modularised the code a little bit using ServiceLoader and friends. There are two implementations, one for Ditaa and one for PlantUML. The longer term goal is to make it possible to only depend on the minimum set of code needed for the diagram types you want to use. See the multigem branch of asciidoctor-diagram for details.

The classpath is built identically for the MRI and JRuby case so if one works and the other doesn't I'm really not sure what's going on. In both cases the implementation classes are loaded through the ServiceLoader mechanism.

**Comment by pepijnve** [comment]
Just double checked the gem packaging. The jars are all in the lib directory where they should be in the gem itself. Does asciidoctorj do any repackaging of the gem?

What also might be going wrong (but I don't understand why) is that the services are loaded too early for some reason when the implementation jars are not yet part of the classpath. The set of implementations is only loaded once in a static initialiser and that set may be getting initialised to an empty set.
No idea why that would happen with asciidoctorj and not in the unit tests with JRuby.

**Comment by robertpanzer** [comment]
Don't worry.
I have a better understanding now and know  what to look for.
Thanks for the help!

Pepijn Van Eeckhoudt <notifications@github.com> schrieb am Fr. 14. Juli
2017 um 15:11:

**Comment by robertpanzer** [comment]
Just tried to only add the services file to asciidoctorj-diagram and (as nearly expected) it fails with a ServiceConfigurationError because the service implies cannot be found.
I probably have to unpack the nested jars and merge the services files.
Closing this issue now as it is not really a problem of this project.

**Comment by mojavelinux** [comment]
> See the multigem branch of asciidoctor-diagram for details.

ooooh, this is interesting ;) I like. I can see asciidoctor-diagram-plantuml not only easier to consume, but likely to become a lot more popular for people searching. Nice.

**Comment by mojavelinux** [comment]
> The jruby tests are passing so I'm not sure what's wrong right away.

So here's the razor's edge. JRuby executed as a top-level Ruby runtime loads gems differently than Java running Ruby in embedded mode.  To use gems in embedded mode, they have to be repackaged as jar files, and they are loaded through the classpath mechanism.

But I don't think that's something the main Asciidoctor Diagram should have to worry about. That's where the test suite in AsciidoctorJ Diagram comes in (currently part of the AsciidoctorJ project, but being moved to its own repo). The focus of the AsciidoctorJ Diagram test suite is to make sure that repackaging does not introduce errors. So it's kind of a partnership...and certainly having triggered builds will help us detect any problems right away.

**Comment by mojavelinux** [comment]
And thanks for your input, @pepijnve!

**Comment by robertpanzer** [comment]
I just wonder though why JRuby apparently loads the server.jar but doesn't
"see" the other jars.

I'll also search in this direction.

Dan Allen <notifications@github.com> schrieb am Sa. 15. Juli 2017 um 00:28:

**Comment by mojavelinux** [comment]
That's exactly what I was wondering too.

**Comment by robertpanzer** [comment]
Maybe the jars aren't on the TCCL (that's what ServiceLoader.load() uses by
default).
I'll check what's happening.
Maybe there's another solution that is not as brutal as repackaging the
jars.

Dan Allen <notifications@github.com> schrieb am Sa. 15. Juli 2017 um 08:06:

**Comment by robertpanzer** [comment]
Seems like it's working correctly if I set the current JRubyClassLoader as the TCCL when rendering the document. 
Created asciidoctor/asciidoctorj#563 to fix this.

**Comment by robertpanzer** [comment]
Wanted to ask if there is already a version of asciidoctor-diagram that doesn't rely on the TCCL being set to the JRubyClassLoader?
It looks like the layout in Plantuml has changed significantly with the last releases and writing with a Live Preview and asciidoctor-diagram is full of surprises.

**Comment by pepijnve** [comment]
> Wanted to ask if there is already a version of asciidoctor-diagram that doesn't rely on the TCCL being set to the JRubyClassLoader?

No I haven't done any work in that area yet. I'm not sure what I need to change on my side to be honest. When [java_jruby.rb](https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/util/java_jruby.rb) is used, the code assumes it can `require` the jar files and that the classes in the jar files will be accessible for use after that. The alternative code path spins up a separate JVM instance.

Perhaps there's a third alternative, but I'm not really sure what that would be then. If you can point me in the right direction I'm happy to add whatever extra support is needed.

**Comment by robertpanzer** [comment]
Oh, seems like I commented in the wrong place [1]
Loading the service implementations with the class loader of the CommandServer should do the trick.

[1] https://github.com/asciidoctor/asciidoctorj/pull/563#issuecomment-315969440
