### ISSUE TITLE
Add support for mermaid.cli

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-diagram#163]
The mermaid CLI has been giving import errors since 7.0.12 and has been removed entirely in 7.1.0. It was replaced by the mermaid.cli package which provides the `mmdc` command. Unfortunately the supported command line parameters are completely different.
See if there's a way to add support for `mmdc` as well while still retaining backwards compatibility with the set of block attributes that the mermaid extension currently supports.

**Comment by athoune** [comment]
Magic appends here : https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/mermaid/extension.rb#L22

**Comment by pepijnve** [comment]
Yep, that's the spot where the logic would need to go. The problem is `mmdc` doesn't support parameters like `css`, `ganttConfig`, ... Ideally I would like the underlying CLI version to be transparent to the asciidoctor-diagram user, but that might simply not be feasible.

**Comment by pepijnve** [comment]
Starting with mermaid.cli 0.2.1 (I think) the necessary CLI options became available that allow adding support for `mmdc` in a way that's backwards compatible with the old CLI interface.
I'll integrate this and add support for the extended option list that `mmdc` supports (theme, background, full config file, ...)
