### ISSUE TITLE
PlantUML diagram hyperlinks don't work

### ISSUE THREAD

**Issue by naomi-owens** [asciidoctor/asciidoctor-diagram#166]
Hyperlinks don't appear to be working in PlantUML diagrams. According to PlantUML there is functionality for this and I believe the code below should work. The text is being formatted like a hyperlink i.e. it is blue and underlined but the link functionality isn't working.

```
[plantuml,_images/diagram,png]
----
@startuml

start
    :Do some stuff;
    :[[xref:pc-setup-guide/pc-setup-guide.adoc# Restore SQL database]];
    stop;
@enduml
----
```

![plantumlhyperlink](https://user-images.githubusercontent.com/1490245/30596834-3462b1a2-9d4d-11e7-8825-56bd13318462.png)

**Comment by pepijnve** [comment]
If you use PNG as output format it's expected that this doesn't work. It might work if you use SVG output; not 100% sure. I remember this coming up before. I'll try to find the previous discussion.

**Comment by pepijnve** [comment]
Issue #64 is what I had in mind.

**Comment by naomi-owens** [comment]
Thanks for the quick response! PlantUml itself does work with png as can be seen [here](http://plantuml.com/link) where an `<img>` and `<map>` seem to be created. Since you advise that PNG is not expected to work this way with asciidoctor-diagram I've switched to SVG as you suggest but with no luck.

Issue [#64 ](https://github.com/asciidoctor/asciidoctor-diagram/issues/64) mentions the svg is embedded in the html using an img tag as opposed to an object tag. 

I have attempted to use a passthrough block to define an svg object as follows:
```
++++
<object alt="diagram" width="713" height="903" data="_images/diagram.svg"></object>
++++
```
This does embed the svg as an object and hyperlinks are created, however the targets don't function properly. 

![nowhyperlinked](https://user-images.githubusercontent.com/1490245/30599798-84c30d56-9d55-11e7-9126-404bc759d882.png)

![target](https://user-images.githubusercontent.com/1490245/30599812-931b5200-9d55-11e7-9a63-ceeb6d78dac1.png)

**Comment by mojavelinux** [comment]
> Issue #64 mentions the svg is embedded in the html using an img tag as opposed to an object tag.

It should be possible to set the interactive or inline option on the image block, which will tell the converter to use either the object element or inline the SVG, respectively. Asciidoctor Diagram would just need to make sure it passed this option on to the block.

**Comment by mojavelinux** [comment]
> PlantUml itself does work with png as can be seen here where an <img> and <map> seem to be created.

The Asciidoctor HTML converter does not use the `<map>` element (nor do I think it should), so using PNG won't work.

**Comment by pepijnve** [comment]
Any attributes that are not consumed by the extensions are set on the resulting image block as is.

**Comment by mojavelinux** [comment]
Perfect! Than it should work. Just add

```
[%interactive]
```

**Comment by naomi-owens** [comment]
Using the following code I can reference an svg that has already been created and has hyperlinks.
```
[%interactive]
image::_images/diagram.svg[]
```
However how can I make a PlantUML example interactive? Should something like this work?

```
[plantuml, _images/diagram, svg, %interactive]
----
start
    :Do some stuff;
    :[[http:\\www.google.com Google]];
stop;
----
```

**Comment by mojavelinux** [comment]
The first position in the block attribute list should be:

plantuml%interactive

The shorthand syntax always goes in the first position.

That's short for:

plantuml, opts=interactive

**Comment by naomi-owens** [comment]
This works perfectly when published. The links don't function on the asciidoctor live preview chrome extension which had me fooled for a minute, but it works fine when I publish the .adoc to my server. Many thanks for your help.

**Comment by mojavelinux** [comment]
Great news!

The AsciiDoc Preview needs to be updated to the latest version to enable this feature. That's in progress. See https://github.com/asciidoctor/atom-asciidoc-preview/pull/235

**Comment by mattadamson** [comment]
Hi

I was wondering if I could reopen this as its related however if needed I can open a separate ticket. 

I was following from

https://plantuml.com/link

used the example in a puml file

[plantuml%interactive,_images/diagram, svg]
----
!pragma layout smetana
@startuml
actor Bob [[http://plantuml.com/sequence]]
actor "This is [[http://plantuml.com/sequence Alice]] actor" as Alice
Bob -> Alice [[http://plantuml.com/start]] : hello
note left [[http://plantuml.com/start]]
  a note with a link
end note
Alice -> Bob : hello with [[http://plantuml.com/start{Tooltip for message} some link]]
note right [[http://plantuml.com/start]] : another note
note left of Bob
You can use [[http://plantuml.com/start links in notes]] also.
end note
@enduml
----

I included it using svg output as recommended where links will work not png

include::diagram.puml[svg]

The diagram looks good rendered from ascii doc to HTML and loaded directly in the brower.  However no hyperlinks are shown or appear when we hover over

Thoughts please?
Thanks
Matt
