### ISSUE TITLE
Scaling for blockdiag

### ISSUE THREAD

**Issue by pela9** [asciidoctor/asciidoctor-diagram#168]
II use blockdiag in asciidoc sources to produce pdf images for further use in ->docbook->latex->pdf document generation.  This works great  but it would be useful if a scaling attribute could be added also for the blockdiag generator. Currently I get this effect by a hack, adding transparent nodes to the block diagram, but obviously this is kind of ugly and obucates the diagram specification.  (By the way, thanks for a nice library!)

**Comment by pepijnve** [comment]
I haven't tried this yet, but I would expect the standard asciidoc image scaling to work. Any block attributes that are not consumed by the diagram extension are copied over to the resulting image block verbatim. Have you tried the scaling options described at https://asciidoctor.org/docs/user-manual/#scaledwidth already?

**Comment by pela9** [comment]
Yes, this works! I had missed that the image attributes are passed. Sorry for bothering you with this.

**Comment by pepijnve** [comment]
No bother at all. Glad to hear this worked for you.
