### ISSUE TITLE
Inconsistent caption generated for plantuml txt

### ISSUE THREAD

**Issue by maverickwoo** [asciidoctor/asciidoctor-diagram#169]
I am using asciidoctor-diagram 0b056bc with asciidoctor 20f5019, both newest master as of this writing. Consider the following `foo.adoc`, where the two diagrams differ only in the output format (png vs. txt):

```adoc
= Caption inconsistency
:xrefstyle: full

== Figure using plantuml

Test <<fig:diagram-classes-png>> caption.

Test <<fig:diagram-classes-txt>> caption.

[[fig:diagram-classes-png]]
.Caption of our test plantuml diagram in png
[plantuml,sequence,png]
....
participant Bob
actor Alice

Bob -> Alice : hello
Alice -> Bob : Is it ok?
....

[[fig:diagram-classes-txt]]
.Caption of our test plantuml diagram in txt
[plantuml,sequence,txt]
....
participant Bob
actor Alice

Bob -> Alice : hello
Alice -> Bob : Is it ok?
....
```

In the output, we see `Figure 1. Caption of our test plantuml diagram in png` at the bottom of the png figure, and `Caption of our test plantuml diagram in txt` at the _top_ of the txt figure. I would expect the latter caption to be (i) at the bottom of the txt figure and (ii) numbered.

Perhaps this is related to #164?

Thanks!

**Comment by pepijnve** [comment]
The difference between PNG (or SVG) and TXT output is that the former generates an image block while the latter generates a literal block. In both cases the caption (`Figure <n> `) and title (`Caption of our test ...`) attributes are assigned to the generated block in the exact same way. It's up to the backend to decide if and how these get used and that's where things start to differ. The built-in HTML5 converter [uses the uncaptioned title for literal blocks](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L618). For [images blocks it uses the captioned_title](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L561). This is something that the diagram extension has no control over.
