### ISSUE TITLE
It'd be nice to have support for syntax diagrams

### ISSUE THREAD

**Issue by vinipsmaker** [asciidoctor/asciidoctor-diagram#170]
Maybe [this tool](http://bottlecaps.de/rr/ui) could be used for the heavy-work.

Actually I'm filling the issue as a “reminder”. Maybe I'll have time to implement it later, maybe not, or maybe I'll convert my diagrams to flowchart diagrams.

[Currently I'm using the LaTeX's `syntax` package](https://github.com/BoostGSoC14/boost.http/blob/aab1cd45cbb21314c1945e4c74e6c941f1f58091/doc/request.tex#L3) and then convert the result to SVG using Inkscape so I can embed it in asciidoc.

**Comment by pepijnve** [comment]
I've been looking for a good syntax/railroad diagram generator for a while now. The bottlecaps one unfortunately only exists as a web service; there's no way to install it locally. The best alternative I've been able to find so far is this one https://github.com/tabatkins/railroad-diagrams

**Comment by vinipsmaker** [comment]
> https://github.com/tabatkins/railroad-diagrams

Well, I like this tool. It's way prettier than the output of the LaTeX tool I'm currently using. Thanks for letting me know.

Is there something you don't like about this tool (given you mention that you're _still_ searching for a tool)?

**Comment by pepijnve** [comment]
I was just doing a search in the python package repository to check if that tool is installable using setuptools. That search provided [Syntrax](https://kevinpt.github.io/syntrax/) as a result as well. Looks like a more polished variant of the same idea. I'll have a look at integrating that instead.

**Comment by pepijnve** [comment]
> Is there something you don't like about this tool (given you mention that you're still searching for a tool)?

Just engineering gut feeling that tells me it's not really a polished tool just yet. That and that it didn't have a command line interface yet.

**Comment by vinipsmaker** [comment]
> https://kevinpt.github.io/syntrax/

Wow, this tool looks much more polished indeed. My Google-fu sucks. I'm 🤤 imagining how my documentation could be improved by using such tools.

**Comment by pepijnve** [comment]
First attempt all done. See the updated README for details on supported formats and attributes.

**Comment by vinipsmaker** [comment]
Wow, that was fast. Will test soon (probably tomorrow at latest). Will try to finish current commit now so I can test this one right away.

**Comment by vinipsmaker** [comment]
It's working perfectly:

![screenshot-2017-11-2 boost http](https://user-images.githubusercontent.com/865914/32341695-fadb0a6c-bfdc-11e7-883d-673e7d307a01.png)

Thanks!

**Comment by pepijnve** [comment]
You're welcome. Time for a new release.

**Comment by pepijnve** [comment]
This is included in 1.5.7
