### ISSUE TITLE
How to support the mind map?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-diagram#176]
I want to use mind map in Asciidoctor. I google it. But I did not get any information.

How to support the mind map?

**Comment by pepijnve** [comment]
Mind maps (and diagrams in general) are not supported in asciidoc out-of-the-box. This add-on adds block types that allow you to embed the source code for various types of diagrams in your asciidoc document. It uses existing external tools to convert the source code into images.

At the moment there is no integration for a mind map rendering tool. Is there any tool in particular you would like to see supported?

**Comment by iFwu** [comment]
A mac app with support for AsciiDoc called *Snow Flower Text* seems to support the mind map. However, it uses private lib to support it.

**Comment by pepijnve** [comment]
[PlantUML supports mind maps](http://plantuml.com/mindmap-diagram) these days. 1.5.17 will include support for this

**Comment by behrangsa** [comment]
> Mind maps (and diagrams in general) are not supported in asciidoc out-of-the-box. This add-on adds block types that allow you to embed the source code for various types of diagrams in your asciidoc document. It uses existing external tools to convert the source code into images.
> 
> At the moment there is no integration for a mind map rendering tool. Is there any tool in particular you would like to see supported?

FreeMind perhaps but looks like it is not in active development since 2016: http://freemind.sourceforge.net/
