### ISSUE TITLE
packetdiag ERROR: images do not match

### ISSUE THREAD

**Issue by crumgary** [asciidoctor/asciidoctor-diagram#179]
It looks like packetdiag has an issue with rotated text for png output but svg works.

When using the following asciidoc:

```
[packetdiag]
....
packetdiag{
  colwidth = 32
  node_height = 72

  0-15: Source Port [rotate = 270]
  16-31: Destination Port [rotate = 270]

}
....
```

I get this error
```
asciidoctor-diagram: ERROR: Failed to generate image: packetdiag.EXE failed: ERROR: images do not match
```

These links seem to suggest that the issue is with pillow.
https://bitbucket.org/blockdiag/blockdiag/issues/72/rotate-not-working-with-pillow-300-and-png
https://github.com/blockdiag/sphinxcontrib-blockdiag/issues/9

As a test hack, I changed the order in the following line:
https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/blockdiag/extension.rb#L80

from: 
```
[:png, :pdf, :svg].each do |f|
```

to:
```
[:svg, :png, :pdf].each do |f|
```

I just started using asciidoctor so I don't know what other issues could arise from changing the order, but it seems to work for me.

Since I'm new with asciidoctor, there might have already been a way to tell packetdiag to use svg without this change, but I didn't see anything when searching.

**Comment by crumgary** [comment]
after a little more reading the docs, asciidoctor-diagram does allow for telling packetdiag to use svg, 

Something like this:
```
[packetdiag, test_diagram, svg]
....
packetdiag{
  colwidth = 32
  node_height = 72
  0-15: Source Port [rotate = 270]
  16-31: Destination Port [rotate = 270]
}
....
```

**Comment by pepijnve** [comment]
@crumgary the 2nd attribute in your example above is the attribute named `format`. All diagram blocks support this attribute. There's a [table in the README](https://github.com/asciidoctor/asciidoctor-diagram#creating-a-diagram) that lists the supported formats per diagram type.

You can set the format at the block level like you're doing, or if you can set it globally for any type of diagram block by defining a document attribute of the form `<diagramtype>-format`.
So in your case set the attribute `packetdiag-format` to `svg`. You can do that in the asciidoc document itself in the [header section](https://asciidoctor.org/docs/user-manual/#setting-attributes-on-a-document) by adding `:packetdiag-format: svg`, or on the command line by adding `-a packetdiag-format=svg` as parameter.
