### ISSUE TITLE
Rendering PlantUML legends as SVG drops colors

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-diagram#184]
With the following legend in PlantUML

```plantuml
legend right
|= |= Type |
|<back:red>    </back>| Abcdef |
|<back:blue>    </back>| Uvwxyz |
endlegend
```

I get a nice PNG but an SVG without colors (cf. attached [test-results.zip](https://github.com/asciidoctor/asciidoctor-diagram/files/2089669/test-results.zip) - Github does not allow to upload SVGs directly).

// @ahus1

**Comment by pepijnve** [comment]
This is a plantuml rendering issue, not something the diagram extension controls. It's best to raise an issue in the issue tracker of that project.
If it has been fixed in a more recent version of plantuml than the embedded one, feel free to reopen this issue.

**Comment by ascheman** [comment]
Opened issue in PlantUML Forum: http://forum.plantuml.net/7831/rendering-plantuml-legends-as-svg-drops-colors
