### ISSUE TITLE
Newest version of Ascii2svg needs filename after "-o" in a separate argument 

### ISSUE THREAD

**Issue by wjl** [asciidoctor/asciidoctor-diagram#185]
The newest version of Ascii2svg (that the author re-wrote in Go) works fine, but needs the "-o" argument needs the filename to come in another argument (not packed into the same argument). One could argue this is a bug in Ascii2svg, but since:

1) it appears to work with the old version either way, and
2) it is pretty standard to put options to arguments in a separate argument,

it might be smart to just always split the filename into a separate argument. (e.g. instead of "-ofilename", use: "-o", "filename").

**Comment by pepijnve** [comment]
I did some basic testing and it doesn't look like the old version supported splitting the `-o` (or any other parameter) and it's argument. Will need to add a version check I guess.

**Comment by pepijnve** [comment]
Commit 8d872b5373fc24765ffde5f008b761623249ae5a resolved this and nobody complained. Not going to bother with a version check.
