### ISSUE TITLE
plantuml stdlib: include doesn't work as expected

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-diagram#186]
There is stdlib in plantuml which allows using different icons http://plantuml.com/stdlib.

With my current setup, I can generate the following diagram (from the plantuml examples):

```
@startuml
!include <font-awesome/common>
!include <font-awesome/server>
!include <font-awesome/database>

title Styling example

FA_SERVER(web1,web1) #Green
FA_SERVER(web2,web2) #Yellow
FA_SERVER(web3,web3) #Blue
FA_SERVER(web4,web4) #YellowGreen

FA_DATABASE(db1,LIVE,database,white) #RoyalBlue
FA_DATABASE(db2,SPARE,database) #Red

db1 <--> db2

web1 <--> db1
web2 <--> db1
web3 <--> db1
web4 <--> db1
@enduml

```

With the command `java -jar plantuml.jar test.txt` I can see the same result as on plantuml stdlib webpage.

And here is what I try to use with asciidoctor-diagram

```
[plantuml, stdlib, svg]
----
!include <font-awesome/common>
!include <font-awesome/server>
!include <font-awesome/database>

title Styling example

FA_SERVER(web1,web1) #Green
FA_SERVER(web2,web2) #Yellow
FA_SERVER(web3,web3) #Blue
FA_SERVER(web4,web4) #YellowGreen

FA_DATABASE(db1,LIVE,database,white) #RoyalBlue
FA_DATABASE(db2,SPARE,database) #Red

db1 <--> db2

web1 <--> db1
web2 <--> db1
web3 <--> db1
web4 <--> db1

----

```

and it doesn't work with the error:

![image](https://user-images.githubusercontent.com/234774/42519817-8a24ee0e-846d-11e8-83ab-25207990c57b.png)

![image](https://user-images.githubusercontent.com/234774/42519896-af7e44e8-846d-11e8-8c3b-00c1f0cd6902.png)

**Comment by habamax** [comment]
It looks like for the includes which are in <stdlib form> no path resolving should be done.

**Comment by habamax** [comment]
Well, I have checked the regex in `plantuml/extension.rb` file

  ```
    def preprocess_code(parent, source, tag)
        code = source.to_s
        base_dir = source.base_dir

        code = "@start#{tag}\n#{code}\n@end#{tag}" unless code.index "@start#{tag}"

        code.gsub!(/(?<=<img:)[^>]+(?=>)/) do |match|
          resolve_path(match, parent, parent.attr('imagesdir'))
        end

        # code.gsub!(/(?<=!include )[^!\n\r]+/) do |match|
        #   resolve_path(match, parent, base_dir)
        # end

        code.gsub!(/(?<=!include )[^<>!\n\r]+/) do |match|
          resolve_path(match, parent, base_dir)
        end

        code
      end
```
And it looks like if I change `code.gsub!(/(?<=!include )[^!\n\r]+/)` to `code.gsub!(/(?<=!include )[^<>!\n\r]+/)` it works for me. Basically I have just added `<>` symbols to the exceptions.

I am not sure I will be able to provide a pull request though :)

Could you check it pls?

**Comment by pepijnve** [comment]
I wasn't aware of this feature. Makes sense indeed, paths surrounded by `<>` shouldn't get processed. Your suggestion is in the right direction, but is slightly too coarse. It would also block resolution of any path that contains an angle bracket anywhere. `/(?<=!include\s+)[^<][^!\n\r]+/` should do the trick.

**Comment by habamax** [comment]
I have applied your change and... it doesn't work for me:

```
C:/prg/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-diagram-1.5.8/lib/asciidoctor-diagram/plantuml/extension.rb:65: invalid pattern in look-behind: /(?<=!include\s+)[^<][^!\n\r]+/
  Use --trace for backtrace
```

If I change `(?<=!include\s+)` to `(?<=!include )` -- it works.
If I change `(?<=!include\s+)` to `(?<=!include)\s+` -- it also works.

**Comment by pepijnve** [comment]
The regex in my initial comment was actually invalid. You can't use repetition in lookbehind which is why I had to use a different regex.
