### ISSUE TITLE
asciidoctor-diagram does not create diagrams for docbook

### ISSUE THREAD

**Issue by habamax** [asciidoctor/asciidoctor-diagram#188]
When you convert adoc files to docbook -- no diagrams are generated.

1. example `test.adoc` file:

```
= test
:author: Maxim Kim
:experimental:
:toc: left
:toclevels: 3
:icons: font
:autofit-option:
:sectnums:
:sectnumlevels: 4
:source-highlighter: rouge
:rouge-style: github
:revdate: 2018-07-10
:imagesdir: images
:pdf-style: default
:doctype: article

== check me


[plantuml, stdlib1, svg]
....
!include <font-awesome/common>
!include <font-awesome/server>
!include <font-awesome/database>

title Styling example

FA_SERVER(web1,web1) #Green
FA_SERVER(web2,web2) #Yellow
FA_SERVER(web3,web3) #Blue
FA_SERVER(web4,web4) #YellowGreen

FA_DATABASE(db1,LIVE,database,white) #RoyalBlue
FA_DATABASE(db2,SPARE,database) #Red

db1 <--> db2

web1 <--> db1
web2 <--> db1
web3 <--> db1
web4 <--> db1

....

```

2. asciidoctor command to convert `test.adoc` to `docbook.xml`

```
asciidoctor  -r asciidoctor-diagram -o docbook.xml -b docbook test.adoc
```

Adoc file is converted to Docbook but no image was generated in `image` folder.

When I convert to HTML or PDF I can see `image/stdlib1.svg` file generated.

PS 
I need it to create `docx` files out of asciidoctor. I usually do it with asciidoctor + pandoc.

1. convert adoc -> docbook with asciidoctor
2. convert docbook -> docx with pandoc

**Comment by pepijnve** [comment]
That's surprising. I wouldn't expect the backend to have any influence on diagram creation. To be honest I haven't used the docbook backend myself. I'll add a basic test case already to see if this is is simple to reproduce.

**Comment by pepijnve** [comment]
Turns out I already had test cases that use the `docbook` backend and those tests assert that the images get created. Not sure what's going wrong right away.

**Comment by habamax** [comment]
I noticed it when I did generate docbook before any other formats -- for a new file.

**Comment by habamax** [comment]
and the versions are

```
Asciidoctor 1.5.6.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]) (lc:IBM866 fs:Windows-1251 in:- ex:IBM866)

asciidoctor-diagram is 1.5.8
```

**Comment by habamax** [comment]
I tried different command and here are the results:

* `asciidoctor -r asciidoctor-diagram -o docbook.html -b html5 test.adoc` NO images
* `asciidoctor -r asciidoctor-diagram -o docbook.html test.adoc` NO images
* `asciidoctor -r asciidoctor-diagram test.adoc` IMAGES ARE THERE!
* `asciidoctor -r asciidoctor-diagram -b html5 test.adoc` IMAGES ARE THERE!
* `asciidoctor -r asciidoctor-diagram -b docbook test.adoc` IMAGES ARE THERE!

It looks like when there is `-o` parameter asciidoctor-diagram doesn't work.

**Comment by habamax** [comment]
Basically for my needs I have fixed the workflow I have -- just don't use `-o` as it generates the filename with the same basename+new extension.

Nevertheless -- this is kind of strange behaviour of asciidoctor :)

**Comment by mojavelinux** [comment]
> It looks like when there is -o parameter asciidoctor-diagram doesn't work.

Could it be that they are just ending up in the wrong place? Here's the logic that determines the output folder to use:

https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/extensions.rb#L245-L258

**Comment by habamax** [comment]
Hi @mojavelinux !

I have created a new file `testdiag.adoc`:

```
= test diags

== diag 1

[plantuml, qwerasdfzxcv, png]
....
skinparam dpi 200
skinparam ArrowColor black

hello -> world

....

```

Then run the command
asciidoctor -r asciidoctor-diagram -o testdiag.html -b html5 testdiag.adoc


No images in html, no images in the dir where `testdiag.adoc` is located, no `qwerasdfzxcv.png` image in my home directory (recursive search).

And if I add `:imagesdir: images` option -- the same thing -- there is no `qwerasdfzxcv.png` in `./images` dir.

Clearly the image is not created with `-o` option given.

**Comment by mojavelinux** [comment]
Aha! I figured it out. The behavior you observed was caused by a regression in Asciidoctor 1.5.6.2 (https://github.com/asciidoctor/asciidoctor/issues/2382), which has since been fixed.

I tried it with Asciidoctor 1.5.6.2 and I was able to reproduce your problem. I then upgraded to Asciidoctor 1.5.7.1 and verified that it solves the problem. Can you upgrade to Asciidoctor 1.5.7.1 and retest?

**Comment by habamax** [comment]
@mojavelinux yep, with the 1.5.7.1 version this is fixed.
Thx!

**Comment by mojavelinux** [comment]
:tada: :tada: :tada: 

Thanks for testing, @habamax. Onwards!
