### ISSUE TITLE
Add support for TikZ

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-diagram#189]
TikZiT is a powerful tool. It can draw mang mathematical diagram.

 Does AsciiDoctor Diagram support TikZiT?

TikZiT: <https://github.com/tikzit/tikzit>

**Comment by pepijnve** [comment]
If I understand it correctly TikZiT is a GUI editor for tikz. The is rather coupled to latex. We could make a little latex wrapper script similar to https://gist.github.com/jbenet/9449155 to render the graphics. That basically generates a mini latex document to wrap the tikz content and then uses `pdflatex` and `pdf2svg` to generate the images. Would something like that be useful?

**Comment by diguage** [comment]
@pepijnve Tikz is the tool I want to say. Sorry, I show a tool with a mistake.
If you can add the support for Tikz, it is a great news to me. Thank you very much.

**Comment by pepijnve** [comment]
@diguage I've pushed a first attempt at integrating tikz support. Could you try this out? Not 100% sure how you want to use this so any feedback is welcome.

https://github.com/asciidoctor/asciidoctor-diagram/blob/master/spec/tikz_spec.rb shows an example of how you can use the integration in its current form.

**Comment by joelsmith** [comment]
IMO, this is working well enough that this issue could be considered resolved and any subsequent bugs that may be discovered could be handled in their own issue.

What work remains on this feature? Documentations?

Thanks for adding another great diagram format!

**Comment by pepijnve** [comment]
Thanks for the feedback. I left this open waiting for some feedback from @diguage who asked for this originally. If you're saying it works for you then I think this issue can be closed indeed.
