### ISSUE TITLE
Use fixed prefix in auto-generated image name

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-diagram#19]
Currently, the rendered images that have auto-generated image names can be hard to cleanup because there is no easy way to refer to them as a group. Introduce a fixed prefix to the auto-generated name, such as `diag-`, so they can easily be identified in bulk.

You can make this prefix configurable using a document-level attribute, though that may be overkill.

**Comment by diguage** [comment]
How to config the prefix?

**Comment by mojavelinux** [comment]
The prefix does not appear to be configurable. A prefix is added if the target attribute is not specified.

**Comment by pepijnve** [comment]
Is it worth making this configurable? Easy enough to do via a doc attribute if this is desirable, but it's yet another switch to maintain, document, etc.
