### ISSUE TITLE
asciidoctor-diagram with WaveDrom CLI

### ISSUE THREAD

**Issue by hotwolf** [asciidoctor/asciidoctor-diagram#190]
On my computer I'm able to run WaveDrom CLI, but not the regular WaveDrom Editor.  According to the readme file, I would need to set the attributes "wavedrom" and "phantomjs" to give the tool the location of my WaveDrom CLI installation. After doing so, I still get the following error:

> asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the PATH or specify its location using the 'WaveDromEditor' document attribute

The "WaveDromEditor" attribute is not mentioned in the readme file.  Do I need to set a different attribute for using WaveDrom CLI? If so, what would it be and could that information be updated in the readme instruction?

**Comment by pepijnve** [comment]
On which operatief system are you having these issue? I’ll try to reproduce this ASAP.

**Comment by hotwolf** [comment]
Thanks for the fast response.
I'm using the "Windows Subsystem for Linux" (WSL) with the Debian installation.

**Comment by pepijnve** [comment]
That’s an environment I havent tested yet. There are some platform specific bits in the code that might be doing the wrong thing.
Could describe in a bit more detail how you have things set up? Is ruby installed as a Debian package or in Windows. What about wavedrom?

**Comment by hotwolf** [comment]
I'm using the Debian/Ubuntu packages for ruby (1:2.3.0+1), asciidoctor (1.5.4-1), and phantomjs (2.1.1+dfsg-1). I've installed asciidoctor-diagram through gem.  The Linux binaries, which are offered for download for the WaveDrom Editor did not run on my system, so I cloned the WaveDrom CLI git repository. I'm able to run the WaveDrom CLI standalone with the Ubuntu phantomjs installation.

**Comment by pepijnve** [comment]
Which values are you specifying for the `wavedrom` and `phantomjs` attributes? AFAICT if those point to the executables then this should work correctly.
I'll try to reproduce this as soon as I get a chance.

**Comment by hotwolf** [comment]
I've set the wavedrom attribute to the location of the "wavedrom-cli.js" script and the phantomjs attribute to the the shell script located at /usr/bin/phantomjs.

**Comment by pepijnve** [comment]
I think I've figured out what the issue is. The code that tries to find external binaries checks if the target files are executable. For the wavedrom-cli.js script this is not the case and is also not necessary. This is causing the detection code to fail which makes it fall back to the generic WaveDromEditor search code.

**Comment by pepijnve** [comment]
@hotwolf could you give the fix in #191 a try?

**Comment by hotwolf** [comment]
I just tried #190 and got:

asciidoctor-diagram: ERROR: Failed to gen

> erate image: undefined method `is_valid_executable' for #<Asciidoctor::Diagram::WavedromBlockProcessor:0x0000000267ad70>

I'll check out #191...

**Comment by pepijnve** [comment]
Made a small mistake, I pushed a new commit that fixes that problem to the `issue_190` branch.

**Comment by hotwolf** [comment]
I was searching for #191 : ) .

Am I doing something wrong for getting the above error with #190?

**Comment by pepijnve** [comment]
#190 is the issue. #191 is the pull request. :)

> Am I doing something wrong for getting the above error with #190?

No not at all, coding mistake on my part. If you checkout `issue_190` and do a pull it should work now.

**Comment by hotwolf** [comment]
Now, I'm back at the previous error message:

> asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the PATH or specify its location using the 'WaveDromEditor' document attribute

**Comment by pepijnve** [comment]
🤔 ok, I guess I'm going to have to set up a reproduction case for this one after all. Stay tuned...

**Comment by hotwolf** [comment]
Making  wavedrom-cli.js executable, doesn't change anything, either. It still produces the error message:

> asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the PATH or specify its location using the 'WaveDromEditor' document attribute

**Comment by pepijnve** [comment]
The lookup code in question is located at https://github.com/asciidoctor/asciidoctor-diagram/blob/issue_190/lib/asciidoctor-diagram/wavedrom/extension.rb#L22
Not sure it won't go in the first branch there. I'll have to create a setup similar to yours and hook up the debugger to figure this one out.

**Comment by pepijnve** [comment]
BTW, if you're comfortable making some small changes, you could throw some `puts` statements in there to check what's going on. Based on the first if statement I can only conclude either phantomjs or wavedrom-cli.js are not being found for whatever reason.

**Comment by hotwolf** [comment]
I"m not familiar with Ruby syntax, so I put is "puts" statements everywhere:

```
      def wavedrom(parent, source, format)
        wavedrom_cli = which(parent, 'wavedrom', :raise_on_error => false, :skip_executable_check => true)
        puts "reached: wavedrom_cli = which(parent, 'wavedrom', :raise_on_error => false, :skip_executable_check => true)"       
        phantomjs = which(parent, 'phantomjs', :alt_attrs => ['phantomjs_2'], :raise_on_error => false)
        puts "reached: phantomjs = which(parent, 'phantomjs', :alt_attrs => ['phantomjs_2'], :raise_on_error => false)"
        
        if wavedrom_cli && !wavedrom_cli.include?('WaveDromEditor') && phantomjs
          generate_file(wavedrom_cli, 'wvd', format.to_s, source.to_s) do |tool_path, input_path, output_path|
            [phantomjs, Platform.native_path(tool_path), '-i', Platform.native_path(input_path), "-#{format.to_s[0]}", Platform.native_path(output_path)]
            puts "reached: generate_file(wavedrom_cli, 'wvd', format.to_s, source.to_s) do |tool_path, input_path, output_path|..."
          end
        else
          if ::Asciidoctor::Diagram::Platform.os == :macosx
            wavedrom = which(parent, 'WaveDromEditor.app', :alt_cmds => ['wavedrom-editor.app'], :attrs => ['WaveDromEditorApp'],:path => ['/Applications'])
            puts "reached: wavedrom = which(parent, 'WaveDromEditor.app', :alt_cmds => ['wavedrom-editor.app'], :attrs => ['WaveDromEditorApp'],:path => ['/Applications'])"
            if wavedrom
              wavedrom = File.join(wavedrom, 'Contents/MacOS/nwjs')
              puts "reached: wavedrom = File.join(wavedrom, 'Contents/MacOS/nwjs')"
            end
          else
            wavedrom = which(parent, 'WaveDromEditor')
            puts "reached: wavedrom = which(parent, 'WaveDromEditor')"
          end

          generate_file(wavedrom, 'wvd', format.to_s, source.to_s) do |tool_path, input_path, output_path|
            [tool_path, 'source', Platform.native_path(input_path), format.to_s, Platform.native_path(output_path)]
            puts "reached: generate_file(wavedrom, 'wvd', format.to_s, source.to_s) do |tool_path, input_path, output_path|..."
          end
        end
      end
    end
```

This is the result:

> reached: wavedrom_cli = which(parent, 'wavedrom', :raise_on_error => false, :skip_executable_check => true)
> reached: phantomjs = which(parent, 'phantomjs', :alt_attrs => ['phantomjs_2'], :raise_on_error => false)
> asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the PATH or specify its location using the 'WaveDromEditor' document attribute

**Comment by pepijnve** [comment]
Try replacing
`puts "reached: wavedrom_cli = which(parent, 'wavedrom', :raise_on_error => false, :skip_executable_check => true)"`
with
`puts "waterdrom_cli = #{wavedrom_cli}"`

and the same for phantom_js. Within double quoted strings `#{expression}` is the ruby string interpolation syntax, so the example above will print the value of the `wavedrom_cli` variable.

**Comment by hotwolf** [comment]
"wavedrom_cli" is not set:

> waterdrom_cli =
> phantomjs = /usr/bin/phantomjs
> asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the PATH or specify its location using the 'WaveDromEditor' document attribute

**Comment by pepijnve** [comment]
Ok so resolution of the wavedrom attribute seems to be failing. The lookup code is at https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/util/which.rb#L19
Would you mind adding some `puts` output in there as well?

**Comment by hotwolf** [comment]
These are the "puts" commands, that I've added:

```
...
      def self.is_valid_executable(exe, options)
        (options[:skip_executable_check] || File.executable?(exe))
      end

      def which(parent_block, cmd, options = {})
        attr_names = options[:attrs] || options.fetch(:alt_attrs, []) + [cmd]
        puts "attr_names = #{attr_names}"
        cmd_names = [cmd] + options.fetch(:alt_cmds, [])
        puts "cmd_names = #{cmd_names}"
        cmd_var = 'cmd-' + attr_names[0]
        puts "cmd_var = #{cmd_var}"

        if config.key? cmd_var
          cmd_path = config[cmd_var]
        else
          cmd_path = attr_names.map { |attr_name| parent_block.attr(attr_name, nil, true) }.find { |attr| !attr.nil? }

          unless cmd_path && ::Asciidoctor::Diagram::Which.is_valid_executable(cmd_path, options)
            cmd_paths = cmd_names.map do |c|
              ::Asciidoctor::Diagram::Which.which(c, :path => options[:path])
            end

            cmd_path = cmd_paths.reject { |c| c.nil? }.first
          end
          puts "cmd_path = #{cmd_path}"

          config[cmd_var] = cmd_path
...

```

And this is the output, they've produced:

> attr_names = ["wavedrom"]
> cmd_names = ["wavedrom"]
> cmd_var = cmd-wavedrom
> cmd_path =
> waverdrom_cli =
> attr_names = ["phantomjs_2", "phantomjs"]
> cmd_names = ["phantomjs"]
> cmd_var = cmd-phantomjs_2
> cmd_path = /usr/bin/phantomjs
> phantomjs = /usr/bin/phantomjs
> attr_names = ["WaveDromEditor"]
> cmd_names = ["WaveDromEditor"]
> cmd_var = cmd-WaveDromEditor
> cmd_path =
> asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the PATH or specify its location using the 'WaveDromEditor' document attribute

I'm going to be offline for the next few weeks.  If you need me to try out anything else, please post it here and I'll pick it up in September.

**Comment by pepijnve** [comment]
I tried to reproduce this locally, but no success so far. I set the `wavedrom` attribute to `/usr/local/lib/node_modules/wavedrom-cli/bin/wavedrom-cli.js` and that gets picked up correctly.

This was on a mac though. I'll try this on Windows when I get a chance.

**Comment by drom** [comment]
I have a new version of wavedrom v2.1.2 here: https://github.com/wavedrom/wavedrom
it comes with browserless CLI. https://github.com/wavedrom/wavedrom/releases/tag/v2.1.2
It is a single file application and requires only `node.js` to run.

```bash
node -i sourceWaveDrom.json5 > result.svg
```
Current version can produce only `SVG`. Do we need `PNG`?

**Comment by pepijnve** [comment]
wavedrom is tested on all platforms in the test suite now.
