### ISSUE TITLE
Bad figure numbering when loading from external files 

### ISSUE THREAD

**Issue by rohel01** [asciidoctor/asciidoctor-diagram#192]
Hello,

I am using Asciidoctor 1.5.4-1 with asciidoctor-diagram 1.5.9 on Ubuntu 16.04.

I have noticed figure numbering is wrong (the counter is incremented twice) when using the "load from external file" syntax. Am I doing something wrong ?

I have attached a small example to demonstrate the issue.

[example.tar.gz](https://github.com/asciidoctor/asciidoctor-diagram/files/2314432/example.tar.gz)

**Comment by pepijnve** [comment]
Could you try again with asciidoctor 1.5.7? Seems to work fine for me with that version.

**Comment by DrHST** [comment]
Hello , I work with maven

                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>2.0.0-RC.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-pdf</artifactId>
                        <version>1.5.0-beta.4</version>
                    </dependency>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-diagram</artifactId>
                        <version>1.5.18</version>
...
                       <require>asciidoctor-diagram</require>
                    </requires>

the following situation:

:desc-image1: description image 1
[id="image1",reftext="{figure-caption} {counter:figures}"]
.{desc-image1}
image::image1.png[align="center"]

:desc-plantuml: description plantuml
[id="plantuml",reftext="{figure-caption} {counter:figures}"]
.{figure-caption} {figures}: {desc-plantuml}
plantuml::images/plantuml.puml[align="center"]

:desc-image2: description image 2
[id="image2",reftext="{figure-caption} {counter:figures}"]
.{desc-image2}
image::image2.png[align="center"]

----
please observe, I added {figure-caption} {figures}:     in the plantuml part
---
So I have two problems (The images are correct!):

1) a wrong numbering of the image2 in the text  (html and pdf)

Figure 2: description image 2   expected    Figure 3: description image 2

2) The Caption and the number is not generated automatically at plantuml . Why?

Figure 1: description image 1
description plantuml                 expected    Figure 2: description plantuml
Figure 2: description image 2   expected    Figure 3: description image 2

is the problem located in line 609 of parser.rb the reason in 2.0.0.RC1?

**Comment by DrHST** [comment]
<asciidoctor.maven.plugin.version>2.0.0-RC.1</asciidoctor.maven.plugin.version>
    <asciidoctorj.pdf.version>1.5.0-beta.**7**</asciidoctorj.pdf.version>
    <asciidoctorj.version>**2.1.0**</asciidoctorj.version>
    <asciidoctor.diagram.version>1.5.18</asciidoctor.diagram.version>

By using this versions the counting is working

**Comment by pepijnve** [comment]
Thanks for the update @DrHST. I kind of suspected this would be an issue in asciidoctor core rather than the diagram extension and this confirms my hunch. The diagram extension asks the core to assign a caption to the generated image blocks, but doesn't actually do the numbering itself.

**Comment by pepijnve** [comment]
The call to `assign_caption` at https://github.com/asciidoctor/asciidoctor-diagram/blob/v1.5.18/lib/asciidoctor-diagram/extensions.rb#L129 is what I'm referring to.

Is it ok for you to close this issue then since it seems you've been able to resolve the problem?

**Comment by DrHST** [comment]
Hello Peijn,

I only hooked on the old issue of “rohel01”

For me – comparing with his example – it seems to be fixed…

Bye

Hendrik

PS: Thank you for your great work on asciidoctor-diagram

Von: Pepijn Van Eeckhoudt <notifications@github.com>
Gesendet: Freitag, 22. November 2019 10:51
An: asciidoctor/asciidoctor-diagram <asciidoctor-diagram@noreply.github.com>
Cc: Hendrik Timmermann <Hendrik.Timmermann@msg.group>; Mention <mention@noreply.github.com>
Betreff: Re: [asciidoctor/asciidoctor-diagram] Bad figure numbering when loading from external files (#192)


The call to assign_caption at https://github.com/asciidoctor/asciidoctor-diagram/blob/v1.5.18/lib/asciidoctor-diagram/extensions.rb#L129 is what I'm referring to.

Is it ok for you to close this issue then since it seems you've been able to resolve the problem?

**Comment by pepijnve** [comment]
Alright then. Closing since it worked for me, works for you now and we've had no other updates in over a year.
