### ISSUE TITLE
When using JRuby: warning: instance variable @loaded not initialized

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#194]
I'm using asciidoctor-diagram-1.5.9 with JRuby and I get the following warning: 

uri:classloader:/gems/asciidoctor-diagram-1.5.9/lib/asciidoctor-diagram/util/java_jruby.rb:10: warning: instance variable `@loaded` not initialized

Should the variable `@loaded` be initialized in this file?

**Comment by pepijnve** [comment]
The code still uses the bad practice of lazily defining instance variables on first use. The code works correctly, but you get this (harmless) warning as a consequence.
`@loaded` should be initialised to `false` to silence this.

**Comment by ahus1** [comment]
I'm currently integrating the latest version of asciidoctor and asciidoctor-diagram into the [IntelliJ Asciidoctor plugin](https://github.com/asciidoctor/asciidoctor-intellij-plugin). The warning appears in the IDE's console when you use an Asciidoctor Diagram the first time in a session. 

I would be thankful if someone with more Ruby knowledge could lend a hand here to avoid this warning.

**Comment by pepijnve** [comment]
@ahus1 this needs to be fixed in the code. Just haven't gotten round to it yet.
