### ISSUE TITLE
Failed to generate Graphviz image

### ISSUE THREAD

**Issue by amontgom** [asciidoctor/asciidoctor-diagram#202]
Hey,

I'm trying to convert some AsciiDoctor code to HTML using the command line on Windows 10. The command I use is this:

> asciidoctor -r asciidoctor-diagram UserDoc.adoc

On this AsciiDoc code:

```
= Title

text block

== header

text block


["graphviz", "plot1.png"]
-----------------------------------------------
digraph plot1 {
  rankdir=LR;
  Nissan;
  Infiniti;
  Toyota;
  Lexus;

  nissan -> infiniti [label = "has_luxury_division"];
  toyota -> lexus [label = "has_luxury_division"];
  "Title" [shape = plaintext];
}
-----------------------------------------------

["graphviz", "plot2.png"]
-----------------------------------------------
digraph plot2 {
  rankdir=LR;
  Japan;
  Nissan;
  Toyota;

  nissan -> japan [label = "country_of_origin"];
  nissan -> japan [label = "country_of_origin"];
  "Title" [shape = plaintext];
}
-----------------------------------------------
```

And the result I get is this:

> asciidoctor-diagram: ERROR: Failed to generate image: dot.BAT failed: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/dot-0.1.0/bin/dot:91:in `<top (required)>': invalid option: -oC:\Users\User\AppData\Local\Temp\dot.BAT20181112-16488-174aqjf.png (OptionParser::InvalidOption)
>         from C:/Ruby25-x64/bin/dot:23:in `load'
>         from C:/Ruby25-x64/bin/dot:23:in `<main>'
> asciidoctor-diagram: ERROR: Failed to generate image: dot.BAT failed: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/dot-0.1.0/bin/dot:91:in `<top (required)>': invalid option: -oC:\Users\User\AppData\Local\Temp\dot.BAT20181112-16488-hmvb0b.png (OptionParser::InvalidOption)
>         from C:/Ruby25-x64/bin/dot:23:in `load'
>         from C:/Ruby25-x64/bin/dot:23:in `<main>'

I have gem installed asciidoctor-1.5.8, asciidoctor-diagram-1.5.11, graphviz-1.1.0, and dot-0.1.0. The weird thing is on AsciidocFX it comes out just fine, producing the images clearly and cleanly, but unfortunately I need to use the command line.

Does anyone know how I can fix this? Thanks.

**Comment by pepijnve** [comment]
The diagram extension is picking up `dot` from `C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/dot-0.1.0/bin/dot`. That's a binary from [the dot gem](https://github.com/jakesandlund/dot), not the graphviz binary.
There are two ways you can resolve this:

- Modify your `PATH` environment variable so that the graphviz installation directory comes before the ruby gems binary directory. The diagram extension should then pick up the right binary. It simply scans `PATH` and uses the first executable with the correct name that it can find.
- Specify the location of `dot` manually via a document attribute. Adding `-a graphvizdot <path to dot>` to your CLI options should do the trick.

**Comment by amontgom** [comment]
Accidentally closed the issue -- please ignore the above.

Thank you for your response, pepijnve. Unfortunately, neither of these worked. I modified the Path with both C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\graphviz-1.1.0\lib\graphviz.rb and C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\graphviz-1.1.0\lib, in sequence, and got the same error in both cases. Here is my current path:

> PATH=C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;c:\Program Files (x86)\GnuWin32\bin;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Git\cmd;C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\graphviz-1.1.0\lib;C:\Ruby25-x64\bin;C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python37\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\atom\bin;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Local\atom\bin;

I also tried the second, using both the commands:

> asciidoctor -r asciidoctor-diagram -a graphvizdot C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\dot-0.1.0\bin\dot UserDoc.adoc

and

> asciidoctor -r asciidoctor-diagram -a graphvizdot C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\graphviz-1.1.0\lib\graphviz.rb UserDoc.adoc

This has the same result, though the latter case has the addition of five iterations of

> asciidoctor: ERROR: graphviz.rb: line 4: level 0 sections can only be used when doctype is book

preceding the normal error. I have also combined these two suggestions, with a similar result.

Do you have any other ideas? Thank you.

**Comment by pepijnve** [comment]
You need to point to the `dot` executable of graphviz itself.
`C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\dot-0.1.0\bin\dot` will definitely not work; that's something completely different.
`C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\graphviz-1.1.0\lib\graphviz.rb` won't work either, that's part of a graphviz related ruby gem.
Unfortunately I can't be more specific than this; I don't know where you installed graphviz on your machine. FWIW, the installer from https://graphviz.gitlab.io/_pages/Download/Download_windows.html installs to `C:\Program Files (x86)\Graphviz2.38\` by default. If I install that, the `dot` executable is at `C:\Program Files (x86)\Graphviz2.38\bin\dot`.

**Comment by amontgom** [comment]
Thank you for clearing that up. The dot executable was indeed where you suggested, in C:\Program Files (x86)\Graphviz2.38\bin. Unfortunately, using the command

> asciidoctor -a graphvizdot "C:\Program Files (x86)\Graphviz2.38\bin\dot" -r asciidoctor-diagram UserDoc.adoc

results in 

> asciidoctor: FAILED: input file C:/Program Files (x86)/Graphviz2.38/bin/dot is missing

It is necessary to use "dot.exe" instead. However, when using dot.exe, the result is an error:

> asciidoctor: FAILED: C:/Program Files (x86)/Graphviz2.38/bin/dot.exe: Failed to load AsciiDoc document - invalid byte sequence in UTF-8

When traced, this is the full error:

> Traceback (most recent call last):
>         15: from C:/Ruby25-x64/bin/asciidoctor:23:in `<main>'
>         14: from C:/Ruby25-x64/bin/asciidoctor:23:in `load'
>         13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/bin/asciidoctor:14:in `<top (required)>'
>         12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
>         11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `each'
>         10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
>          9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `convert_file'
>          8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `open'
>          7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `block in convert_file'
>          6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1479:in `convert'
>          5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1367:in `load'
>          4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:570:in `parse'
>          3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:98:in `parse'
>          2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:369:in `next_section'
>          1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:641:in `next_block'
> C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:641:in `match?': asciidoctor: FAILED: C:/Program Files (x86)/Graphviz2.38/bin/dot.exe: Failed to load AsciiDoc document - invalid byte sequence in UTF-8 (ArgumentError)

Looking at the parser, it looks like it doesn't like the dot.exe? I'm not sure how to resolve this; is there some version of dot.exe that lacks the executable file extension? I can't seem to find a "dot" in the Ruby folder, outside of dot-0.1.0. Thank you.

**Comment by pepijnve** [comment]
🤦‍♂️ my bad. That needs to be `-a key=value` so `-a graphvizdot="C:\Program Files (x86)\Graphviz2.38\bin\dot.exe"`

**Comment by amontgom** [comment]
That worked perfectly, thanks!

**Comment by amontgom** [comment]
Hey,

I've been having an odd problem. Two weeks ago when I closed this issue, the code was working fine; I was able to use the command:

`asciidoctor -a graphvizdot="C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" -r asciidoctor-diagram UserDoc.adoc`

to create an HTML from some AsciiDoctor code, along with some nice graphs. Now, when I am trying to run the command on the code:

```
= Title

text block

== Header

text block

.Dataframe Title
[options="header,footer"]
|=======================
|EFIN |Orig_phone |ptin |Signed_name |Orig_signed_name 
|1234 |888-888-8888 |2345 |Deb T |Deb T 
|987 |111-111-1111 |9876 |Bob Z | Bob Z 

|=======================

text block

["graphviz", "plot1.png"]
-----------------------------------------------
digraph plot1 {
  rankdir=LR;

  nissan;
  infiniti;
  toyota;
  lexus;
  japan;

  nissan -> infiniti [label = "has_luxury_division"];
  toyota -> lexus [label = "has_luxury_division"];
  nissan -> japan [label = "country_of_origin"];
  toyota -> japan [label = "country_of_origin"];

  "Title" [shape = plaintext];
}
-----------------------------------------------


["graphviz", "plot2.png"]
-----------------------------------------------
digraph plot2 {
  rankdir=LR;

  japan;
  nissan;
  toyota;

  nissan -> japan [label = "country_of_origin"];
  toyota -> japan [label = "country_of_origin"];

  "Title" [shape = plaintext];
}
-----------------------------------------------
```

the resulting HTML has neither Graphviz plots nor the table. Instead, it is a jumble of the code above:

```
Title
text block
== Header
text block .Dataframe Title [options="header,footer"] |======================= |EFIN |Orig_phone |ptin |Signed_name |Orig_signed_name |1234 |888-888-8888 |2345 |Deb T |Deb T |987 |111-111-1111 |9876 |Bob Z | Bob Z |======================= text block ["graphviz", "plot1.png"] ----------------------------------------------- digraph plot1 { rankdir=LR; nissan; infiniti; toyota; lexus; japan; nissan → infiniti [label = "has_luxury_division"]; toyota → lexus [label = "has_luxury_division"]; nissan → japan [label = "country_of_origin"]; toyota → japan [label = "country_of_origin"]; "Title" [shape = plaintext]; } ----------------------------------------------- ["graphviz", "plot2.png"] ----------------------------------------------- digraph plot2 { rankdir=LR; japan; nissan; toyota; nissan → japan [label = "country_of_origin"]; toyota → japan [label = "country_of_origin"]; "Title" [shape = plaintext]; } -----------------------------------------------
```

The weird thing is, if I first open the code in AsciidocFX, which among other things generates the .pngs, the HTML shows up as I would like. Unfortunately, I need to be able to generate this doc from the command line without needing to go through AsciidocFX. Is there some way to modify the command to generate the .pngs and table, so that it all turns out as it should? Thanks.

**Comment by mojavelinux** [comment]
Could it be that the editor is changing the endlines to `\r`?

**Comment by amontgom** [comment]
That does seem to have been the problem, and it had an easy, non-AsciiDoctor-related fix. Thank you very much!
