### ISSUE TITLE
Update batik dependency

### ISSUE THREAD

**Issue by matsev** [asciidoctor/asciidoctor-diagram#203]
The `batik-all-1.7.jar` has several known security vulnerabilities and should be updated. Latest version is currently [1.10](https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-all).

Ref: [NIST National Vulnerability Database](https://nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Aapache%3Abatik%3A1.7)

**Comment by pepijnve** [comment]
Thanks for the notification. PlantUML seems to still depend on 1.7, but from what I've been able to test it works fine with 1.10.
