### ISSUE TITLE
asciidoctor-diagram fails when placed in table (1.5.12)

### ISSUE THREAD

**Issue by emillindqvist90** [asciidoctor/asciidoctor-diagram#212]
In lib\asciidoctor-diagram\extensions.rb:285 

spelling error ("docuemnt"), causing embedded diagrams in tables to fail to generate

**Comment by pepijnve** [comment]
🤦‍♂️ odd that the test suite doesn't pick this up. I'll try to get this fixed asap.

**Comment by pepijnve** [comment]
1.5.12 introduced this regression. Sorry about that. I've added test cases, fixed the issue and published 1.5.13 which fixes this.

**Comment by emillindqvist90** [comment]
Thank you Pepijn!

**Comment by mojavelinux** [comment]
Really nice find @emillindqvist90. Thanks!
