### ISSUE TITLE
plantuml behind proxy

### ISSUE THREAD

**Issue by hakandilek** [asciidoctor/asciidoctor-diagram#215]
I've gone through the documentation and partially through the code but could not really find the answer.

I'm trying to generate plantuml diagrams with `!includeurl` directives behind a corporate proxy. I've tried to set up `HTTP_PROXY` and `HTTPS_PROXY` environment variables, and `JAVA_ARGS` but none of them helped.

My docs look basically like this:
```
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND

title System Context


@enduml
```

**Comment by pepijnve** [comment]
I think I'll have to add `-Djava.net.useSystemProxies=true` to the JVM startup flags in order to get that to work. Not something I've needed myself so I haven't tested that kind of setup.

**Comment by hakandilek** [comment]
There you go.
