### ISSUE TITLE
Update bundled PlantUML and add new diagram types

### ISSUE THREAD

**Issue by lorrden** [asciidoctor/asciidoctor-diagram#222]
The latest plantuml supports. mind maps and work breakdown structure diagrams, neither which seem to work in asciidoctor-diagram at the moment. I would assume there need to be a diagram-wbs and diagram-mindmap type for this.

Note that the gantt diagrams work fine already though.

**Comment by lorrden** [comment]
Now that the latest plantuml jar is in, it would be. nice to look at what diagrams that work.

Currently @startuml works some of the other diagrams may work when plantuml can deduce the type automatically (gantt works inside @startuml blocks).

The other diagrams supported by plantuml includes:

- @startditaa (a bit redundant since ditaa has its own blocks, but anyway)
- @startsalt (seems to be supported, but not documented, there is a ruby class for it at least?)
- @startgantt (accidentally work as plantuml handles this in @startuml blocks as well)
- @startwbs
- @startmindmap
- @startmath
- @startlatex

**Comment by pepijnve** [comment]
8fa6447 relaxes the start/end detection code a bit. With that change you should be able to use the various plantuml diagram types. If @start/@end is not found the code will be surrounded with @startuml/@enduml like before.
