### ISSUE TITLE
Surface PlantUML diagram generation problems to asciidoctor

### ISSUE THREAD

**Issue by knl** [asciidoctor/asciidoctor-diagram#231]
When PlantUML encounters an error in the diagram, it will still generate the diagram, containing the snapshot of the code and the error. Then, it will continue generating diagrams, making it really hard to spot errors.

There is a flag for PlantUML `-failfast` which causes it "To stop processing as soon as a syntax error in diagram occurs". Would it be possible to somehow pass that flag to PlantUML?

**Comment by knl** [comment]
Can I please get any response on this issue? Is this something planned to be fixed, or is it not recognized as a problem? Is there a workaround for this?

**Comment by pepijnve** [comment]
Sorry for the delayed response. Please understand that this project is maintained on a volunteer basis.

I opened the relevant project in my IDE to see how large a change this would require and it turns out I had everything done already, just hadn't committed it yet. I'll try to get this integrated asap.

**Comment by knl** [comment]
Hi Pepijn,
Thanks for responding quickly. Awesome that you already have a fix. If I can help (not just with this issue), please let me know.

**Comment by pepijnve** [comment]
Quick update, the fix I though I had unfortunately doesn't work. Setting the 'fail fast' option in the code has no effect whatsoever; it's only taken into account in PlantUML's file based processing code, not in the String based code. 🙄 Doesn't surprise me TBH.

The code that I'm using from PlantUML here is only 10-20 lines, so I'm going to inline that and add my own error intercepting logic. Just struggling a bit to get a formatted error report out. The code that does that is hidden in private methods in PlantUML.

Anyway, just wanted to let you know I'm working on it, but it will take slightly longer than expected.

**Comment by pepijnve** [comment]
https://github.com/asciidoctor/asciidoctor-diagram-java/commit/b55ead6c5f568500ba2257464a35b1fe6aae07ea takes care of surfacing the errors as well as possible, but PlantUML is such a mess internally that it's impossible to get everything out.

The code path that reports that `dot` could not be found for instance still insists on swallowing the error, writing it out to an image and pretending everything is fine. There's no way to intercept AFAICT.

Anyway, after this change syntax errors are at least reported the way you would expect.

**Comment by knl** [comment]
Thanks a lot @pepijnve, looks great!
