### ISSUE TITLE
Please support state-machine-cat

### ISSUE THREAD

**Issue by baronTommy** [asciidoctor/asciidoctor-diagram#234]
## Please support state-machine-cat

- https://github.com/sverweij/state-machine-cat

![state-machine-cat](https://raw.githubusercontent.com/sverweij/state-machine-cat/master/docs/pics/smcat-full-small.png)

**Comment by pepijnve** [comment]
:+1: should be aan easy one to add.

**Comment by baronTommy** [comment]
![ありがとう](https://stickershop.line-scdn.net/stickershop/v1/product/1303592/LINEStorePC/main.png;compress=true)
