### ISSUE TITLE
How to set image attributes.

### ISSUE THREAD

**Issue by kristvanbesien** [asciidoctor/asciidoctor-diagram#244]
I understand that asciidoctor-diagram basically passes the diagram source to an external processor, saves the resulting image and then inserts this in the document.

Is it possible to add image attributes (like size, postion etc...) to the diagram block?

It would be nice to have more control over image size and positioning. Most of my diagrams end up occupying a whole page.

**Comment by pepijnve** [comment]
That should already be possible. Any attribute you specify that is not consumed by the diagram processor itself should get passed on verbatim. In other words, you should be able to use any backend specific attribute you want to control the final size of the image.

**Comment by OlivierJourdan** [comment]
As far as I understand, we should be able to center a diagram.  I didn't find the syntax to this. 

Lest say we have the following diagram in an adoc file:

`[graphviz]
....
digraph G177458 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"DQMH module / Lvlib"[color=black shape=component]
"Vi"[color=skyblue shape=note]
}`

How do you center the resulting image ?
