### ISSUE TITLE
Have a way to embed SVG properly (to support interactivity) by default

### ISSUE THREAD

**Issue by manueljacob** [asciidoctor/asciidoctor-diagram#247]
This has been discussed in the past (#20, #64), but back then it wasn’t possible to instruct AsciiDoctor to embed the SVGs in a way that they can be used interactively.

This is possible since some time: https://asciidoctor.org/docs/user-manual/#taming-svgs

It’s a bit tedious to specify e.g. `opts=interactive` in every plantuml block. Therefore it would be nice to enable that by default.

**Comment by inponomarev** [comment]
I came here to write a new issue, but I see I'm not the only one facing this. 

I need documentation with [syntrax](https://kevinpt.github.io/syntrax/index.html) diagrams, but their hyperlinks are dead because of wrong embedding of svg pics. 

Our organization is using Ascciidoctor and Co. extensively, and we are ready to sponsor the work on a number of issues. Or, we are ready to hire a part-time Ruby developer, but in this case we will need a guidance for them from maintainers. But we cannot get in touch with anyone behind Asciidoctor. Please, hear us)

**Comment by mojavelinux** [comment]
> But we cannot get in touch with anyone behind Asciidoctor

You are getting in touch with Asciidoctor developers right now. This is literally how you do it.

> I need documentation with syntrax diagrams, but their hyperlinks are dead because of wrong embedding of svg pics.

Then set `opts=interactive` or `opts=inline` on the diagram block. Then you will get the result that you want.

**Comment by pepijnve** [comment]
@inponomarev as @mojavelinux said, you came to the right place.

It shouldn't be too hard to add a global and per-block option for this. Let me see what I can do.

**Comment by pepijnve** [comment]
@inponomarev with 2bf075f you can now add either `svg-type=...` per block or `diagram-svg-type` as a document attribute to control the SVG style. You can set the attribute to `static`, `interactive` or `inline`. This will result in `opts=...` being added to the generated image block as described at https://asciidoctor.org/docs/user-manual/#taming-svgs.
The `static` option is intended to allow you to specify exceptions per block if you set the document attribute to `inline` or `interactive`.
This change is applicable to any diagram generator that can produce SVG.

**Comment by mojavelinux** [comment]
@pepijnve I like your idea. I do believe it needs to come from the extension because context is important. I thought about having global enablement of the type for all images, but then static images would be affected and that's likely not the result we want. When Asciidoctor Diagram generates an SVG, it can then add the option given that it knows what it's making.

**Comment by bric3** [comment]
Hi I have trouble to make this work.

I'm running the following document trhough this configuration 

```bash
asciidoctor --trace --verbose \
  --base-dir=. \
  --backend=html5 \
  --require asciidoctor-diagram \
  --attribute=icons=font \
  --attribute sectlinks \
  --attribute sectanchors \
  --attribute diagram-svg-type=inline \
  plantuml.smoketest.adoc
```


```adoc
== Sequence diagram

[plantuml,"sequence-diagram-example",format="svg"]
.Sequence diagram
----
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections
----
```

I have tried setting `svg-type="inline"`  in the source listing _descriptor_. But the new options/attributes introduced in 2bf075fe07dde384326e47282970832b6f7aeb1d don't work, the svg is still declared as an `img`, only `opts="inline"` actually embed the SVG. 

I can see that the global attribute is correctly set using this :

```adoc
attribute `diagram-svg-type` : `{diagram-svg-type}`
```

Just in case here's what I've installed 

```
❯ gem query --local

*** LOCAL GEMS ***

asciidoctor (2.0.10)
asciidoctor-diagram (2.0.2)
asciidoctor-html5s (0.4.1)
bigdecimal (2.0.0, default: 1.4.1)
bundler (2.1.4, default: 1.17.2)
CFPropertyList (3.0.2, 2.3.6)
cmath (default: 1.0.0)
csv (3.1.2, default: 3.0.9)
date (3.0.0, default: 2.0.0)
dbm (1.1.0, default: 1.0.0)
did_you_mean (1.4.0, 1.3.0)
e2mmap (default: 0.1.0)
etc (1.1.0, default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (1.4.1, default: 1.1.0)
forwardable (1.3.1, default: 1.2.0)
hpricot (0.8.6)
io-console (0.5.6, 0.5.5, 0.5.4, default: 0.4.7)
ipaddr (default: 1.2.2)
irb (1.2.3, 1.2.1, default: 1.0.0)
json (2.3.0, default: 2.1.0)
libxml-ruby (3.1.0)
logger (1.4.2, default: 1.3.0)
matrix (default: 0.1.0)
mini_portile2 (2.5.0, 2.4.0)
minitest (5.14.0, 5.11.3)
mustache (1.1.1)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
nokogiri (1.10.9, 1.10.8, 1.10.7, 1.10.1)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.2.0, 1.1.7, 1.1.6, 1.1.5, 1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (13.0.1, 12.3.2)
rdiscount (2.2.0.1)
rdoc (6.2.1, default: 6.1.0)
reline (0.1.3, 0.1.2)
rexml (3.2.4, 3.2.3, default: 3.1.9)
ronn (0.7.3)
rss (0.2.9, 0.2.8, default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (0.8.0, default: 0.7)
sqlite3 (1.4.2, 1.3.13)
stringio (0.1.0, default: 0.0.2)
strscan (1.0.3, default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.3.5, 3.2.9)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (1.6.0, default: 1.4.2)
xmlrpc (0.3.0)
zlib (1.1.0, default: 1.0.0)
```

```
❯ java --version
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
```
