### ISSUE TITLE
Add puppeteerConfigFile Option

### ISSUE THREAD

**Issue by ldz-w** [asciidoctor/asciidoctor-diagram#250]
It appears that the asciidoctor-diagram options for [Mermaid](https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/mermaid/converter.rb) do not include the option `puppeteerConfigFile`, like the Mermaid CLI:

```
Usage: mmdc [options]

Options:
  -V, --version                                   output the version number
  <...>
  -p --puppeteerConfigFile [puppeteerConfigFile]  JSON configuration file for puppeteer. Optional
  -h, --help                                      output usage information
```

The config file is needed to fix a sandbox issue that occurs under certain circumstances, described [here](https://github.com/mermaidjs/mermaid.cli#linux-sandbox-issue).

Are there any plans to add this option?

**Comment by pepijnve** [comment]
I wasn't aware of that option (or the need for it). Thanks for letting me know.
Easy enough to add. PR welcome if you have the time.
