### ISSUE TITLE
Please update plantuml version for bugfix

### ISSUE THREAD

**Issue by RalfJahns** [asciidoctor/asciidoctor-diagram#260]
I have asciidoctor-diagram version 2.0.1, which includes the plantuml 1.2019.12 (at least that is the version in my ~/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-2.0.1/lib folder) from beginning of November last year.
Unfortunately there is a bug in this version, that breaks some of my sequence charts. The bug is already accepted and fixed by the project in the latest version of plantuml, see here:
https://forum.plantuml.net/10612/sequence-diagram-shortcut-deact-incoming-outgoing-messages?show=10612#q10612
This posting also includes a short example to reproduce the bug.

I don't know, for when you have scheduled your next update. Just wanted to raise this.

Best Regards
Ralf Jahns

**Comment by mojavelinux** [comment]
I can confirm that this can be fixed by grabbing the latest version of the plantuml distribution (ASL license) from https://plantuml.com/download#asl, extracting the jar, and putting it into the lib folder. All the existing tests pass, and the provided example works too.
