### ISSUE TITLE
'unterminated block' when diagram is put into a table cell

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-diagram#263]
Given `book.adoc`:

----
```asciidoc
= Inline diagrams
:doctype: book

|===
a|[ditaa]
....
+------------------+
|Me not works, halp|
+------------------+
....
|===

```
----

Attempt to convert produces a warning:
```
$ asciidoctor -r asciidoctor-diagram -D output book.adoc
asciidoctor: WARNING: book.adoc: line 6: unterminated ditaa block
```

Also, resulting table is corrupt:
![image](https://user-images.githubusercontent.com/92637/73440921-377d4000-4363-11ea-87b9-44775ef85f62.png)

However, same diagram works properly if put outside of table cell.

**Comment by mojavelinux** [comment]
You need to change the table cell separator if you're going to use the original on in the content of the cell. (The alternative is to escape it, but in this context that's much less convenient). See https://asciidoctor.org/docs/user-manual/#escaping-the-cell-separator. This is not a bug, it's a feature.

**Comment by slonopotamus** [comment]
Woah, cool.

**Comment by mojavelinux** [comment]
:+1:
