### ISSUE TITLE
Debugging on cygwin

### ISSUE THREAD

**Issue by gotnone** [asciidoctor/asciidoctor-diagram#264]
Hi,
I had been using asciidoctor-diagram as recently as three weeks ago on a Windows 7 + cygwin computer.  Yesterday, when I went to use it to update a document containing a ditaa diagram, it no longer worked.  Between the time when it was working and yesterday, I know that the base cygwin was updated and most likely the java runtime environment, too.

I know that there have been some changes with how asciidoctor-diagram communicates with the java job server backend for ditaa and plantuml.  I tried using a variety of older and newer versions of asciidoctor-diagram, but they all seem to fail at ./lib/asciidoctor-diagram/util/java.rb:17:in `write'.  I have also tried a couple of different jre and jdk versions, but they all fail similarly.

```
  11) Asciidoctor::Diagram::DitaaBlockMacroProcessor should generate PNG images when format is set to 'png'
      Failure/Error: io.write "POST #{req[:url]} HTTP/1.1"

      Errno::EPIPE:
        asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - Broken pipe
      # ./lib/asciidoctor-diagram/util/java.rb:17:in `write'
      # ./lib/asciidoctor-diagram/util/java.rb:17:in `format_request'
      # ./lib/asciidoctor-diagram/util/java_socket.rb:65:in `send_request'
      # ./lib/asciidoctor-diagram/ditaa/converter.rb:72:in `convert'
      # ./lib/asciidoctor-diagram/diagram_processor.rb:171:in `create_image_block'
      # ./lib/asciidoctor-diagram/diagram_processor.rb:87:in `process'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:645:in `[]'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:645:in `next_block'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:379:in `next_section'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:364:in `next_section'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb:97:in `parse'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:549:in `parse'
      # /usr/share/gems/gems/asciidoctor-2.0.10/lib/asciidoctor/load.rb:83:in `load'
      # ./spec/test_helper.rb:90:in `load_asciidoc'
      # ./spec/ditaa_spec.rb:28:in `block (2 levels) in <top (required)>'
      # ./spec/test_helper.rb:132:in `block (3 levels) in <top (required)>'
      # ./spec/test_helper.rb:131:in `chdir'
      # ./spec/test_helper.rb:131:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # Errno::EPIPE:
      #   Broken pipe
      #   ./lib/asciidoctor-diagram/util/java.rb:17:in `write'
```

I see a java process started in the task manager, but it seems like there is something wrong with the communication between the asciidoctor-diagram ditaa ruby code and the java server.  What steps can I take to debug this communication to see if some change in cygwin may be the cause of my problems.

So far I tried to run the server from the cygwin command line:

```
$ "C:/Program Files/AdoptOpenJDK/jdk-13.0.2.8-hotspot/bin/java.exe" "-Djava.awt.headless=true" "-Djava.net.useSystemProxies=true" "-cp" "C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\server-1.3.14.jar;C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\ditaa-1.3.14.jar;C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\ditaamini-0.12.jar;C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\plantuml-1.3.14.jar;C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\plantuml.jar;C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\jlatexmath-minimal-1.0.5.jar;C:\\cygwin64\\tmp\\asciidoctor-diagram\\lib\\batik-all-1.10.jar" "org.asciidoctor.diagram.StdInOutCommandServer"
```

This starts a java process and seems to sit empty.  I tried typing some HTTP commands to see if I could get a response, but I don't know what to type to check the correct operation.

```
POST \ditaa HTTP/1.1
Content-Length: 0
Content-Type: text/plain; charset=UTF_8
```

I would like to get this working with cygwin so that I can continue building my documentation with my usual build tools.  Thanks for your time.

**Comment by gotnone** [comment]
It appears that the problem I am encountering is related to upgrading cygwin.  I tried to downgrade the cygwin to v3.0.7-1.  This allows asciidoctor-diagram to work again.  When I stepped this forward to v3.1.1-1 the communication with the java server again failed as noted previously.

The actual changes that caused the problem were most likely introduced in v3.1.0-1, which was quickly replaced by v3.1.1-1 on the cygwin setup program.  Of particular interest, the changelog states that:

```
What's new:
-----------
...
- Support pseudo console in PTY. Pseudo console is a new feature
  in Windows 10 1809, which provides console APIs on virtual
  terminal. With this patch, native console applications can work
  in PTYs such as mintty, ssh, gnu screen or tmux.
...

What changed:
-------------

- FIFOs can now be opened multiple times for writing.
  Addresses: https://cygwin.com/ml/cygwin/2015-03/msg00047.html
             https://cygwin.com/ml/cygwin/2015-12/msg00311.html

...
```

It seems like the best course of action may be to bring this problem to the attention of the cygwin developers, but I still don't have a clear understanding of what is failing.  What is the best way to isolate a minimal test case?

**Comment by gotnone** [comment]
It looks like this may have been fixed in recent snapshots of cygwin

https://cygwin.com/ml/cygwin/2020-01/msg00322.html

**Comment by gotnone** [comment]
### Solution
Using version cygwin v3.0.7-1 or a snapshot or version **after** 2020-01-14 fixes the problem with pipes and non-cygwin processes.

### Bottom Line
Don't use cygwin v3.1.1-1 or v3.1.2-1 and expect pipes with non-cygwin processes to work correctly.  Asciidoctor-diagram components that rely on launching a separate process will hang with these versions of cygwin.

**Comment by pepijnve** [comment]
Thanks for investigating so thoroughly @gotnone. Happy to hear you've been able to resolve the problem.
