### ISSUE TITLE
Gnuplot on Windows: Failed to generate image: Invalid PNG signature

### ISSUE THREAD

**Issue by mojca** [asciidoctor/asciidoctor-diagram#267]
The default `gnuplot` terminal seems to be `png`, but it seems to be defunct on Windows.

Unless I explicitly change the image type to something different like `svg`, I cannot do anything  with the terminal at all.

It seems to help if I add `:binmode=>TRUE` to https://github.com/asciidoctor/asciidoctor-diagram/blob/5e7dcfb7e9251502b6499ccc8410de5b651e9dde/lib/asciidoctor-diagram/util/cli.rb#L64

except that this probably needs to be handled somewhere else, like for example in `generate_stdin_stdout` calling `generate`. I don't know whether always switching binary mode would have any side-effects for other terminals, else we want to explicitly enable binary output for `gnuplot`.

(Somehow it seems that it works on unix which is why this hasn't been noticed before.)

PS: Somewhat unrelated, but there is no reason why PDF output could not be supported as well.

**Comment by mojavelinux** [comment]
I agree that the binary flag should be set when working with input and output so it works on Windows. Linux seems to work either way since it doesn't mess with newlines, whereas Windows does. The binary flag turns off that implicit conversion.

**Comment by mojca** [comment]
Thank you.
