### ISSUE TITLE
After changing gnuplot image size, plots are not regenerated

### ISSUE THREAD

**Issue by mojca** [asciidoctor/asciidoctor-diagram#268]
If I change important parameters like
```adoc
:gnuplot-width: 420
:gnuplot-height: 200
```
the resulting graphics are not regenerated until I delete the images or the cache.

**Comment by pepijnve** [comment]
Only the diagram contents were taken into account when deciding to regenerate an image or not. Since asciidoctor-diagram v2.0.0 the common code that makes this decision has access to all the option values and with commit d4ac07f it should also detect changes to the options and regenerate the image.
