### ISSUE TITLE
umlet converter does not work properly

### ISSUE THREAD

**Issue by triaubaral** [asciidoctor/asciidoctor-diagram#271]
I am working with asciidoctor plugin from eclipse.
I set into my path the adress to umlet v14.3 tool (c:\tools\umlet\) where resides the umlet.jar executable file.
I tried to render an umlet diagram with the following syntax inside my asciidoc document : 

```
[umlet]
...

 <diagram program="umlet" version="14.3.0">
  <zoom_level>10</zoom_level>
  <element>
    <id>UMLUseCase</id>
    <coordinates>
      <x>60</x>
      <y>100</y>
      <w>120</w>
      <h>40</h>
    </coordinates>
    <panel_attributes>Use case 1</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLActor</id>
    <coordinates>
      <x>230</x>
      <y>80</y>
      <w>60</w>
      <h>110</h>
    </coordinates>
    <panel_attributes>Actor</panel_attributes>
    <additional_attributes/>
  </element>
</diagram>

...
```

I also tried the alternative syntax with file reference : 

`umlet::testfile.uxf[]`

Both syntaxes lead to the same unexpected result : it opens umlet app with an empty file instead of rendering the diagram inside my asciidoc document like plantuml converter.

**Comment by pepijnve** [comment]
UMLet 14.3 is now covered by the test suite on all platforms.
