### ISSUE TITLE
When/can/how github.com auto-render ditaa and plantuml from .adoc files?

### ISSUE THREAD

**Issue by johnnyutahh** [asciidoctor/asciidoctor-diagram#274]
When/can/how github.com auto-render `ditaa` and `plantuml` blocks when viewing (from github.com) .adoc files?

I suspect this is a FAQ, but I could not find a previous answer.

**Details**

I want github.com to render images in an .adoc like the following example but _without_ resorting to hard-coding the image references (as in `image::sample-ditaa-diagram.png[]`).

https://github.com/asciidoctor/asciidoctor.org/blob/master/news/plain-text-diagrams-in-asciidoctor.adoc

**Comment by pepijnve** [comment]
@johnnyutahh that's a feature request for GitHub itself, which I don't have any control over whatsoever. There's nothing inherently preventing GitHub from doing this.

**Comment by johnnyutahh** [comment]
> @johnnyutahh that's a feature request for GitHub itself, which I don't have any control over whatsoever. There's nothing inherently preventing GitHub from doing this. You could try contacting GitHub support with this question.

Yes, of course, I'm aware of that. What I'm therefore effectively asking: is there some way (some configuration, tweak, etc that y'all know that I do not) to get github.com to do it?  And if it does not work, it'd be interesting to see what if anything y'all have tried to 1) "tweak" it work or 2) ask github.com to do something about it. (They already do .adoc renderings... so there was some sort of asciidoc/asciidoctor integration done somewhere along the way, and do we know which personnel made that happen on the github side?)

I'm assuming by your above reply the answer is "we (asciidoctor) know of no way to make that work, and we're respectfully not interested in and/or we do not have resources to expend for additional effort to make it work or investigate with our github contacts to make it work." Which all makes perfect sense. Knowing whatever the background is will help me to determine next steps.

(And/or: y'all are trying to keep your open-issue queues as small as possible. Which is also understandable.)

Eventually, github.com should be interested in this. It seems bloody damn valuable to have text-based-source graphics capability in their view renderings. If we could reach the right person (possibly product-manager and/or VP-ish kind of level) at github who's thinking and/or care about this kind of feature (especially it means something more to their financial bottom line), we might be able to help motivate them make it happen.

"By default," per my initial testing, it does not work.

**Comment by pepijnve** [comment]
It's more a matter of having no contacts at GitHub to request this and having no influence whatsoever over what the GitHub team does. I have no idea how the GitHub code uses asciidoctor or asciidoctor-diagram exactly. I can't give you any advice here. Maybe (really big maybe) @mojavelinux can tell you a bit more.

If you're trying to ge in touch with GitHub product management, then this project's issue tracker is simply the wrong place for that. I do not work for GitHub and do not have any points of contact there. I doubt anyone from the GitHub development team monitors this project.

**Comment by mojavelinux** [comment]
I have contacts at GitHub, but that's not how GitHub works. No matter who you know, GitHub requires that you communicate via support. If enough requests are made through that channel, they may (or may not) decide to implement a feature. I don't see that changing.

You're free to make the case and perhaps it will make a difference. We will most certainly lend our voices in support.

> It seems bloody damn valuable to have text-based-source graphics capability in their view renderings.

We wholeheartedly agree.

On another note, we have had success getting these types of changes on GitLab. Very recently, support was added for both font-based icons and PlantUML diagrams.

**Comment by johnnyutahh** [comment]
Very helpful feedback, thanks very much @pepijnve and @mojavelinux for the feedback.

> On another note, we have had success getting these types of changes on GitLab. Very recently, support was added for both font-based icons and PlantUML diagrams.

That's super good to know. I plan to look into that.

Thanks again.

**Comment by johnnyutahh** [comment]
> On another note, we have had success getting these types of changes on GitLab. Very recently, support was added for both font-based icons and PlantUML diagrams.

@mojavelinux - I tried the PlantUML render on GitLab with no success. Any thoughts?

https://gitlab.com/johnnyutahh/software-systems-docs/-/blob/master/z-sandbox/diagram-test.adoc

**Comment by mojavelinux** [comment]
I could be wrong, but I think it has to be a listing block (though it should be supporting the literal block). See https://docs.gitlab.com/ee/administration/integration/plantuml.html#creating-diagrams

**Comment by johnnyutahh** [comment]
Right. Changing plantuml list block delimiters from `....` to `----` solves the GitLab problem.

https://gitlab.com/johnnyutahh/software-systems-docs/-/blob/master/z-sandbox/diagram-test.adoc

Thanks Dan for your help on this, really appreciated.
