### ISSUE TITLE
Wrong Mermaid link in README

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-diagram#286]
Readme points to :point_right: https://github.com/mermaid-js/mermaid.cli, but the real link is (I assume) :point_right:  https://github.com/mermaidjs/mermaid.cli.

**Comment by pepijnve** [comment]
Seems like the current source is actually https://github.com/mermaid-js/mermaid-cli. I'll fix the URL right away.

**Comment by abelsalgadoromeroWD** [comment]
Are there two project? :exploding_head:

**Comment by pepijnve** [comment]
No idea what happened there but the `mermaidjs/mermaid.cli` states this in the README. My hunch would be open source politics at work.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/225326/91160275-7b51e100-e6c9-11ea-84ab-cb2a2ac04e0e.png">
