### ISSUE TITLE
Support for C4 model

### ISSUE THREAD

**Issue by ilvetz** [asciidoctor/asciidoctor-diagram#288]
Please consider support for [C4 model](https://c4model.com/).
Thank you.

**Comment by Riduidel** [comment]
It is already possible to generate C4 diagrams using asciidoctor-diagram.
For that, I use plantuml C4 pencils (https://github.com/RicardoNiepel/C4-PlantUML).
You can take a look at https://riduidel.github.io/agile-architecture-documentation-system/ as an example of what is easily doable

**Comment by pepijnve** [comment]
I'm going to close this issue since the requested functionality is apparently already supported. Feel free to reopen if something isn't working correctly related to C4.
