### ISSUE TITLE
Does not work with asciidoctor-pdf

### ISSUE THREAD

**Issue by rongcuid** [asciidoctor/asciidoctor-diagram#289]
I tried to generate a PDF using `asciidoctor-pdf -r asciidoctor-diagram`, but got some problems:

```
$ ruby /tmp/test.rb README.adoc 
Traceback (most recent call last):
	3: from /tmp/test.rb:5:in `<main>'
	2: from /usr/lib/ruby/vendor_ruby/polyglot.rb:65:in `require'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- asciidoctor-diagram (LoadError)
	17: from /tmp/test.rb:5:in `<main>'
	16: from /usr/lib/ruby/vendor_ruby/polyglot.rb:65:in `require'
	15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	12: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram.rb:1:in `<top (required)>'
	11: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram.rb:1:in `require_relative'
	10: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/a2s.rb:2:in `<top (required)>'
	 9: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/a2s.rb:2:in `require_relative'
	 8: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/a2s/extension.rb:1:in `<top (required)>'
	 7: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/a2s/extension.rb:1:in `require_relative'
	 6: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/a2s/converter.rb:2:in `<top (required)>'
	 5: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/a2s/converter.rb:2:in `require_relative'
	 4: from /var/lib/gems/2.7.0/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/util/cli_generator.rb:1:in `<top (required)>'
	 3: from /usr/lib/ruby/vendor_ruby/polyglot.rb:65:in `require'
	 2: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/tempfile.rb:121:in `<top (required)>': superclass mismatch for class Tempfile (TypeError)
```

Now, this happens if asciidoctor-pdf is loaded before asciidoctor-diagram.
However, if I reverse their order, no diagrams are generated, and diagram turn into code blocks.

I tried #29's tests, and I got exact same thing if I use a script to invoke.
I can generate HTML correctly with diagrams.

Here's my Gem list:

```
$ gem list  | grep asciidoctor
asciidoctor (2.0.10)
asciidoctor-diagram (2.0.2)
asciidoctor-pdf (1.5.0.alpha.17.dev)
```

**Comment by mojavelinux** [comment]
The problem you're facing is that the version of Asciidoctor PDF you're using is substantially out of date and no longer supported. The current release is Asciidoctor PDF 1.5.3. The Tempfile class is no longer patched by Asciidoctor PDF, which will resolve the issue you're observing. Please upgrade and retest.

In your follow-up, please state how you are invoking (and thus loading) Asciidoctor PDF.

**Comment by rongcuid** [comment]
Hmmm, I recognize this is the exact version on the `asciidoctor-diagram` documentation, and is the one coming with Ubuntu. I assumed it would work, but I will try to upgrade it.

**Comment by rongcuid** [comment]
I confirm the `1.5.3` version of asciidoctor-pdf works with `$ asciidoctor-pdf -r asciidoctor-diagram README.adoc`.
I still suggest updating the documentation to reflect this, though it is the asciidoctor-pdf doc:
https://asciidoctor.org/docs/asciidoctor-pdf/.

Not sure if you actually have permission to do so.

**Comment by pepijnve** [comment]
@mojavelinux https://github.com/asciidoctor/asciidoctor.org/pull/970 should fix that. The documentation page is still referencing the older prerelease version of the readme instead of the current release.

**Comment by mojavelinux** [comment]
Thanks for testing and confirming, @rongcuid.

@pepijnve Thanks for pointing that out! I didn't realize it had fallen behind.

**Comment by pepijnve** [comment]
I'm closing this issue since the original problem was resolved by upgrading to a more recent version of asciidoctor-pdf.
