### ISSUE TITLE
Error in including plantuml files that has !include statements

### ISSUE THREAD

**Issue by carun** [asciidoctor/asciidoctor-diagram#291]
## Something.adoc

```
== Introduction

This is an asciidoc document.

[plantuml, Text, png]
----
include::file1.puml[]
----
```

## file1.puml
```
@startuml Sequence
title Example
!include internal-header.iuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
```

## header.iuml
```
autonumber "<font color=teal><b> 00."
skinparam defaultFontName Segoe UI
skinparam roundcorner 10
skinparam sequenceLifeLineBackgroundColor pink
skinparam sequenceMessageAlign center
```

## Expected Output
HTML file with correct sequence diagram.

## Actual Output

![image](https://user-images.githubusercontent.com/471374/93658945-08e8ce00-f9f5-11ea-9ef4-bb8d555bd4d3.png)

**Comment by pepijnve** [comment]
Could you describe a bit what your directory layout looks like and with which command line invocation you're running asciidoctor?

**Comment by carun** [comment]
Here is a repo to reproduce https://github.com/carun/asciidoctor-diagram-issue-291.

**Comment by carun** [comment]
```
2020-09-21 09:53:01 /var/tmp/asciidoctor-diagram-issue-291 (master)
$ asciidoctor -b html5 Something.adoc -r asciidoctor-diagram
asciidoctor: FAILED: 'asciidoctor-diagram' could not be loaded
  Use --trace for backtrace
2020-09-21 09:54:49 /var/tmp/asciidoctor-diagram-issue-291 (master)
$ gem search asciidoctor-diagram

*** REMOTE GEMS ***

asciidoctor-diagram (2.0.3, 1.2.1 java)
asciidoctor-diagram-cacoo (0.2.2)
asciidoctor-diagram-eralchemy (0.1.0)
asciidoctor-diagram-office (0.1.2)
asciidoctor-diagram-stupid (0.1.0)
2020-09-21 09:55:17 /var/tmp/asciidoctor-diagram-issue-291 (master)
$ sudo gem install asciidoctor-diagram
Fetching asciidoctor-diagram-2.0.3.gem
Successfully installed asciidoctor-diagram-2.0.3
Parsing documentation for asciidoctor-diagram-2.0.3
Installing ri documentation for asciidoctor-diagram-2.0.3
Done installing documentation for asciidoctor-diagram after 0 seconds
1 gem installed
2020-09-21 09:55:28 /var/tmp/asciidoctor-diagram-issue-291 (master)
$ asciidoctor -b html5 Something.adoc -r asciidoctor-diagram
2020-09-21 09:55:41 /var/tmp/asciidoctor-diagram-issue-291 (master)
$
```

**Comment by carun** [comment]
I just validated the generated HTML and it seems to be fine.

![image](https://user-images.githubusercontent.com/471374/93808819-5d609900-fc01-11ea-8fd4-107083bdcd7d.png)

This is reproducible with AsciidocFX 1.7.3 (latest on GitHub).

![image](https://user-images.githubusercontent.com/471374/93809013-97319f80-fc01-11ea-9a7d-16009b8c8337.png)

**Comment by pepijnve** [comment]
Could you give the block macro notation a try instead? That's `plantuml::file1.puml[png]`. If you use an asciidoc `include::` macro the diagram extension doesn't really know where your source file is located in the filesystem which can cause resolving of relative paths to fail.

**Comment by carun** [comment]
This work fine when run from command line, but not just with asciidocfx. So I don't think it is related to `include::` macro.

**Comment by carun** [comment]
with `plantuml::file1.puml[png]`

![image](https://user-images.githubusercontent.com/471374/93812329-47a1a280-fc06-11ea-9779-449a22aa0e7a.png)

**Comment by pepijnve** [comment]
Sorry, that's the wrong syntax. You want to replace

```
[plantuml, png]
----
include::file1.puml
----
```

with

```
plantuml::file1.puml[png]
```

**Comment by pepijnve** [comment]
On closer inspection, I don't think AsciidocFX even uses `asciidoctor-diagram` for PlantUML integration at all. I can't find any trace of it being referenced in the AsciidocFX repository. The only PlantUML code I found is https://github.com/asciidocfx/AsciidocFX/blob/master/src/main/java/com/kodedu/service/extension/PlantUmlService.java which is not related to this project.

**Comment by carun** [comment]
Ugh! I see. Thanks. I will raise this up with AsciidocFX team.

**Comment by pepijnve** [comment]
FWIW, if you would like to use asciidoctor-diagram in an interactive editor with live preview, I can recommend [IntelliJ IDEA Community Edition](https://www.jetbrains.com/idea/) with the [Asciidoc plugin](https://plugins.jetbrains.com/plugin/7391-asciidoc).

**Comment by pepijnve** [comment]
Closing this issue for now since it's related to a different project.
