### ISSUE TITLE
Re-render of svgbob sets width=0

### ISSUE THREAD

**Issue by michaelrommel** [asciidoctor/asciidoctor-diagram#292]
When rendering an HTML document where an ascii box drawing is included, svgbob renders the output svg file and the HTML page includes a proper tag with width and height:

`<img src="test.svg" alt="test" width="480" height="256">`

If I render the same file again without changing the ascii block, the svg file is not changed and the resulting html file contains:

`<img src="test.svg" alt="test" width="0" height="0">`

I did look into the source code, but unfortunately I was unable to locate, where the width and height are written and why they were not appropriately detected from the svg file like on the first run. I am sorry to not being able to include further helpful information. I don't even know, whether the culprit is in asciidoctor or in asciidoctor-diagram... :-(

**Comment by pepijnve** [comment]
@michaelrommel with which version of `asciidoctor-diagram` is this? I made som changes in that area for 2.0.3 so I'm thinking I might have introduced a regression 😬

**Comment by pepijnve** [comment]
I was able to reproduce this and it's indeed a regression in 2.0.3. I'll get this fixed asap.

**Comment by pepijnve** [comment]
@michaelrommel I've pulled 2.0.3 from rubygems.org because of this. So sorry for the inconvenience. In the meantime I suggest you roll back to 2.0.2.

**Comment by michaelrommel** [comment]
Thank you so much for looking into this - I was really lost in the code, as I am not familiar with ruby and their code structuring at all. Since I am just starting out with asciidoctor, I really can wait for the next release - it is not a big hassle to just delete the directory with rendered images when I re-create a new HTML version.
I am just happy to have helped at all...
