### ISSUE TITLE
Macro syntax expects "format" to be specified for generated-file-extension

### ISSUE THREAD

**Issue by gdurandrexel** [asciidoctor/asciidoctor-diagram#294]
When using the syntax `plantuml::diagram.puml[svg]` or `plantuml::diagram.puml["svg"]`, png is generated. I have to use `plantuml::diagram.puml[format=svg]` for svg to be generated.

I ended up using the attribute `:plantuml-format: svg` which works but is not documented.

Using the gradle plugin org.asciidoctor.jvm.pdf 3.1.0

**Comment by pepijnve** [comment]
Thanks for the feedback @gdurandrexel. This one has been lurking in the codebase for a long time. The first unnamed parameter was being interpreted as `target="..."` instead of as `format="..."`. This will be fixed in the next patch release.
