### ISSUE TITLE
Installation error: "invalid gem: package is corrupt, exception while verifying: undefined method `path' for "data.tar.gz":String (NoMethodError)"

### ISSUE THREAD

**Issue by mwnaumann** [asciidoctor/asciidoctor-diagram#303]
Installing asciidoctor works flawlessly.  I've tested other gem packages and they also install correctly.  Here is an example:

[504]$ sudo gem install asciidoctor
Successfully installed asciidoctor-2.0.10
Parsing documentation for asciidoctor-2.0.10
Done installing documentation for asciidoctor after 2 seconds
1 gem installed

But, whenever I try to install asciidoctor-diagram, I am getting this error:

[505]$ sudo gem install asciidoctor-diagram
ERROR:  Error installing asciidoctor-diagram:
        invalid gem: package is corrupt, exception while verifying: undefined method `path' for "data.tar.gz":String (NoMethodError) in /var/lib/gems/2.5.0/cache/asciidoctor-diagram-2.0.5.gem

I deleted /var/lib/gems/2.5.0/cache/asciidoctor-diagram-2.0.5.gem and re-ran the installation.  That did not fix the problem.
I deleted all *.gem files in /var/lib/gems/2.5.0/cache and re-ran the installation.  That did not fix the problem.

**Comment by mojavelinux** [comment]
I tried it and it installs without an issue. It must be pulling the corrupt gem file from somewhere else on your system. Can you try it on a different computer?

**Comment by mwnaumann** [comment]
Thank you for checking.  
I tried on a different virtual machine and (unfortunately for me) it works. :(

**Comment by mwnaumann** [comment]
Is there a way for me to (somehow) download the gem file to my local machine, and then point 'gem install' to that local file?

**Comment by mojavelinux** [comment]
You can find the download link on the package on rubygems.org. See https://rubygems.org/gems/asciidoctor-diagram/versions/2.0.5

**Comment by mojavelinux** [comment]
I also noticed that you're installing the gem into the root of your system. I strongly recommend against doing this. You should let the package manager manage gems installed in the system. For your own gems, you should use RVM (or some other version manager) so that they are installed in your home directory. Better yet, install them directly into the project using Bundler + Gemfile.
