### ISSUE TITLE
First successful run logs to stderr

### ISSUE THREAD

**Issue by 1marc1** [asciidoctor/asciidoctor-diagram#309]
Hi Team,

I am very new to asciidoctor-diagram, but I noticed that upon first run it logs to stderr, despite everything being fine: the resulting PDF file shows the graph how it was intended. Please review the following output. Is there a way to suppress this initial output? I am looking to integrate the use of asciidoctor-diagram into a workflow that alerts when something is sent to stderr. Obviously, when everything worked fine, there should be no need to send anything to stderr.

Thank you.

Marc.

```
marc@ag-ubuntu:/tmp/1marc1$ ll
total 20
drwxrwxr-x  2 marc marc  4096 Nov 27 18:51 ./
drwxrwxrwt 21 root root 12288 Nov 27 18:51 ../
-rw-rw-r--  1 marc marc   299 Nov 27 18:41 test.adoc
marc@ag-ubuntu:/tmp/1marc1$ cat test.adoc 
== Graph

[graphviz,test,png]
....
digraph G {
      a -> b -> c;
      b -> d;
      a [shape=polygon,sides=5,peripheries=3,color=lightblue,style=filled];
      c [shape=polygon,sides=4,skew=.4,label="hello world"]
      d [shape=invtriangle];
      e [shape=polygon,sides=4,distortion=.7];
}
....
marc@ag-ubuntu:/tmp/1marc1$ asciidoctor-pdf -r asciidoctor-diagram -o test.pdf test.adoc --trace -v 2>stderr
marc@ag-ubuntu:/tmp/1marc1$ cat stderr
asciidoctor: DEBUG: Finding 'dot' in attributes
asciidoctor: DEBUG: Finding 'dot' in environment
asciidoctor: DEBUG: Found '/usr/local/bin/dot' in environment
asciidoctor: DEBUG: Executing ["/usr/local/bin/dot", "-o/tmp/dot20201127-5205-186lu5h.png", "-Tpng"] with options {:stdin_data=>"digraph G {\n      a -> b -> c;\n      b -> d;\n      a [shape=polygon,sides=5,peripheries=3,color=lightblue,style=filled];\n      c [shape=polygon,sides=4,skew=.4,label=\"hello world\"]\n      d [shape=invtriangle];\n      e [shape=polygon,sides=4,distortion=.7];\n}"}
marc@ag-ubuntu:/tmp/1marc1$ asciidoctor-pdf -r asciidoctor-diagram -o test.pdf test.adoc --trace -v 2>stderr
marc@ag-ubuntu:/tmp/1marc1$ cat stderr
marc@ag-ubuntu:/tmp/1marc1$ 
```

**Comment by pepijnve** [comment]
By running with `-v` you're turning on debug logging. `asciidoctor-diagram` uses `asciidoctor`s logging mechanism and that ends up printing to stderr. I'm planning on changing any of that. If you do not want verbose output, don't request verbose output.

**Comment by mojavelinux** [comment]
@pepijnve is correct, the `-v` option is linked to enabling the debug level on the logger. This is documented behavior. See https://asciidoctor.org/docs/user-manual/#processing-information. The logger always writes to stderr by default. (If you want to redirect those messages, it's possible to plug in your own logger.)

We're considering an enhancement to the CLI that allows the log level to be controlled independently, which you may be interested in. I just filed an issue for it. See https://github.com/asciidoctor/asciidoctor/issues/3868

**Comment by 1marc1** [comment]
@pepijnve and @mojavelinux Thank you both for clarifying how it works. I have been using the `-v` flag in asciidoctor and asciidoctor-pdf and when output is generated without any issues, then nothing is logged to stderr. I thought it would be the same when enabling asciidoctor-diagram.
