### ISSUE TITLE
Upgrade PlantUML version

### ISSUE THREAD

**Issue by Z01ndels** [asciidoctor/asciidoctor-diagram#312]
asciidoctor-diagram seems to use PlantUML version 1.2020.6. We're currently at 1.2020.21.
Can you upgrade your dependency ? The 1.2020.6 version seems to trigger some bugs (see https://github.com/Riduidel/agile-architecture-documentation-system/issues/68)

**Comment by mojavelinux** [comment]
It's a licensing issue.

@pepijnve It might be a good idea to add a disclaimer to the README to avoid having to answer this question periodically.

**Comment by habamax** [comment]
And it also has json rendering too I am eager to try out: https://twitter.com/PlantUML/status/1333527507677704198

**Comment by habamax** [comment]
Actually I was thinking I could use non-builtin plantuml, but it looks like there is no info in the doc how can I specify it

**Comment by pepijnve** [comment]
@mojavelinux upgrading isn't really a licensing issue, I'm just a bit overloaded with other work at the moment. Longer term I've been thinking of stripping the embedded PlantUML jar out of the gem. You would then have to point to it using an environment variable instead.
That would be a pretty big breaking change though for most people, so short term I think I'll upgrade the embedded version along with that env var change. That will get most users on the most recent version of PlantUML and also enable what @habamax is asking for.

**Comment by mojavelinux** [comment]
Thanks for clarifying, @pepijnve!

**Comment by pepijnve** [comment]
asciidoctor-diagram 2.1.0 updates PlantUML to v1.2021.0. Additionally you can now tell the extension to use a specific PlantUML jar file using the  a different version of plantuml via the `DIAGRAM_PLANTUML_CLASSPATH` environment variable.

**Comment by habamax** [comment]
Thank you, @pepijnve !
