### ISSUE TITLE
asciidoctor-diagram load error

### ISSUE THREAD

**Issue by SimonRekers** [asciidoctor/asciidoctor-diagram#316]
Hello there,

I am getting the following error, when I am trying to use asciidoctor-diagram:

**I am executing the following:**
`asciidoctor "-r asciidoctor-diagram" --trace "-o document.html" .\src\document.adoc`

**And I am getting the following output:** 

```
Traceback (most recent call last):
        10: from C:/Ruby27-x64/bin/asciidoctor:23:in `<main>'
         9: from C:/Ruby27-x64/bin/asciidoctor:23:in `load'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/bin/asciidoctor:13:in `<top (required)>'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/bin/asciidoctor:13:in `new'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:24:in `initialize'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/options.rb:34:in `parse!'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/options.rb:274:in `parse!'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/options.rb:274:in `each'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/options.rb:276:in `block in parse!'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file --  asciidoctor-diagram (LoadError)
```

The terminal process "C:\windows\system32\cmd.exe /d /c asciidoctor "-r asciidoctor-diagram" --trace "-o document.html" .\src\document.adoc" terminated with exit code: 1.

**Reference Info**
`asciidoctor -version`
Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:UTF-8 ex:UTF-8)

`gem install asciidoctor-diagram`
Fetching asciidoctor-diagram-2.0.5.gem
Successfully installed asciidoctor-diagram-2.0.5
Parsing documentation for asciidoctor-diagram-2.0.5
Installing ri documentation for asciidoctor-diagram-2.0.5
Done installing documentation for asciidoctor-diagram after 2 seconds
1 gem installed

Any help is largely appreciated!

**Comment by pepijnve** [comment]
No idea why you would be getting this error I'm afraid. You could check under `C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/` to see if the diagram gem was actually installed correctly. Are you using Bundler?
