### ISSUE TITLE
Github actions Windows CI migration

### ISSUE THREAD

**Issue by snecklifter** [asciidoctor/asciidoctor-diagram#317]
Raising this to track migration from appveyor/travis to Github Actions for Windows (Linux is working).
Have made some progress on the Windows branch and the test suite now runs to completion.

@pepijnve there are 20-odd errors remaining which will probably make more sense to you than me?

https://github.com/asciidoctor/asciidoctor-diagram/runs/1657558579?check_suite_focus=true

**Comment by pepijnve** [comment]
It took me a while but I finally figured out what was going on. The gem communicates with the Java subprocess via stdin/stdout:
- The encoding for these streams was not being set; that's now set to be UTF-8.
- Both Ditaa and PlantUML are kind of sloppy when it comes to output. Some codepaths in Ditaa were writing directly to stdout and that was getting interleaved in with the response data. As a quick fix I'm redirecting regular stdout to stderr.

With those two fixes the Windows builds are working and AppVeyor is out of the picture.

**Comment by snecklifter** [comment]
Excellent news, thanks for the explanation.
