### ISSUE TITLE
Kroki Server returns 414 Request-URI Too Long

### ISSUE THREAD

**Issue by achimgrimm** [asciidoctor/asciidoctor-diagram#345]
Once a diagram gets bigger (very common for some diagram types like BPMN), the request to the kroki server will result in a very large URI if HTTP GET is used.

This will result in the error message `Failed to generate image: 414 "Request-URI Too Long"`

Increasing the max URI length limit on the kroki server is a not an option, as this will also not work with larger diagrams (i.e. normal sized BPMN).

Kroki server allows to use HTTP POST instead. 
see https://kroki.io/#how

**Comment by pepijnve** [comment]
I hadn't implemented automatic switching to POST yet indeed. Shouldn't be too hard to implement.
