### ISSUE TITLE
Add documentation for diagram server configuration

### ISSUE THREAD

**Issue by achimgrimm** [asciidoctor/asciidoctor-diagram#346]
The documentation Diagramm attributes documentation (https://docs.asciidoctor.org/diagram-extension/latest/#diagram-attributes) is missing the `diagram-server-url` and `diagram-server-type` parameters.

These attributes should be added, as they are only visible in the `mermaid_spec.rb`.

**Comment by achimgrimm** [comment]
Please see my pull request https://github.com/asciidoctor/asciidoctor-diagram/pull/347

**Comment by pepijnve** [comment]
Thank you for the contribution. Reviewed and merged.
