### ISSUE TITLE
`style` attribute is ignored for syntrax diagrams

### ISSUE THREAD

**Issue by inponomarev** [asciidoctor/asciidoctor-diagram#348]
I can set the custom style file for all the syntrax diagrams in the document by setting `:syntrax-style: `, and it works!

However, if I want to set an individual style file for a single syntrax diagram using 

```asciidoc
[syntrax,example,svg, style="mystyle.ini"]
....
line('a', 'b', 'c') 
....
```

the style is simply ignored, no matter if `:syntrax-style: ` style is set for the document or not (other attributes such as `scale` and `heading` are respected), contrary to what is said in [documentation](https://asciidoctor.org/docs/asciidoctor-diagram/#syntrax).

**Comment by pepijnve** [comment]
Turns out 'style' is a reserved attribute and it simply doesn't get passed down to the extension. I'll rename this to style-file.
