### ISSUE TITLE
Feature request: PlantUML `?=` syntax support

### ISSUE THREAD

**Issue by HeinrichAD** [asciidoctor/asciidoctor-diagram#353]
PlantUML supports to assign a value to a variable, only if it is not already defined, with the syntax `!$a ?= "foo"`.

`!$a ?= "foo"` could be considered the short form of the following:
```plantuml
!if %not(%variable_exists("$a"))
  !$a = "foo"
!endif
```
Since there is a workaround, this is prio low, but once you start working with a lot of customizable parameters, it's pretty annoying and the code gets messy quickly.

## References

Documentation: https://plantuml.com/preprocessing#788fa5fb2276ed17

Example below in action: [PlantUML Online Example](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBCoKnELT2rKt3AJrAmKZ3KKz3IKibBp4tLqb8epiWlpKbHI4fLICqjAAdaub84ooZOsoeeEMSa5kLafYgX6s24tG2eShWHG1DS4iioKp3q6sFN3rQCuW3Naep4F0pj9lYqEwJcfO3y3000)

## Example

```plantuml
= Test

[plantuml]
----
@startuml
Alice -> Bob : 1. **$name** should be empty

!$name ?= "Charlie"
Alice -> Bob : 2. **$name** should be Charlie

!$name = "David"
Alice -> Bob : 3. **$name** should be David

!$name ?= "Ethan"
Alice -> Bob : 4. **$name** should be David
@enduml
----
```

## Expected
![image](https://user-images.githubusercontent.com/5962361/117550113-ba00af00-b03e-11eb-8ba3-4e9dddcdf8eb.png)

## Actual
Syntax Error

<details>

```
> asciidoctor -r asciidoctor-diagram --failure-level ERROR -b xhtml5 -a data-uri -D generated test.adoc
asciidoctor: ERROR: test.adoc: line 5: Failed to generate image: PlantUML preprocessing failed: [From <input> (line 4) ]                   
                                           
@startuml                                  
Alice -> Bob : 1. **$name** should be empty
                                           
!$name ?= "Charlie"                        
^^^^^                                      
 Syntax Error?                             

asciidoctor: FAILED: /documents/test.adoc: Failed to load AsciiDoc document - PlantUML preprocessing failed: [From <input> (line 4) ]                   
                                           
@startuml                                  
Alice -> Bob : 1. **$name** should be empty
                                           
!$name ?= "Charlie"                        
^^^^^                                      
 Syntax Error?                             
 (RuntimeError)
  Use --trace for backtrace
```

</details>

**Comment by pepijnve** [comment]
This seems to have been added in a recent version of PlantUML. The currently bundled version is 1.2021.2. I've updated the gem containing the PlantUML jar to 1.2021.5. Could you update the gem on your end and retest?

**Comment by HeinrichAD** [comment]
Thank you. I confirm the functionality. It's working without issues.

<details>
<summary>Example of above with <code>asciidoctor-diagram</code>.</summary>

![image](https://user-images.githubusercontent.com/5962361/117679934-ff44ee00-b1b0-11eb-861e-f2fc6e84fed0.png)

</details>
