### ISSUE TITLE
Add contributors guide how to run a single test

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#359]
When preparing PR #358, I struggled with running a single test of the big test suite locally. 

This is probably due to me being a Ruby newbie. I tried to [apply some things about running a single test from the Asciidoctor contributor's guide](https://github.com/asciidoctor/asciidoctor/blob/master/CONTRIBUTING.adoc#writing-and-executing-tests), but did work out. As a last resort I delete the tests I didn't want to run locally, and reverted that change before pushing the change.

I'd love to see a chapter in this project's contributors guide for this project about how to run a single test.

**Comment by pepijnve** [comment]
I usually do this from my IDE (RubyMine). From a shell it's a standard RSpec invocation. See below for instance:

```
pepijn@Cerris asciidoctor-diagram % bundle exec rspec spec/plantuml_spec.rb -e "plantuml should generate image blocks when format is set to 'png'"
Run options:
  include {:full_description=>/plantuml\ should\ generate\ image\ blocks\ when\ format\ is\ set\ to\ 'png'/}
  exclude {:broken_on_osx=>true}

Asciidoctor::Diagram::PlantUmlBlockMacroProcessor
  plantuml should generate image blocks when format is set to 'png'

Asciidoctor::Diagram::PlantUmlBlockProcessor
  plantuml should generate image blocks when format is set to 'png'

Finished in 1.64 seconds (files took 0.27539 seconds to load)
2 examples, 0 failures
```

**Comment by pepijnve** [comment]
See https://relishapp.com/rspec/rspec-core/v/3-10/docs/command-line/example-option for more detailed information.

**Comment by ahus1** [comment]
Thanks, I'll use the suggested scripts and links next time.
