### ISSUE TITLE
C4-PlantUML prefers PlantUML 1.2021.6 or higher.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-diagram#360]
Asciidoctor-diagram 2.1.2 uses PlantUML 1.2021.2.  With a version of PlantUML of 1.2021.5 or less, it produces the following log message when processing a C4-PlantUML diagram:

````
[Log] "dynamic undefined legend colors" requires PlantUML version >= 1.2021.6, therefore only static assigned colors are used
````

When is Asciidoctor-diagram 2.1.3 planned to be released? (since it will be released with at least PlantUML 1.2021.8 or higher).

**Comment by pepijnve** [comment]
Starting with asciidoctor-diagram 2.1 PlantUML is no longer bundled inside the main gem directly. This was done to avoid having to make nee releases every time a new PlantUML release becomes available. You should be able to pull in the latest version of https://rubygems.org/gems/asciidoctor-diagram-plantuml
That's currently at 1.2012.8.

**Comment by wfouche** [comment]
Thanks.
