### ISSUE TITLE
last diagram of each type populating across document

### ISSUE THREAD

**Issue by elisa-riscv** [asciidoctor/asciidoctor-diagram#365]
I am working on a fully featured pdf document that has numerous Wavedrom and Graphviz diagrams. We are making use of customization in addition to asciidoctor-mathematical, asciidoctor-bibtex, and of course asciidoctor-diagram. My problem is that for both Wavedrom and Graphiviz diagrams, the last diagram in the text is populated backwards to with the result that the same graphical output appears for all spots where Wavedrom diagrams should appear, and likewise the same graphical output appears for all spot where Graphviz diagrams should appear. Following is a screen shot that shows what should be completely different diagrams. The second diagram in this screen shot is from an svg that I generated *before* the build for comparison:
<img width="840" alt="Screen Shot 2021-08-12 at 8 15 51 AM" src="https://user-images.githubusercontent.com/78001874/129225447-4c61badc-3f88-4702-aa5d-725bd96c0493.png">

**Comment by pepijnve** [comment]
I'll need some more information to go on than what you've provided so far. It sounds like the targets of your diagrams are all the same causing the files to get overwritten. I might be able to tell you more if you provide some snippets of your asciidoc source document.

**Comment by elisa-riscv** [comment]
.Figure title
[wavedrom, svg]
----
{reg:[
    { bits:  7, name: 0x3b, attr: ['OP-32'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x0, attr: ['ADD.UW'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  7, name: 0x04, attr: ['ADD.UW'] },
]}
----

You have the option of referencing a graphics file directly:

[#wavedrom_example2]
.This example is from an svg generated prior to the build
image::wavedrom/wavedrom-example2.svg[wavedrom_example2]

.Wavedrom example
[wavedrom, svg]
....
{reg: [
  {bits: 7,  name: 'opcode'},
  {bits: 5,  name: 'rd'},
  {bits: 3,  name: 'func3'},
  {bits: 5,  name: 'rs1'},
  {bits: 5,  name: 'rs2'},
  {bits: 7,  name: 'funct7'}
], config: {label: {right: 'z-Type'}}}
....

More information here.

.Wavedrom W
[wavedrom,svg]
----
{reg: [
  {bits: 7,  name: 'opcode'},
  {bits: 5,  name: 'rd'},
  {bits: 3,  name: 'func3'},
  {bits: 5,  name: 'rs1'},
  {bits: 12, name: 'imm[11:0]', type: 3},
], config: {label: {right: 'VV-Type'}}}
----

.Wavedrom S
[wavedrom,svg]
----
{reg: [
  {bits: 7,  name: 'opcode'},
  {bits: 5,  name: 'imm[4:0]', type: 3},
  {bits: 3,  name: 'func3'},
  {bits: 5,  name: 'rs1'},
  {bits: 5,  name: 'rs2'},
  {bits: 7,  name: 'imm[11:5]', type: 3}
], config: {label: {right: 'S-Type'}}}
----

**Comment by pepijnve** [comment]
Have a look at https://docs.asciidoctor.org/diagram-extension/latest/#creating-a-diagram

The block attributes are always key-value pairs. When the key is omitted, it is derived implicitly from the index of the attribute. For block macros

```
[diagram-type, generated-file-name, generated-image-format]
```

is equivalent to

```
[diagram-type, target=generated-file-name, format=generated-image-format]
```

If you do not care about the name of the generated diagram file, the simplest is to write

```
[wavedrom, format=svg]
```

Alternatively if you want SVG for all your wavedrom diagrams you can set this at the document level as well like this

```
:wavedrom-format: svg

[wavedrom]
```

The syntax you're probably trying

```
[wavedrom,,svg]
```

should work as well, but there was a parsing bug in asciidoctor at one point that you might be hitting. See https://github.com/asciidoctor/asciidoctor-diagram/issues/305 and https://github.com/asciidoctor/asciidoctor/issues/3813 for the details.

**Comment by elisa-riscv** [comment]
Thanks for the clarification.

In my opinion, the current documentation at https://docs.asciidoctor.org/diagram-extension/latest/#creating-a-diagram could use some improvement. I suggest that the macro syntax be _introduced_ with
....
[diagram-type, target=file-name, format=image-format]
....

After that, the point that it's possible to omit the key names because the parser automatically assigns (it does *not* derive--the word derive gives an incorrect connotation here) those keynames based on order of appearance in the macro, is easier to understand. 

I am not a fan of the use of the phrases, "generated-file-name" and "generated-image-format" because adding the file name and the format *precedes* the generation and therefore  using the past tense creates a subtle dissonance for the literal-minded. 

I am certain that I hit the bug, because the diagrams were working properly without filenames for a while.

Thanks for your timely responses.

**Comment by mojavelinux** [comment]
Would you be willing to submit a pull request that includes your suggested changes to the documentation?

**Comment by pepijnve** [comment]
> In my opinion, the current documentation at https://docs.asciidoctor.org/diagram-extension/latest/#creating-a-diagram could use some improvement. I suggest that the macro syntax be _introduced_ with
> ....
> [diagram-type, target=file-name, format=image-format]
> ....

I was thinking the exact same thing yesterday. It would be better to introduce the full, explicit syntax first rather than start with the compact form.

> After that, the point that it's possible to omit the key names because the parser automatically assigns (it does _not_ derive--the word derive gives an incorrect connotation here) those keynames based on order of appearance in the macro, is easier to understand.

I'm not a native English speaker, nor a professional writer, so no surprises that there are subtley incorrect connotations. Why is 'derive' in the meaning of 'infer' or 'deduce' wrong in this context though? I'm not sure what the incorrect connotation is here.

> I am not a fan of the use of the phrases, "generated-file-name" and "generated-image-format" because adding the file name and the format _precedes_ the generation and therefore using the past tense creates a subtle dissonance for the literal-minded.

Any suggestions for replacements? 'name of file that will be generated' is a bit verbose. 'target-file-name'?

**Comment by mojavelinux** [comment]
> Any suggestions for replacements? 'name of file that will be generated' is a bit verbose. 'target-file-name'?

I think `output-file-name` would work here. Just like with the converter itself, we are assuming that the software is going to create something for us from the input given. It's the same concept here. The "output" is well defined in conversion (particularly within this ecosystem) as meaning the thing that the software creates.

"target" could be confusing since that is used in AsciiDoc to indicate the subject of a reference. So the user might think that it needs to exist already.

**Comment by mojavelinux** [comment]
Another possible alternative to "output" is "destination", but it's my second choice.

**Comment by pepijnve** [comment]
The name of the attribute is, perhaps a bit unfortunately in retrospect, `target` though. `[diagram-type, target=output-file-name]`. Should we consider renaming that? I can keep support for `target` in place for backwards compatibility of course.

**Comment by elisa-riscv** [comment]
Happy to do so by some time tomorrow. :-)

**Comment by pepijnve** [comment]
I updated the text a bit for the 2.2.0 release. There's still a lot of room for improvement on the documentation front. Any help here is much appreciated.

**Comment by elisa-riscv** [comment]
I do intend to suggest some edits in a pull request and apologize for the
delays. I have had some real emergencies come up. I need to meet a deadline
this week and plan to free up some time soon.

**Comment by pepijnve** [comment]
Closing this issue for now. Still happy to accept any documentation improvement PRs when/if they are submitted.
