### ISSUE TITLE
ditaa svg output crashes Batik

### ISSUE THREAD

**Issue by metro69** [asciidoctor/asciidoctor-diagram#366]
The ditaa svg output adds the following style:
```
<style type='text/css'>@font-face {
  font-family: sans-serif;
}</style>
```

This crashes Batik in Apache Fop (i.e. in the docbook to pdf flow in Asciidoctor).

Is it possible to add an option to suppress adding this style?

Are there other options to make this work in Batik?

Thanks,
MT

**Comment by pepijnve** [comment]
This is fixed in asciidoctor-diagram-ditaamini 1.0.1. That version will only output an `@font-face` rule if a font URL has been provided to ditaa.
