### ISSUE TITLE
Behavior of svg-type="inline" vs. opts="inline"

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#368]
For https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/805 I observed the following behavior: 

When specifying an `imagesoutdir` and adding `svg-type="inline"` to the diagram, asciidoctor-diagram passes the image information so that it is inlined into the output HTML. 

When specifying an `imagesoutdir` and adding `opts="inline"` to the diagram, asciidoctor-diagram passes the image without folder information so that Asciidoctor doesn't find the file and it won't be inlined.

Reading the docs of asciidoctor-diagram, using `svg-type="inline"` is the documented way to go. Still, it might be the intuitive way to also support `opts="inline"` the same way. 

Looking at the code the following snippets in diagram_processor.rb would be the one to be enhanced to not only look at `svg-type`, but also `opts` to set the variable `use_absolute_path` to true. 

This is the current code, without changes: 

```rb
        use_absolute_path = source.attr('data-uri', nil, true)

        if format == :svg
          svg_type = source.global_attr('svg-type')
          case svg_type
            when nil, 'static'
            when 'inline', 'interactive'
              node.set_option(svg_type)
              use_absolute_path = true
            else
              raise "Unsupported SVG type: #{svg_type}"
          end
        end

        if use_absolute_path
          node.set_attr('target', image_file)
        else
          node.set_attr('target', image_name)

          if source.global_attr('autoimagesdir')
            image_path = Pathname.new(image_file)
            output_path = Pathname.new(parent.normalize_system_path(output_dir(parent)))

            imagesdir = image_path.relative_path_from(output_path).dirname.to_s
            node.set_attr('imagesdir', imagesdir)
          end
        end

        node
      end
```

**Comment by pepijnve** [comment]
Makes sense. I'll fix that asap.

**Comment by pepijnve** [comment]
My own code has me a bit puzzled, but it's been like this for quite some time. We basically always use absolute paths for SVG files regardless of the style. Not sure why I did that and not for, for instance, PNGs.

**Comment by pepijnve** [comment]
Never mind, Ruby cases don't fall through. That had me confused for a moment.
