### ISSUE TITLE
Absolute path for "interactive" svg

### ISSUE THREAD

**Issue by Flugtiger** [asciidoctor/asciidoctor-diagram#370]
We use plantuml to render an interactive svg diagram. With 2.2.1 our diagram is no longer visible in the asciidoc output, because there is an absolute path inserted where there was a relative path before. This is caused by #368 

Our options for the plantuml diagram look like this: [plantuml%interactive,solutionStrat,svg]

We need a relative path since the asciidoc html output is copied to a webserver and the browser needs to use the relative path to load the svg.

**Comment by pepijnve** [comment]
Sorry for that regression. This is one of those points where the API between asciidoctor core and the extensions isn't really rich enough to communicate intent. The extension needs to "guess" what's appropriate, but that's dependent on the backend that's being used. I'll try to get this fixed asap.

**Comment by pepijnve** [comment]
The fix for this will be included in v2.2.2
