### ISSUE TITLE
puppeteerConfigFile attribute not forwarded to mmdc

### ISSUE THREAD

**Issue by softmetz** [asciidoctor/asciidoctor-diagram#371]
I tried to generate a mermaid diagram inside an Asciidoc file inside docker. For this I need to provide a puppeteer config file which configures Chrome to not create a sandbox.

According to the documentation, the path to the puppeteer config file can be given using the attribute `puppeteerConfigFile`. But as it turns out, setting the attribute does not call mmdc with the proper command line parameter.

I called Asciidoctor via

`asciidoc-pdf -r asciidoctor-diagram -a puppeteer-config=/path/to/file input.adoc`

I worked around it by creating a `mmdc` wrapper script which gives the parameter directly, but the parameter should also be set by setting the attribute.

**Comment by pepijnve** [comment]
When attribute values are specified at a higher level than the individual block you need to prefix the attributes with `<diagram-type>-`. `-a mermaid-puppeteer-config` should work.

**Comment by pepijnve** [comment]
Closing since I don't think there's actually a bug here
