### ISSUE TITLE
Rendering of Ditaa diagrams via PlantUML fails with ClassNotFoundException

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#373]
The following snippet

```
[plantuml]
----
@startditaa -E
+---------+
| example |
+---------+
@endditaa
----
```

fails with the following Exception (actually an image): 

![diag-8033e54066a115ecce22ae0dfdb578ac](https://user-images.githubusercontent.com/3957921/138917827-2d8b8845-8dcf-40e3-8cc6-b09bbc558683.png)

Setup: 

```
Windows / ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
Using asciidoctor 2.0.16
Using asciidoctor-diagram-ditaamini 1.0.1
Using asciidoctor-diagram-plantuml 1.2021.8
Using rexml 3.2.5
Using asciidoctor-diagram 2.2.1
```

CLI: `asciidoctor -r asciidoctor-diagram test.adoc`

Suspected root cause: asciidoctor-diagram-plantuml doesn't bundle ditaamini. 

Suggested fix: If asciidoctor-diagram-ditaamini is present, load those JARs as well to render ditaa diagrams via PlantUML.

This has originally been reported by @aklemp in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/902

**Comment by pepijnve** [comment]
@ahus1 I added just enough shims to ditaamini to allow rendering of ditaa via PlantUML to work. Requires ditaamini 1.0.3.

**Comment by ahus1** [comment]
Thanks for that - I tested it in the upcoming pre-release 0.37.22 of the AsciiDoc IntelliJ plugin and it works great!
