### ISSUE TITLE
plantuml attribute to set -Dplantuml.include.path

### ISSUE THREAD

**Issue by mskyaxl** [asciidoctor/asciidoctor-diagram#375]
I saw other topics related to "puml includes" but none of them matched to my issue. So I hope I'm not repeating myself.

https://docs.asciidoctor.org/diagram-extension/latest/#diagram-attributes describes the way a user could set specific Attributes for diagrams.

```adoc
= Asciidoctor Diagram
:blockdiag-fontpath: /path/to/font.ttf 

[blockdiag] 
....
....
```

For planuml I only see the option to provide a ```config``` configuration.

Is it possible to also provide an include path for puml.

I would like to be able to use such a syntax
```adoc
//some content


:plantuml-includedir: <some path> // this is more like the -Dplantuml.include.path="<somepath>" property for the plantuml
:plantumldir: <some other path> //this is just the location where the plantuml files are located

plantuml::{plantumldir}/myDiagram1.puml[target="{targetumldir}/myDiagram1",format=svg]

plantuml::{plantumldir}/myDiagram2.puml[target="{targetumldir}/myDiagram2",format=svg]
//some content
```
where myDiagram1.puml would be something like this
```puml
@startuml
!include myGeneralStyling.puml
`I would like to keep these lines here because I want to see the preview when I open the diagram standalone
!include someA.puml

` concrete diagram
`
@enduml
```

and myDiagram2.puml would be something like this
```puml
@startuml
!include myGeneralStyling.puml
!include someB.puml

` concrete diagram
`
@enduml
```

Is it possible to change the include path for plantuml using an attribute as suggested?
Using a central way of configuring the include paths makes things easier because you don't have to update any puml when the included files are moved around.

More info about the Search path:
https://plantuml.com/preprocessing#4d03410776ebc180

**Comment by mojavelinux** [comment]
If this request is accepted, I'd like to see the name of the attribute be `plantumldir` to be consist with the pattern used for the image macros.

**Comment by mskyaxl** [comment]
For me ``plantumldir`` makes me think of a directory where all the plantuml files are located. My intention is to provide a folder where the "puml headers" are located so IMHO ``plantumlincludedir`` looks like a better choice. But that's less important to me :)

**Comment by mojavelinux** [comment]
Oh, I see. In your example, there are two paths to consider. One (plantumldir) is where the plantuml files are located. That would replace `{path}` in the target of the `plantuml` macro. There would then need to be a second attribute that controls where the puml headers are located. For that, I'd be fine with something like `planumlincludedir` (or `plantuml-includedir` if that makes it easier to read.

**Comment by mskyaxl** [comment]
Ah, sorry for the confusion, I "fixed" the description to make it more clear.  I'll try to have a look over the weekend maybe I can figure out how to do it but I'll probably need some support.

**Comment by mskyaxl** [comment]
It seems to be really similar to #339

**Comment by mskyaxl** [comment]
I've created #377 that should solve this issue.

**Comment by pepijnve** [comment]
@mskyaxl everything is integrated; looking good. Thanks for your contribution!

**Comment by pepijnve** [comment]
> I don't understand where the *.jar are coming from.(It looks a little bit weird to me to keep jar files in git :) )

Agreed that it's suboptimal. I don't know if there's a better way to tackle this without a significant amount of work in setting up the build chain. The jars don't change all that often so I felt this was the most pragmatic solution. If you know a better approach to mix Ruby and Java in one project, I'm open to suggestions.

**Comment by f3tta1i** [comment]
@pepijnve can we get this PR included in a release? I would like to use it :)
Thanks!
