### ISSUE TITLE
Images inside of diagrams not rendering

### ISSUE THREAD

**Issue by Alwinator** [asciidoctor/asciidoctor-diagram#378]
I want to use a diagram that includes an [image](https://avatars.githubusercontent.com/u/3137042?s=280&v=4) inside of my asciidoctor document. However, the image inside of the diagram does not render in the document. When I directly build the diagram using the `blockdiag` command it works.

It also does not work with graphviz diagrams. I have this problem both when creating HTML and PDF.

`test.diag`
```blockdiag
blockdiag {
   A [label = "", background = "asciidoctor.png"];
   A -> B;
}
```

Output of the `blockdiag test.diag` command:
![test](https://user-images.githubusercontent.com/39517491/153478376-f73863c1-631a-40fa-a9b4-24d71294e3c6.png)

`test.adoc`
```asciidoc
== Test

[blockdiag, format=png]
----
include::test.diag[]
----
```
The image rendered from asciidoctor:
![diag-de9e625d4980107e4cde6f2a5b6252e0](https://user-images.githubusercontent.com/39517491/153478579-7b2e6e53-e764-487b-9fad-54011c586007.png)

**Comment by pepijnve** [comment]
Could you give this a try instead `blockdiag::test.diag[format=png]`? The difference between the two is that in your example the diagram processor uses the directory containing `test.adoc` as base directory while in my suggestion the base directory containing `test.diag` should get used.

**Comment by Alwinator** [comment]
@pepijnve Thank you for your comment. Unfortunately, I have the same problem with `blockdiag::test.diag[format=png]`. (All three files (.adoc, .diag, .png) are in the same directory.)

**Comment by pepijnve** [comment]
I think this has to do with the current directory of the blockdiag subprocess not being set at all. As a consequence the resolution of the image path will start from the current directory of the shell from which asciidoctor is being run. Could that explain the difference we're seeing?

**Comment by Alwinator** [comment]
@pepijnve Sorry for the long delay. I was finally able to reproduce the bug in a new environment. I have used Docker to make sure that it also works on your machine. You can find the code here: https://github.com/Alwinator/asciidoctor-diagram-image-bug

**Comment by Alwinator** [comment]
@pepijnve Were you able to reproduce the bug on your computer using the Docker image?

**Comment by pepijnve** [comment]
I haven't had a chance to try yet. Paid work is keeping me occupied.

**Comment by Alwinator** [comment]
@pepijnve That's okay! Just tell me when you reviewed it.

**Comment by Alwinator** [comment]
It was a path issue, I've fixed it by setting the `:outdir:` parameter in addition to the `:imagesdir:`.
