### ISSUE TITLE
PlantUml includes resolved locally and not on Kroki

### ISSUE THREAD

**Issue by LukeCz** [asciidoctor/asciidoctor-diagram#380]
Hi,

It seems that !inlcude is resolved locally before sending to Kroki server (when diagram-server-url is used). This is causing error when some extensions are installed on the server but not locally.
The example below works when commenting out the offending line (the sprite is just not rendered) or when converting to base64 and sensing to Kroki server manually.

Example:

[plantuml]
----
@startuml
!include <c4/C4_Container>
!include crashedmind-plantuml-icons-gcp-master/GCPCommon.puml
!include crashedmind-plantuml-icons-gcp-master/API_Management/Cloud_Endpoints.puml

System_Ext(gateway, "Cloud Endpoints", "API Gateway", $sprite=Cloud_Endpoints)
@enduml
----

asciidoctor-pdf test.adoc -r asciidoctor-diagram -a diagram-server-url="http://test.test.com:8080" -a diagram-server-type=kroki_io 
asciidoctor: ERROR: test.adoc: line 3: Failed to generate image: PlantUML preprocessing failed: [From <input> (line 3) ]

@startuml
!include <c4/C4_Container>
!include <C4/C4_Context>
!include <C4/C4>
' C4-PlantUML
...
... ( skipping 3312 lines )
...

!unquoted procedure ContainerDb_Ext($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
!$sprite=$toElementArg($sprite, $tags, "ElementTagSprite", "external_container")
!$techn=$toElementArg($techn, $tags, "ElementTagTechn", "external_container")
database "$getContainer($label, $techn, $descr, $sprite)$getProps()" $toStereos("external_container", $tags) as $alias $ ...
!endprocedure

!unquoted procedure ContainerQueue_Ext($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
!$sprite=$toElementArg($sprite, $tags, "ElementTagSprite", "external_container")
!$techn=$toElementArg($techn, $tags, "ElementTagTechn", "external_container")
queue "$getContainer($label, $techn, $descr, $sprite)$getProps()" $toStereos("external_container", $tags) as $alias $get ...
!endprocedure

' Boundaries
' ##################################

!unquoted procedure Container_Boundary($alias, $label, $tags="", $link="")
Boundary($alias, $label, "Container", $tags, $link)
!endprocedure
!include crashedmind-plantuml-icons-gcp-master/GCPCommon.puml
^^^^^
 cannot include crashedmind-plantuml-icons-gcp-master/GCPCommon.puml

**Comment by pepijnve** [comment]
That's correct, PlantUML code is preprocessed client side before sending it off to a server. This was implemented for issue #335. I don't think there's a way to have our cake and eat it here. The preprocessing is handled by PlantUML itself and there's no way to tell it to process some includes but not others.

**Comment by LukeCz** [comment]
Thanks for the answer. This is solved if you use Asciidoc includes (include::) for local and delegate all PlantUml includes (!include) to Kroki. This is how other tools are doing it, for example Antora or IntelliJ plugin.

**Comment by pepijnve** [comment]
I've added support for a `preprocess` attribute. When set to `false` local preprocessing is disabled entirely.
