### ISSUE TITLE
Rendering sequence diagram fails on big note

### ISSUE THREAD

**Issue by drachenpalme** [asciidoctor/asciidoctor-diagram#384]
The following diagram fails to compile using the current asciidoctor plugin (0.37.19) in a current intellij installation (2022.1.2) with the diagram extensions installed:

    participant P1
    participant P2
    
    [-> P1 ++ : new task
    
    P1 -> P2 ++ : other task
    
    alt someCondition   
    else else
      note over P1
    	Text of some length fails
      end note
    [<- P1: abort
    end

I have pinned it down to the length of the text within the note. As soon as the note-text hits the border of the alt-fragment, generating the diagram fails with the message "PlantUML (1.2021.8) cannot parse result from do/GraphViz".
As soon as the word "fails" is removed from the note, the text no longer collides with the alt-fraagment border and the diagram is rendered. Also, putting this diagram to the standalone plantuml (2022.5) with the word "fails" works as expected - the alt-fragment is extended in width.

**Comment by pepijnve** [comment]
The error your seeing is being generated by PlantUML. Not something I can fix in the extension. The extension can work with PlantUML 1.2022.5, but for some reason the IntelliJ plugin is using an older version.
@ahus1 is there a way to update the used plantuml version? From a ruby gem point of view, you want to use the most recent version of https://rubygems.org/gems/asciidoctor-diagram-plantuml which is basically the plantuml jar wrapped in a gem.

**Comment by drachenpalme** [comment]
Hi @ahus1, @pepijnve,

You are right, with the pre-release the issue is gone. I guess, this is really bad timing as the bug itself is a regression in plantuml (some very old version on my disk rendered the diagramm correctly).

Thanks a lot.
