### ISSUE TITLE
mermeid-puppeteer-config option set at the document level is ignored. 

### ISSUE THREAD

**Issue by kenmasumitsu** [asciidoctor/asciidoctor-diagram#385]
As I referred to https://docs.asciidoctor.org/diagram-extension/latest/#diagram-attributes, I set `puppeteer-config` attribute for mermaid at the document level.
However the attribute was ignored. So that, the generated pdf missed the image.

```
= Asciidoctor Diagram
:mermeid-puppeteer-config: /puppeteer-config.json

[mermaid]
....
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
....
```

`--puppeteerConfigFile` option is **NOT** seen in the console log of asciidoctor-pdf.

```
asciidoctor: DEBUG: Executing ["/home/mermaidcli/node_modules/.bin/mmdc", "-i", "/tmp/mmdc20220630-987-fezwv3.mmd", "-o", "/tmp/mmdc20220630-987-x8gjtw.png"] with options {} and environment {"NODE_OPTIONS"=>"--unhandled-rejections=strict"}
```

But, if the diagram specifies `puppeteer-config` attribute (instead of at the document level) , it worked expectedly.

```
[mermaid, puppeteer-config=/puppeteer-config.json]
....
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
....
```

`--puppeteerConfigFile` option is seen in the console log of asciidoctor-pdf.
```
asciidoctor: DEBUG: Executing ["/home/mermaidcli/node_modules/.bin/mmdc", "-i", "/tmp/mmdc20220630-728-pwomwb.mmd", "-o", "/tmp/mmdc20220630-728-30gxi6.png", "--puppeteerConfigFile", "/puppeteer-config.json"] with options {} and environment {"NODE_OPTIONS"=>"--unhandled-rejections=strict"}
```

**Comment by KartikSoneji** [comment]
Can't replicate, setting `mermaid-puppeteer-config` works for me.

**Comment by kenmasumitsu** [comment]
Thanks for your responses. It was my fault. Close it.
