### ISSUE TITLE
Could asciidoctor-diagram support diagrams.net？

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-diagram#390]
Docsy theme of Hugo supports, [Diagrams and Formulae | Docsy](https://www.docsy.dev/docs/adding-content/diagrams-and-formulae/#diagrams-with-diagramsnet).

diagrams.net(draw.io) is a popular diagram tool. It also provides a cross-os client.

Could asciidoctor-diagram support [diagrams.net](https://app.diagrams.net/)？

**Comment by pepijnve** [comment]
See #213
