### ISSUE TITLE
Why text has overlapping characters

### ISSUE THREAD

**Issue by yuto-katsuragi** [asciidoctor/asciidoctor-diagram#392]
## Probrem
I tried to embed PlantUMLs diagram into pdf, but the text has overlapping characters. It text(カード) is in japanese.

![image](https://user-images.githubusercontent.com/9588876/189244452-cf7e1320-8a6b-4132-b89f-c309aa04f2d5.png)

## Environments
Versions:
asciidoctor - 2.0.17
asciidoctor-pdf - 2.3.0
asciidoctor-diagram - 2.2.3

## Steps to reproduce
Create 'diagram.adoc'.

```diagram.adoc
:encoding: utf-8
:lang: ja
:scripts: cjk
:pdf-theme: default-with-fallback-font

[plantuml,format=svg]
....
@startuml

card カード

@enduml
....
```

and 'patch.rb' patch file for prawn-svg.

```patch.rb
require 'prawn-svg'

Prawn::Svg::Font::GENERIC_CSS_FONT_MAPPING.merge!(
  'sans-serif' => 'M+ 1p Fallback'
)
```

then run command following.

```bash
$ asciidoctor-pdf diagram.adoc -r asciidoctor-diagram -r patch.rb
```

**Comment by mojavelinux** [comment]
You seem to have missed this section in the documentation:

https://docs.asciidoctor.org/pdf-converter/latest/image-paths-and-formats/#svg

If you create plantuml.cfg and populate it with the following text:

```
skinparam defaultFontName M+ 1p Fallback
```

Then declare it in your document:

```
:plantumlconfig: plantuml.cfg
```

I think you'll find it does the right thing. Be sure to clear your cache so that Asciidoctor Diagram recreates the image.

**Comment by mojavelinux** [comment]
Alternately, you can remap sans-serif in a PDF theme:

```
font:
  catalog:
    merge: true
    sans-serif: GEM_FONTS_DIR/mplus1p-regular-fallback.ttf
```

**Comment by yuto-katsuragi** [comment]
This problem occurred when installing asciidoctor and others with nix-shell.
I apologize for the flawed reproduction procedure I wrote. I am going to close this issue.

@mojavelinux
Thanks for the documentation and the instructions I had missed.

**Comment by mojavelinux** [comment]
FYI, I added a test to Asciidoctor PDF to verify that the instructions provided in the docs are correct. See https://github.com/asciidoctor/asciidoctor-pdf/blob/7bd05cbe4c4db016bc30734f532639e3c2abcbd6/spec/diagram_spec.rb#L28-L51
