### ISSUE TITLE
PlantUML default Theming

### ISSUE THREAD

**Issue by Syndlex** [asciidoctor/asciidoctor-diagram#399]
PlantUML allowes to set --theme as a call parameter.
It would be nice to make this parameter accessible with environment Variables or as a parameter for the diagram Extension.

**Comment by pepijnve** [comment]
I had a look at the plantuml code and as far as I can tell `-theme <theme>` is syntactic sugar for injecting a `!theme <theme>` line in the plantuml config. Would that be a good enough workaround for you?

**Comment by Syndlex** [comment]
Our plan is to enforce a plantuml style in our company documentation. 
We don't wand to put the `!theme` reference on every plantuml definition we have. Since this is a lot of manuel labor and error prone.

I tried using the configuration overwrite environment variable from plantuml but wasn't successful.

I don't fully understand what you mean with "injecting" here

**Comment by pepijnve** [comment]
> I don't fully understand what you mean with "injecting" here

If you specify a config file using `-config <file>` and a theme using `-theme <theme>`, PlantUML will read the contents of the `<file>` and add a line `!theme <theme>` to it. You could do the same thing manually and only specify the config file; the end result should be identical.

**Comment by pepijnve** [comment]
I've added a `theme` attribute (`plantuml-theme` at the document level) that should do the trick. Could you give v2.2.4 a try?

**Comment by Syndlex** [comment]
Nice, it works great!! :) That was fast. 

Thank you for the change :+1:
