### ISSUE TITLE
[PROPOSED] Replace ERD (Haskell) with erd-go

### ISSUE THREAD

**Issue by barthel** [asciidoctor/asciidoctor-diagram#402]
As part of https://github.com/asciidoctor/docker-asciidoctor/issues/51 I have been trying to create a multi-platform Asciidoctor Docker image.

In doing so, `erd` (https://github.com/BurntSushi/erd) was a challenge, as there is only one `x86` platform variant.

To remove this limitation, I looked at `erd-go` (https://github.com/kaishuu0123/erd-go/) and included it.
Since it supports the same CLI parameters, replacing the executable was enough.

To further promote platform independence, I would like to propose an official switch to or support of `erd-go`.

**Comment by barthel** [comment]
`erd` was introduced with #118

**Comment by barthel** [comment]
WDYT? @pepijnve @mojavelinux

**Comment by barthel** [comment]
Used and testable via Docker Image https://hub.docker.com/r/uwebarthel/asciidoctor/

**Comment by pepijnve** [comment]
@dduportal I understand the concern. Not really an issue for the diagram extension itself since it supports both the Haskell and Go version now preferring the former over the latter.

**Comment by barthel** [comment]
@dduportal You are not a party chrasher. Security concerns are important and valid at any time.

The goal of using èrd-go`is to use a platform independend tool.
As a consequence, èrd-go`will be compiled for each platform and no pre-compiled executables are used.

Let's discuss in https://github.com/asciidoctor/docker-asciidoctor/issues/343#issuecomment-1482429267

**Comment by barthel** [comment]
Challange accepted for a more than less platform independent Asciidoctor.
