### ISSUE TITLE
D2 diagram support

### ISSUE THREAD

**Issue by liefra** [asciidoctor/asciidoctor-diagram#407]
Are there plans to support the [D2 diagram scripting language](https://d2lang.com/)? Or is this already working somehow?

**Comment by pepijnve** [comment]
D2 isn't supported yet, but basic integration should be pretty trivial to add.

**Comment by liefra** [comment]
Hi, @pepijnve. Wow, that was very fast. Incredible! Thanks a lot for this rapid implementation
