### ISSUE TITLE
D2: --sketch takes no parameters

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-diagram#409]
when trying to enable the sketch mode with d2 for eg like

```
[d2,gen/05_dispatcherd2,svg,layout=tala,theme=3,sketch=true]
```

it fails with 
Failed to generate image: d2 failed: err: bad usage: too many arguments passed

when ommitting the parameter value it gets filtered out completely,

I guess there could be an additional check in

https://github.com/asciidoctor/asciidoctor-diagram/blob/6cc8cc4bf46304bdaf8f3eb7e89929bd6b17edef/lib/asciidoctor-diagram/d2/converter.rb#L36

**Comment by pepijnve** [comment]
Thanks for testing; should have written some extra tests...

**Comment by eiswind** [comment]
Thanks for the quick fix!

**Comment by eiswind** [comment]
I finally could test your changes. Sadly it's not working.
```
if key == :sketch && value != 'false'
  args << flag
elsif key.to_s.start_with?('font') && !value.nil?
  args << Platform.native_path(value)
elsif !value.nil?
  args << flag
  args << value
end
```
now sketch is enabled by default. 

if i pass sketch=false it goes to the last branch and adds --sketch false which breaks the command.

**Comment by pepijnve** [comment]
Sorry about this. That's what I get for trying to rush things...

**Comment by eiswind** [comment]
Never mind. I use to get such boolean chains wrong every time. Didn't see it until it didn't work :)

**Comment by pepijnve** [comment]
I have a fix ready that should prevent this kind of problem once and for all. Positional attributes like `sketch` will get converted to `sketch=true`. The converter itself doesn't need to handle the differences between the two forms that way.

**Comment by petr-nechaev** [comment]
Well, I guess it should be:
```
if @attributes[attr_position] == name
     value = false
end
```
but not `true`
