### ISSUE TITLE
D2: Set working directory for the process(?) to document dir so that relative images can be resolved.

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-diagram#410]
Currently an image relative to the document cannot be resolved.

```
test: {
  shape: image
  icon: ./images/target.png
}

**Comment by eiswind** [comment]
After a  little digging i have to add that I'm running on JRuby. There is a "JAVA" switch there for the CLI Runner.
Doing Dir.pwd prints the documents directory, so this seems to be ok.

but  d2 is using my Home-Directory for the basepath, but I did not find out where this is coming from.

Can anyone give me a pointer here?

**Comment by pepijnve** [comment]
@eiswind could you give df004ecb65649850da045732d144c2725b8e9349 a try on jruby? I've tested with MRI already and that works correctly now affect.

**Comment by eiswind** [comment]
I can confirm that this is ok now.
