### ISSUE TITLE
Creating an inline barcode logs an info message

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#416]
Given the following input

```
qrcode:https://my-link.tld/something[]
```

and rendering it with INFO messages enabled (`-v`)

```
asciidoctor -r asciidoctor-diagram test.adoc -v
```

there is a INFO message indicating a possible problem:

> asciidoctor: INFO: expected substitution value for custom inline macro to be of type Inline; got String: `qrcode:https://my-link.tld/something[]`

This only occurs with the inline macro, not with the block macro.

**Comment by ahus1** [comment]
Might be related to this - the following code: 

```
qrcode:https://my-link.tld/something[format=txt]
```

creates this error message: 

> asciidoctor: ERROR: test.adoc: line 3: Failed to generate image: Asciidoctor::Diagram::BarcodeInlineMacroProcessor does not support output format txt
undefined method `include?' for nil:NilClass

**Comment by pepijnve** [comment]
Looks like I got that wrong when I added inline support. The processor was eagerly converting the Inline node instead of returning it.

**Comment by mojavelinux** [comment]
That used it be how it was, but it changed in Asciidoctor 2.
