### ISSUE TITLE
Structurizr docs missing on the docs page

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#418]
I've been investigating issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1364 and found that the `structurizr` macro is not documented on the [docs page](https://docs.asciidoctor.org/diagram-extension/latest/).

Is there something I'm missing on how to use that macro? Thanks!

**Comment by pepijnve** [comment]
I'm working on improving the docs. See https://github.com/asciidoctor/asciidoctor-diagram/blob/master/docs/modules/ROOT/pages/structurizr/index.adoc

I've reset the documentation tag to https://github.com/asciidoctor/asciidoctor-diagram/commit/54a2ae517b5a1688d4032dcf5183b9a7ff1c70bd so the new split version of the docs should appear online the next time the asciidoctor doc site is built. Feel free to make PRs against the updated docs or suggest improvements. It's still very much work-in-progress.
