### ISSUE TITLE
Could not find the 'blockdiag', 'blockdiag3' executable in PATH (Windows)

### ISSUE THREAD

**Issue by ioannisstavrakakis** [asciidoctor/asciidoctor-diagram#421]
I would need to know where you have blockdiag installed, what the value of the PATH environment variable is, and what the exact filename of the blockdiag executable is, including the extension.
When running `asciidoctor-pdf -r asciidoctor-diagram --trace test.adoc` in Windows, I get the following error:

`asciidoctor: ERROR: test.adoc: line 248: Failed to generate image: Could not find the 'blockdiag', 'blockdiag3' executable in PATH;add it to the PATH or specify its location using the 'blockdiag' document attribute`

User variable PATH: C:\Python311\Lib\site-packages\blockdiag
System variable PATH: C:\Python311\Lib\site-packages\blockdiag

This is where blockdiag is installed:

![image](https://github.com/asciidoctor/asciidoctor-diagram/assets/87022642/cf2b2fc8-df8d-4d70-be19-1dfe572f2b6e)

I can also see this folder, C:\Python311\Lib\site-packages\blockdiag-3.0.0.dist-info:

![image](https://github.com/asciidoctor/asciidoctor-diagram/assets/87022642/7f68fbf0-20ca-4438-a1a6-528e01cdec5e)

**Comment by ioannisstavrakakis** [comment]
I unisntalled and reinstalled it, and now I notice this error message during installation:

```
pip install blockdiag
Collecting blockdiag
  Using cached blockdiag-3.0.0-py3-none-any.whl (2.7 MB)
Requirement already satisfied: setuptools in c:\python311\lib\site-packages (from blockdiag) (65.5.0)
Requirement already satisfied: funcparserlib>=1.0.0a0 in c:\python311\lib\site-packages (from blockdiag) (1.0.1)
Requirement already satisfied: Pillow>3.0 in c:\users\istavrak\appdata\roaming\python\python311\site-packages (from blockdiag) (9.5.0)
Requirement already satisfied: webcolors in c:\python311\lib\site-packages (from blockdiag) (1.13)
Installing collected packages: blockdiag
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\blockdiag.exe' -> 'C:\\Python311\\Scripts\\blockdiag.exe.deleteme'
```

**Comment by pepijnve** [comment]
Based on https://github.com/pypa/pip/issues/9023 you need to install as a user with Administrator privileges

**Comment by ioannisstavrakakis** [comment]
Yes, that did the trick!
Many thanks!
