### ISSUE TITLE
Colon in filename gives an error when creating a PNG from a Lilypond diagram on a Windows folder

### ISSUE THREAD

**Issue by georgeraraujo** [asciidoctor/asciidoctor-diagram#424]
Hi,
I run asciidoctor in a Linux guest VM in VirtualBox on a Windows host. I mount a Windows folder on a mount point in the Linux VM.

I noticed that the last release supports Lilypond diagrams (THANKS!) and decided to try it. When I processed the sample document, I got an error; when I tried it again in a folder inside the VM's virtual hard disk, it worked fine:

```
vboxuser@asciidoctor:/mnt/windows_shared_folder$ asciidoctor -r asciidoctor-diagram lilypond.adoc
asciidoctor: ERROR: lilypond.adoc: line 6: Failed to generate image: Protocol error @ rb_sysopen - /mnt/windows_shared_folder/diag-:md5:b7d074b335dbb39dbd4e4501c5a27831.png
vboxuser@asciidoctor:/mnt/windows_shared_folder$ cd ~/linux_folder/
vboxuser@asciidoctor:~/linux_folder$ asciidoctor -r asciidoctor-diagram lilypond.adoc
vboxuser@asciidoctor:~/linux_folder$ ls
diag-:md5:b7d074b335dbb39dbd4e4501c5a27831.png  lilypond.adoc  lilypond.html
vboxuser@asciidoctor:~/linux_folder$
```

I think that's because the filename for the generated PNG has a colon (`:`). Would you consider changing the colon for some other character, or dropping it altogether?

Thanks!

**Comment by pepijnve** [comment]
Based on your output it looks like the host OS is Windows. That would explain the error. I'll change the separator character to something that's valid on Windows filesystems as well.
