### ISSUE TITLE
Regression: Version 2.2.10 generates wrong image path

### ISSUE THREAD

**Issue by SebastianKuehn** [asciidoctor/asciidoctor-diagram#427]
Hello,

we have a regression in version 2.2.10. Since this version the following img-tag is created:
```
<img src="diag-:md5:70e2bf5a0c6056bb839c72d1a6b640e2.svg" alt="Diagram" width="762" height="430">
```
previous versions created:
```
<img src="diag-70e2bf5a0c6056bb839c72d1a6b640e2.svg" alt="Diagram" width="762" height="430">
```
The filename is `diag-70e2bf5a0c6056bb839c72d1a6b640e2.svg`.

Windows fails to build (because a `:` in a filename is not allowed) and Linux creates broken links.

The following Change seems to be responsible for the behaviour: https://github.com/asciidoctor/asciidoctor-diagram/commit/332c2209ce0efb6b55411337d0845e74377f99c8. This change fixed #417.

We use Asciidoctor-Diagram via AsciidoctorJ-Diagram via Asciidoctor-Gradle-Plugin.

**Comment by pepijnve** [comment]
2.2.11 should fix this
