### ISSUE TITLE
 Nested boxes not getting generated with PlantUML in v2.2.10 (asciidoctorj-diagram)

### ISSUE THREAD

**Issue by PascalDutch** [asciidoctor/asciidoctor-diagram#429]
We have some issues building our documentation using the latest release of asciidoctorj-diagram.

We get an error from PlantUML that nested boxes are not supported. This is supported by PlantUML for sometime now, so I tried some different asciidoctorj-diagram versions and the problem only appears when using the latest version 2.2.10, 2.2.9 works fine. I downloaded the PlantUML version used in this asciidoctorj-diagram version (1.2023.5, found [here](https://github.com/asciidoctor/asciidoctor-diagram/commit/3af76c9b6bce73f07727ee9ea7ebb298a3ff5cf3)) and that generates the diagram just fine.

Error:
```
box "SomeText" #APPLICATION
  participant Participant
  box "SomeBox" #LightYellow   
^^^^^                                         
 Box cannot be nested                         

[error] asciidoctor: ERROR: diagram/subdir/file.puml: line 0: Failed to generate image: PlantUML image generation failed: [From <input> (line 16) ]     
```

AsciiDoc versions:
``` 
<asciidoctor-maven-plugin.version>2.2.2</asciidoctor-maven-plugin.version>
<asciidoctorj-diagram.version>2.2.10</asciidoctorj-diagram.version>
<asciidoctorj-pdf.version>2.3.3</asciidoctorj-pdf.version>
```

I can't put the complete PlantUML diagrams here since they contain classified information. 

I initially created an [issue](https://github.com/asciidoctor/asciidoctorj-diagram/issues/44) at asciidoctorj-diagram, but was sent here.

**Comment by PascalDutch** [comment]
> That error is being produced by PlantUML itself. I'll try to figure out where the difference is coming from.
> 
> I did give this a quick try already and it seems that, while I'm not getting an error, the boxes aren't really nested either. <img alt="image" width="625" src="https://user-images.githubusercontent.com/225326/260013979-241144a2-c41a-4527-8ef7-d1912fa7159c.png">

I believe you need to use the teoz (`!pragma teoz true`) engine for it to work.

**Comment by pepijnve** [comment]
I've added a unit test for this particular case. Seems to run fine, so I'm not entirely sure what's going on.

**Comment by pepijnve** [comment]
Looking at https://github.com/search?q=org%3Aplantuml%20cannot%20be%20nested&type=code it seems there's a difference between the various variants of PlantUML. That line gets printed in the MIT variant. In the others it's commented out. Perhaps asciidoctorj-diagram is packaging the MIT build?

**Comment by pepijnve** [comment]
I tried a couple of combinations of the various jars. I can't seem to get the error you're seeing.

**Comment by PascalDutch** [comment]
I isolated it in a separate project (one adoc file and one puml) with the same version as used above and that seems to be running fine. I think the error is on our side then. I agree that for some reason a different PlanUML version is used. Will investigate what the issue (probably next week). Thanks for the assistance though!

**Comment by pepijnve** [comment]
You could try figuring out which one it is using some PlantUML meta stuff.

If the bundled version is being used

```
@startuml
license
@enduml
```

should generate a diagram containing the ASLv2 license.

```
@startuml
participant "%version()"
@enduml
```

should show 1.2023.5

**Comment by pepijnve** [comment]
One possibility might be that some maven plugin in your project is placing a version of PlantUML on the classpath at build time. asciidoctor-diagram will add PlantUML to the classpath itself, but if it's already the already loaded version may take precedence. I might be able to guard against this by using a dedicated classloader when running under JRuby.

**Comment by PascalDutch** [comment]
> 

Hmm weird. It shows 1.2019.12 when I run it in the project and 1.2023.5 (expected) in the test project.

**Comment by pepijnve** [comment]
Well that at least explain a where the error is coming from. There's no code in place yet that could help debug this. The best suggestion I can give you is to somehow print the classpath from Maven to see if there's a rogue PlantUML in there somewhere. I haven't used Maven in ages so I cant really give you advice about how to do this.

**Comment by PascalDutch** [comment]
After some searching we found that some (inhouse made) plugin in some top level parent pom imported `asciidoctorj-diagram 2.2.1`. We now overwrite the dependency for that plugin and everything works fine now. Thanks for the help!
