### ISSUE TITLE
Files aren't installed without git

### ISSUE THREAD

**Issue by joshua-zivkovic** [asciidoctor/asciidoctor-diagram#431]
I started experiencing the same problems as https://github.com/asciidoctor/asciidoctor-diagram/issues/316 and did some digging. The gemspec has a case for what files to use when git is present or not. It seems as though when git is not installed, the fallback method installs no files at all, making the lib unusable.

I'm no gem expert so I can't say if this is because of the `deps` folder being included, where it is excluded when using git, or for some other reason. This is fixed by having git installed though so I am guessing it is the difference between the two commands used for specifying the files.

## Versions being used
- gem: 3.4.10
- ruby: 3.2.2
- asciidoctor-diagram: 2.2.11
- asciidoctor-diagram-plantuml: 1.2021.8
- asciidoctor-diagram-ditaamini: 1.0.3

## To reproduce
- Don't have git installed
- gem build
- gem install asciidoctor-diagram-2.2.11.gem

`ls` will show no contents under `.../ruby/gems/3.2.0/gems/asciidoctor-diagram-2.2.11/`

Repeating with git installed will show all necessary files required to use the lib.

**Comment by pepijnve** [comment]
That's not entirely surprising though. The gemspec uses the git to determine which files to include in the gem.

Can I ask why you're building the gem from source (which would require git to obtain it) instead of getting the prebuilt one from rubygems.org?

**Comment by pepijnve** [comment]
After reviewing the gemspec, I concluded there wasn't really much added value in using git. I've replaced that with an explicit listing of the files to include.

**Comment by mojavelinux** [comment]
The use of git to collect the files is really just a hold out from an old way of packaging gems to ensure it wasn't packaging files that are not committed. Now that we use an automated process that clones from git to publish most gems, we can be certain that the files it's collecting are not temporary files on the developer's computer.

**Comment by pepijnve** [comment]
That automation hasn't been set up for this particular gem just yet. 😁

**Comment by joshua-zivkovic** [comment]
Thanks for the quick responses and the changes made.

I'm building from source because we're following strict rules on how software is consumed. Any software that is consumed must have sources mirrored and be built from scratch which then all gets put together using buildstream.
