### ISSUE TITLE
Allow linking to source file for `svg-type=inline`

### ISSUE THREAD

**Issue by KartikSoneji** [asciidoctor/asciidoctor-diagram#433]
Inline svgs are great but that doesn't provide access to the source svg.
For example, right click > open in new tab to allow a focused view of only that image.

Can we add an option like `svg-type=inline-linked` that wraps the whole svg tag with `<a href="image.svg" target="_blank">` that will open the image in a new tab when clicked?

I believe the changes will need to be made here:
https://github.com/asciidoctor/asciidoctor-diagram/blob/2636028423f79b2411e25ef3d7aada7c720f63ef/lib/asciidoctor-diagram/diagram_processor.rb#L255-L265

**Comment by pepijnve** [comment]
I can add that in the diagram extension, but without support from the html5 backend it won't have much effect. Is this something the html5 backend already supports?

**Comment by pepijnve** [comment]
See https://docs.asciidoctor.org/asciidoc/latest/macros/image-svg/ for the available options

**Comment by KartikSoneji** [comment]
> Is this something the html5 backend already supports?

I don't think it does.
Maybe this should be a feature request to asciidoctor as well?

**Comment by KartikSoneji** [comment]
Something like an `opts=inline-linked` here:

([source](https://github.com/asciidoctor/asciidoctor/blob/454d590906459dc4645f9b01e44df486c1385827/lib/asciidoctor/converter/html5.rb#L1215-L1221
))
```ruby
        if node.option? 'inline'
          img = (read_svg_contents node, target) || %(<span class="alt">#{node.alt}</span>)
        elsif node.option? 'interactive'
          fallback = (node.attr? 'fallback') ? %(<img src="#{node.image_uri node.attr 'fallback'}" alt="#{encode_attribute_value node.alt}"#{attrs}#{@void_element_slash}>) : %(<span class="alt">#{node.alt}</span>)
          img = %(<object type="image/svg+xml" data="#{src = node.image_uri target}"#{attrs}>#{fallback}</object>)
        else
          img = %(<img src="#{src = node.image_uri target}" alt="#{encode_attribute_value node.alt}"#{attrs}#{@void_element_slash}>)
```

**Comment by mojavelinux** [comment]
Self linking for images has been proposed and implemented. However, it's not yet available in a release. See https://github.com/asciidoctor/asciidoctor/issues/3656

**Comment by KartikSoneji** [comment]
That's great!
Does that support inline images as well?

**Comment by mojavelinux** [comment]
* https://github.com/asciidoctor/asciidoctor/blob/454d590906459dc4645f9b01e44df486c1385827/lib/asciidoctor/converter/html5.rb#L642-L644
* https://github.com/asciidoctor/asciidoctor/blob/454d590906459dc4645f9b01e44df486c1385827/lib/asciidoctor/converter/html5.rb#L1227-L1229

**Comment by pepijnve** [comment]
Unless I'm mistaken this should just work out of the box since the diagram extension passes most attributes through to the generated block.

**Comment by mojavelinux** [comment]
Yes, once 2.1.0 is released. I recommend holding out for that release rather than changing Asciidoctor Diagram, as you suggested.
