### ISSUE TITLE
Gnuplot set working dir to document dir to resolve relative paths correctly

### ISSUE THREAD

**Issue by ManDay** [asciidoctor/asciidoctor-diagram#437]
If I understood it correctly, this is a sister issue to https://github.com/asciidoctor/asciidoctor-diagram/issues/410 , for Gnuplot, such that instructions like `load "file_in_document_directory"` do not depend on whence asciidoctor is invoked. Currently, the path resolves to the PWD in which I executed the asciidoctor binary.

**Comment by pepijnve** [comment]
This should be the case already. Would you mind providing a more detailed description of the file layout and contents so I can try to reproduce this locally?

**Comment by ManDay** [comment]
The script `test.sh` [here](https://github.com/asciidoctor/asciidoctor-diagram/files/12609119/add_test.zip) will reproduce it (asciidoctor-diagram 2.0.5).

**Comment by pepijnve** [comment]
Looks like I was mistaken. The fix I did for #410 was only for D2. PR #438 is a first attempt at fixing this for all types including gnuplot.

**Comment by pepijnve** [comment]
Should be fixed in 2.2.13
