### ISSUE TITLE
Valid mermaid graphs are not rendered within asciidoc files

### ISSUE THREAD

**Issue by quilicicf** [asciidoctor/asciidoctor-diagram#445]
Hi,

## The issue I have

I've got a Mermaid graph that renders correctly in GitHub but fails to render in a lot of other contexts which makes edition a pain.

The graph in question is this one:

```
classDiagram
  class Item {
    <<interface>>
  }
```

It renders in GitHub:

```mermaid
classDiagram
  class Item {
    <<interface>>
  }
```

When running asciidoctor via CLI though (or in IntelliJ's editor plugin):
```shell
asciidoctor README.adoc \
  --out-file README.html \
  --require 'asciidoctor-diagram'
```

The output is un-highlighted code instead.

## The analysis I've already done

I've tried rendering this graph in multiple contexts:
* GitHub
* Mermaid CLI (version `10.4.0` as it's the one used under the hood by asciidoctor-diagram)
* From inside Markdown documents (with IntelliJ's plugin, using Mermaid `10.4.0`)
* From IntelliJ Asciidoctor's plugin (Mermaid `10.4.0` under the hood)
* With Asciidoctor's CLI (Mermaid `10.4.0` under the hood)

This diagram only breaks in Asciidoc files, however it is run.

## The core of the issue

My original diagram was way bigger, I've slimmed it to the minimal example, and found out that the part that trips the rendering process is the `<<interface>>` bit.

## Idea of what's going on

I've played with Asciidoc a lot recently and noticed that the code blocks returned by Asciidoctor's parser have a particularity: the `<` & `>` characters are HTML-encoded as `&lt;` & `&gt;`.

I suspect it _might_ be what trips the rendering, but I am not sure and don't have the time to dig more right now.

Could you please have a look? :pray:

**Comment by pepijnve** [comment]
I tried to reproduce this with the following example. Seems to work fine.

```
= Hello, Mermaid!
Doc Writer <doc@example.com>

== First Section

[mermaid]
----
classDiagram
    class Item {
      <<interface>>
  }
----
```

**Comment by quilicicf** [comment]
Dang, I have an issue in IntelliJ but not with the CLI anymore Oo

![Selection_011](https://github.com/asciidoctor/asciidoctor-diagram/assets/5594303/2c5dda8a-d270-45f9-9c10-4a8bc3c09056)

It may have been because of the difference between how GitHub decides to render (`[source,mermaid]` blocks) and how it's supposed to be done (`[mermaid]` blocks) and a chair-keyboard-interface issue then ? :thinking: 

Maybe there's a bug in the IntelliJ plugin but none here.

I'll try to get to the bottom of this and re-open if I manage to reproduce, thanks for having a look :bow:
