### ISSUE TITLE
RfE: Extract type specific includes from embedded source.

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-diagram#446]
As a power user of the plugin I would like to get a respective file extension (and title) when extracting embedded source code, in particular PlantUML.

When extracting an include from a source block it currently looks like this:

<img width="706" alt="image" src="https://github.com/asciidoctor/asciidoctor-diagram/assets/456000/949f6f68-36ff-42e2-91a8-2719f1e1401c">

I'd rather like to get a type specific file name (e.g., `puml` for PlantUML blocks):

<img width="699" alt="image" src="https://github.com/asciidoctor/asciidoctor-diagram/assets/456000/e45e307f-21dd-4878-badd-d0d03ae4d3c7">

If a file name was given in the block head, it would furthermore be great, if the filename could be used as proposal for the include file.
In the case above the filename was `example`, so the proposed name should be `example.puml` finally.

<img width="695" alt="image" src="https://github.com/asciidoctor/asciidoctor-diagram/assets/456000/0c21f902-3b70-4082-accc-7fae250601d7">

In an Antora context it would also be great, if the generated file would be moved to the respective Antora partials directory, e.g., `examples`.
As discussed via personal communication, I am not yet sure whether puml files should be moved to the images partials directory?

**Comment by ahus1** [comment]
I suppose this issue should be moved to the GitHub repo of the AsciiDoc IntelliJ plugin.

**Comment by ascheman** [comment]
Of course, sorry, have been very busy with GH today and obviously opened the wrong repo without double checking.

**Comment by ascheman** [comment]
Reopened as https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1458
