### ISSUE TITLE
Cannot pass attributes to `mmdc` from command line

### ISSUE THREAD

**Issue by willcl-ark** [asciidoctor/asciidoctor-diagram#448]
It's possible that I've misunderstood the documentation (sorry in advance if that's the case), but I am trying to generate `png`s of my mermaid images by running this command:

```sh
asciidoctor -r asciidoctor-pdf -b pdf -r asciidoctor-diagram --attribute mermaid-output-format="png" -o output.pdf index.adoc
```

But the `mermaid-ouput-format=` attribute is not being detected/respected. Am I doing something wrong, or is this a bug?

**Comment by pepijnve** [comment]
Changing mermaid-output-format to mermaid-format should do the trick.
