### ISSUE TITLE
Misleadingly Reports Need for WaveDromEditor

### ISSUE THREAD

**Issue by acook** [asciidoctor/asciidoctor-diagram#453]
Because of the series of fallbacks culminate in a a check for `WaveDromEditor`:

https://github.com/asciidoctor/asciidoctor-diagram/blob/733f41cc18cf35a2d7ce68d50c6bf4ef5cc14983/lib/asciidoctor-diagram/wavedrom/converter.rb#L45

This is the error message that you see:

```
Failed to generate image: Could not find the 'WaveDromEditor' executable in PATH; add it to the 
PATH or specify its location using the 'WaveDromEditor' document attribute
```

But the easiest solution to the problem is to just install the commandline tools instead:

```sh
sudo npm install -g wavedrom-cli
```

I would suggest that the error message be updated or at least the documentation would reflect what is happening.

# Related

- https://github.com/asciidoctor/asciidoctor-diagram/issues/89
- https://github.com/asciidoctor/asciidoctor-diagram/issues/190

# Context

I encountered this while building the official RISC-V [documentation](https://github.com/riscv/riscv-isa-manual) which uses `asciidoctor-diagram` with WaveDrom.

**Comment by pepijnve** [comment]
I thought I had fixed this in 2.2.15; actually fixed in 2.2.16.
