### ISSUE TITLE
Failed to generate image: Could not find the 'blockdiag', 'blockdiag3' executable in PATH;

### ISSUE THREAD

**Issue by ioannisstavrakakis** [asciidoctor/asciidoctor-diagram#462]
In Windows, when executing asciidoctor-pdf, I het the following error message:

```
  WARNING: The script blockdiag.exe is installed in 'C:\Users\istavrak\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts nwdiag.exe, packetdiag.exe and rackdiag.exe are installed in 'C:\Users\istavrak\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
The files under the _Scripts_ folder are:

![image](https://github.com/asciidoctor/asciidoctor-diagram/assets/87022642/f6d2a929-49af-41ac-b646-641606ab9361)

How can I add it to PATH? Is is a system or a user variable? What name should I give to variable, and which value?

Thank you

**Comment by pepijnve** [comment]
This is a Python installation/configuration issue. See https://superuser.com/questions/1372793/the-script-is-installed-in-directory-which-is-not-path for ways to resolve this.
