### ISSUE TITLE
Wrong diagram shown in documentation

### ISSUE THREAD

**Issue by lurch** [asciidoctor/asciidoctor-diagram#469]
At the bottom of https://docs.asciidoctor.org/diagram-extension/latest/blocks/ it seems fairly obvious that the rendered diagram image doesn't actually correspond to the example diagram markup :facepalm: 

![Screenshot from 2024-09-07 16-01-17](https://github.com/user-attachments/assets/c3371803-3286-4ba9-83a5-28673d183ab2)

**Comment by mojavelinux** [comment]
If you would like to put together the diagram source that goes with it, we
can certainly get that updated. Or feel free to send a PR by clicking Edit
this Page.

**Comment by lurch** [comment]
I've never used asciidoctor-diagram before, and I don't have the motivation to learn enough if it to be able to correct your documentation.

**Comment by pepijnve** [comment]
Should be fixed next time the doc site is regenerated.
