### ISSUE TITLE
(LoadError) no such file to load -- asciidoctor-diagram (Use after fat Jar deployment)

### ISSUE THREAD

**Issue by Ghuu420** [asciidoctor/asciidoctor-diagram#471]
Ive been working on a Spring boot project lately that uses the asciidoctor and keep having this problem so hopefully someone is familiar with it and could say something about it .. 

Its a basic projekt to creates different types of reports. Locally using a IDE (ECLIPSE) everything works fine but after the deployment , some problems start to happen. I am using java 17 and Apach Maven 3.9.1 locally . 

The project is built into a fat executable Jar which is used for deployment (Linux Ubuntu (Java 17 too)) using these dependencies and  build plugins
<dependencies>
              <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
 		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj</artifactId>
			<version>3.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj-pdf</artifactId>
			<version>2.3.18</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj-diagram</artifactId>
			<version>2.3.1</version>
		</dependency>
	</dependencies>

   
![build_screen](https://github.com/user-attachments/assets/10495659-faa7-4c35-b114-8fdb196a1ad4)

I double checked after the successful build, that the asciidoctor-diagramm is unpacked and existant  (at xxx1.0.0.jar\BOOT-INF\classes\gems\asciidoctor-diagram-2.3.1\).
 After the deployment , calling an Api to generate a pdf report , I keep getting  this error :

 [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] -  Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.jruby.exceptions.LoadError: (MissingSpecError) Gem::MissingSpecError] with root cause : org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor-diagram
 at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1184)
 at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85)
 at RUBY.<main>(<script>:1)

**Comment by abelsromero** [comment]
I answered in https://github.com/asciidoctor/asciidoctorj/issues/1286. I can't close, but whoever has permission can? 🙏

**Comment by Ghuu420** [comment]
im really sorry about the double posting.
