### ISSUE TITLE
PlantUml StdLib sprites for aws14 can't be included 

### ISSUE THREAD

**Issue by chriskn** [asciidoctor/asciidoctor-diagram#475]
Hi, 

I have the following issue converting PlantUml diagrams containing stdlib sprites

## Issue

When I am trying to generate HTML via gradle from this adoc file: 
```
[plantuml]
....
@startuml
!include <tupadr3/devicons/android>
(<$android>)
@enduml
....

[plantuml]
....
@startuml
!include <awslib14/AWSCommon>
!include <awslib14/Analytics/EMR>
(<$EMR>)
@enduml
....
```

I am getting the following error: 

```
Failed to generate image: PlantUML preprocessing failed: [From <input> (line 3) ]            
                                    
@startuml                           
!includeurl <awslib14/AWSCommon>    
^^^^^                               
 cannot include <awslib14/AWSCommon>

Failed to generate image: PlantUML preprocessing failed: [From <input> (line 3) ]            
                                    
@startuml                           
!includeurl <awslib14/AWSCommon>    
^^^^^                               
 cannot include <awslib14/AWSCommon>
 :: test.adoc :: ....:14 (uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/parser.rb:next_block)
```

The error only occcurs for the awslib14 diagram. `!include <tupadr3/devicons/android>` works as expected. 

I don't know if there are issues with other libs then the awslib14. 

Since the tupadr3 include is working, I assume that [this code](https://github.com/asciidoctor/asciidoctor-diagram/blame/13865dbee07e2991601568d51eeb6d197eb46933/lib/asciidoctor-diagram/plantuml/extension.rb#L61) works as expected and the issue is related to something else. 

## Setup
I am using org.asciidoctor.jvm.convert 4.0.3 and tested with asciidoctor-diagram 2.3.1 and 2.2.1. Both have this issue. 

## Side Note 
What makes this even stranger is that the preview in the IntelliJ Asciidoctor plugin in version 0.43.3 displays the diagrams as expected when I use asciidoctor-diagram to render them: 
![grafik](https://github.com/user-attachments/assets/31719cf0-0e18-47d1-b265-492bd1a09bf4)

**Comment by pepijnve** [comment]
I'm not sure what could be going on here. That error is coming from PlantUML itself as far as I can tell. Perhaps pulling in the most recent PlantUML wrapper gem might resolve this?

**Comment by chriskn** [comment]
The PlantUML version could definitely be an issue. When I print the PlantUML version, I get 1.2022.5. Is there a way to force the use of a newer version with asciidoctor-diagram?

**Comment by pepijnve** [comment]
PlantUML is bundled in a secondary gem (https://rubygems.org/gems/asciidoctor-diagram-plantuml) that's updated independently of the asciidoctor-diagram gem. Easiest way to get the version you want is using Bundler.
Alternatively there's a mechanism in place to point to a specific PlantUML jar file as well. That's not documented though; I'll need to look up the exact syntax in the code.

**Comment by chriskn** [comment]
The reason for this issue is the way I configure asciidoctor-diagram in the asciidoctorj section of the build.gradle.kts. 
This statement: 
```
asciidoctorj {
    modules {
        diagram.use()
        diagram.setVersion("2.3.1")
    }
    setVersion("2.5.13")
}
```

leads to the following dependency graph containing different asciidoctor-diagram-plantuml versions
```
__$$asciidoctorj$$___d (n)
+--- org.asciidoctor:asciidoctorj:2.5.7 (n)
\--- org.asciidoctor:asciidoctorj-diagram:2.2.3 (n)

__$$asciidoctorj$$___r
+--- org.asciidoctor:asciidoctorj:2.5.7
|    +--- com.beust:jcommander:1.82
|    +--- org.asciidoctor:asciidoctorj-api:2.5.7
|    \--- org.jruby:jruby:9.3.8.0 -> org.jruby:jruby-complete:9.3.8.0
\--- org.asciidoctor:asciidoctorj-diagram:2.2.3 -> 2.3.1
     +--- org.asciidoctor:asciidoctorj-diagram-plantuml:1.2024.5
     |    \--- org.asciidoctor:asciidoctorj-diagram-batik:1.17
     \--- org.asciidoctor:asciidoctorj-diagram-ditaamini:1.0.3

__$$asciidoctorj_asciidoctor$$__d (n)
\--- org.asciidoctor:asciidoctorj:2.5.7 (n)

__$$asciidoctorj_asciidoctor$$__r
+--- org.asciidoctor:asciidoctorj:2.5.7
|    +--- com.beust:jcommander:1.82
|    +--- org.asciidoctor:asciidoctorj-api:2.5.7
|    \--- org.jruby:jruby:9.3.8.0 -> org.jruby:jruby-complete:9.3.8.0
\--- org.asciidoctor:asciidoctorj-diagram:2.2.3
     +--- org.asciidoctor:asciidoctorj-diagram-plantuml:1.2022.5
     \--- org.asciidoctor:asciidoctorj-diagram-ditaamini:1.0.3
```

As the graph shows, there is the `org.asciidoctor:asciidoctorj-diagram-plantuml:1.2022.5 ` included which leads to the issue. 

After removing the `diagrams.use()` call from my definition:
```
asciidoctorj {
    modules {
        diagram.setVersion("2.3.1")
    }
    setVersion("2.5.13")
}
```

I get the following dependency graph and the issue is fixed: 
```
__$$asciidoctorj$$___d (n)
+--- org.asciidoctor:asciidoctorj:2.5.7 (n)
\--- org.asciidoctor:asciidoctorj-diagram:2.3.1 (n)

__$$asciidoctorj$$___r
+--- org.asciidoctor:asciidoctorj:2.5.7
|    +--- com.beust:jcommander:1.82
|    +--- org.asciidoctor:asciidoctorj-api:2.5.7
|    \--- org.jruby:jruby:9.3.8.0 -> org.jruby:jruby-complete:9.3.8.0
\--- org.asciidoctor:asciidoctorj-diagram:2.3.1
     +--- org.asciidoctor:asciidoctorj-diagram-plantuml:1.2024.5
     |    \--- org.asciidoctor:asciidoctorj-diagram-batik:1.17
     \--- org.asciidoctor:asciidoctorj-diagram-ditaamini:1.0.3

__$$asciidoctorj_asciidoctor$$__d (n)
\--- org.asciidoctor:asciidoctorj:2.5.7 (n)

__$$asciidoctorj_asciidoctor$$__r
+--- org.asciidoctor:asciidoctorj:2.5.7
|    +--- com.beust:jcommander:1.82
|    +--- org.asciidoctor:asciidoctorj-api:2.5.7
|    \--- org.jruby:jruby:9.3.8.0 -> org.jruby:jruby-complete:9.3.8.0
\--- org.asciidoctor:asciidoctorj-diagram:2.3.1
     +--- org.asciidoctor:asciidoctorj-diagram-plantuml:1.2024.5
     |    \--- org.asciidoctor:asciidoctorj-diagram-batik:1.17
     \--- org.asciidoctor:asciidoctorj-diagram-ditaamini:1.0.3
```

The  `diagram.use()` snipped is taken from [the official documentation](https://asciidoctor.github.io/asciidoctor-gradle-plugin/master/user-guide/#diagram). If the configuration should be done differentially, the documentation should be fixed.

**Comment by pepijnve** [comment]
I can't tell you much about asciidoctorj I'm afraid. Different project maintained by different people. @robertpanzer can you share any insights regarding this issue?

**Comment by robertpanzer** [comment]
If I run it with the asciidoctorj command line installed from sdkman it seems to work fine.
It also works if I convert this using the Maven plugin.
I cannot tell much about the gradle plugin, it's probably best to create an issue for asciidoctor/asciidoctor-gradle-plugin.

**Comment by pepijnve** [comment]
> The  diagram.use() snipped is taken from [the official documentation](https://asciidoctor.github.io/asciidoctor-gradle-plugin/master/user-guide/#diagram). If the configuration should be done differentially, the documentation should be fixed.

I think the intent of the documentation is to provide two alternatives: default version or specific version. That can probably be clarified. Best place to discuss that would be https://github.com/asciidoctor/asciidoctor-gradle-plugin

I'm going to mark this issue as closed since I don't think there's a problem in the diagram gem itself.
