### ISSUE TITLE
Scaling the generated images

### ISSUE THREAD

**Issue by wimalopaan** [asciidoctor/asciidoctor-diagram#58]
It would be nice if there would be a possiblility to scale the generated svg diagrams. Especially for plantuml this would be nice:

 [plantuml, scale="200%"]
 ---- 
 A->B
 ----

**Comment by mojavelinux** [comment]
:+1:

This aligns well with the scale attribute in image macros used by the DocBook backend.

**Comment by pepijnve** [comment]
I seem to remember one of my colleagues already implementing this. Certainly feasible and a good idea.

**Comment by pepijnve** [comment]
Resolved in 69efda565940a1bc2ed040cd6ca83e112133f982

**Comment by mojavelinux** [comment]
:+1:

**Comment by pepijnve** [comment]
FYI, the latest commit changed the scale syntax from percentage to fraction. In other words, instead of `scale=150%` you'll need to use `scale=1.5`.

**Comment by mojavelinux** [comment]
I like this better, actually.

**Comment by alwyn** [comment]
Can this please be ported to work on PDF too?
