### ISSUE TITLE
Missing documentation on imagesoutdir attribute

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctor-diagram#59]
Issue https://github.com/asciidoctor/asciidoctor-diagram/issues/39 introduced a new attribute `imagesoutdir` whose usage is not explained in the documentation.

**Comment by pepijnve** [comment]
This was kind of a temporary workaround for missing information that asciidoctor wasn't exposing. I'll recheck to see if this has been resolved in the meantime or not. If not, I'll make sure to add some documentation on this attribute.

**Comment by mojavelinux** [comment]
I think we're going to be stuck with it for now because it seems like it's a tougher change to split in/out dirs globally than expected. It can't hurt to use this and then to move to something more universal in the future. Perhaps in the note just mention that we may have a more elegant solution in the future. For now, this is it. It is enabling a lot of use cases that are important.

**Comment by yeroc** [comment]
Has the fix with `imagesoutdir` actually been released?  There hasn't been a asciidoctor-diagram release in some time now.  I just ran into this issue using the asciidoctor-diagram-example (https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example).  When I discovered the diagrams were being generated into my `src` and went looking for a solution...

**Comment by mojavelinux** [comment]
Yep, it's available in the 1.3.0 previews (I tested 1.3.0.preview.4).

I think it's safe to upgrade the Maven example to use this version. First, you'd need to change the version of the gem to 1.3.0.preview.4. Next, you need to add the following attribute (adjacent to where `imagesdir` is set).

```
<imagesoutdir>${project.build.directory}/generated-docs/images</imagesoutdir>
```

I tested it and it works. Could you open an issue in https://github.com/asciidoctor/asciidoctor-maven-examples?

**Comment by pepijnve** [comment]
Apologies for not getting a proper 1.3 out the door yet. preview.4 has been available for a while and I haven't seen any new issues reported so I'll build and publish that as 1.3.0 tomorrow.

**Comment by mojavelinux** [comment]
:+1:

**Comment by yeroc** [comment]
Thanks a lot @mojavelinux, I updated to 1.3.0.preview.4 and specified the config as you suggested and it works.

@pepijnve I wasn't aware of the newer previews as there are no release tags for them on github?  Do tags for those only exist in your local github repository?  Could we get those pushed up to github?

Thanks again.

**Comment by pepijnve** [comment]
https://github.com/asciidoctor/asciidoctor-diagram/pull/104 also contains documentation on `imagesoutdir`.

**Comment by pepijnve** [comment]
Description of target directory logic has been added to README as part of c5e2798621b76d0e678d725694304fabdb675509
