### ISSUE TITLE
Current PlantUML fails when detach"

### ISSUE THREAD

**Issue by j-manu** [asciidoctor/asciidoctor-diagram#61]
The PlantUML included in the gem  - Version 8004 - does not handle the detach keyword

**Comment by kira-backes** [comment]
@j-manu When will there be a new (preview) gem release? https://rubygems.org/gems/asciidoctor-diagram/versions

Since I really want to use detach ;-) If it takes too long please just tell me and I’ll compile from source

**Comment by pepijnve** [comment]
@kira-backes I promised @wimalopaan a 1.3.0 release by the end of this week in #66. Still hoping to make that happen.

**Comment by kira-backes** [comment]
Thanks for the fast reply (and your work)!
