### ISSUE TITLE
Wrong embedding for SVG objects in HTML

### ISSUE THREAD

**Issue by gudesh** [asciidoctor/asciidoctor-diagram#64]
I'm trying to use **asciidoctor** for a highly linked documentation mostly based on generated *graphs*.

I'll use **graphviz** and **nwdiag** for this.

The graphs and their integration look very good, thank you.

**But** the **hyperlinks** set in the graphs (Ex: `web_srv [href="web_srv_details.html"]`) are **dead** when clicked upon from the html page.
Actually they are useable if I view the .svg file alone, so they work well.

I found out it is caused by the way the -svg files are embedded into the html, using _<img src=_
This is known to make svg elements **"inanimate"**.
>*[An SVG embedded with an <img> tag and one embedded as a CSS background image are treated in a similar way when it comes to CSS styling and animation. Styles and animations applied to an SVG using an external CSS resource will not be preserved once the SVG is embedded.](http://www.smashingmagazine.com/2014/11/03/styling-and-animating-svgs-with-css/4/)*

If I manually edit the html to embed the .svg with [`<object type="image/svg+xml" data=`](http://edutechwiki.unige.ch/en/Using_SVG_with_HTML5_tutorial#Embeding_SVG_in_HTML_5_with_the_object_tag), then
it works well, with the links clickable, as expected.

I also noted **another side-effect**: nwdiag seems to embed icons/images (think [cisco plugin](http://tk0miya.hatenablog.com/entry/20111212/p1)) using their
full-path. When I replaced the path with a local one it didn't work (blank image).
But after using `<object type="image/svg+xml" data=` for the html embedding, it started to work.

I think the images of format *SVG* should be (at least optionally) embedded as `<object ... />`.

Thanks for the good job.

**Comment by pepijnve** [comment]
What asciidoctor-diagram does is convert the diagram block to an image block at the asciidoc syntax tree level. The chosen asciidoctor backend then converts this to the chosen output format. It's the HTML5 backend that's choosing to write an `image` tag rather than an `object` tag.
I'll double check, but I don't think I can influence this from the asciidoctor-diagram code. If it's not possible I'll create an issue in the asciidoctor project itself linked to this one.

**Comment by pepijnve** [comment]
As suspected this is an issue with the default HTML5 backend. Short term fix is to monkey patch the backend to generate the content you want. There's no way for the asciidoctor-diagram plugin to do this for you I'm afraid.

**Comment by mojavelinux** [comment]
Technically, Asciidoctor Diagram could override the handler used to render the image block, but I'd rather not go down that path. Let's address it in core so that we fix it where the problem is actually happening.

**Comment by Kaligule** [comment]
Just for completness: You can do `[graphviz, format=svg, opts="inline"]` now, which will make links clickable.
