### ISSUE TITLE
Table-embedded diagram generation does not kick in

### ISSUE THREAD

**Issue by gudesh** [asciidoctor/asciidoctor-diagram#65]
When I embed a "blockdiag" diagram into a table's cell (with cell's type = `asciidoc`) it does not get generated.

However, if I place the same diagram's code _outside and before_ the table too, then it gets 
a) generated and displayed before the table (which I do not want, of course)
b) the diagram, for which a file now exists, gets gracefully displayed in the table's cell (which is what I want)

What this means:
a) my environment is correctly configured (called with `asciidoctor -r ascii-diagram`)
b) the *asciidoc* interpretation of the cell does kick in (the file link obviously gets generated)
c) but it does not kick the generation of diagrams in )-:

Thanks for your help.

Here an example:
```asciidoc
// pre-generate the diagram
[blockdiag, target='hosts-relationships-0-from', 'png']
----
{
  A <- B -> C -- D <-> E;
}
----

// table with embeddings
[cols="2", options="header", width="100%"]
|===
a| This host is involved in following relationships

[blockdiag, target='hosts-relationships-0-from', 'png']
----
{
  A <- B -> C -- D <-> E;
}
----
a| This host is involved in following relationships

[blockdiag, target='hosts-relationships-0-to', 'png']
----
{
  A <- B -> C -- D <-> E;
}
----


|===
```

**Comment by pepijnve** [comment]
@mojavelinux do you happen to know if the root cause here is an asciidoc syntax issue, an asciidoctor parsing issue, or a problem in the extension? Could save me some investigation time...

**Comment by pepijnve** [comment]
@gudesh do you get the same behaviour when, for instance, embedding a source code block in a table?

**Comment by gudesh** [comment]
@pepijnve I installed Coderay for the occasion and I can confirm it *does* get called within a table's cell.

**Comment by pepijnve** [comment]
AFAICT this is an asciidoctor issue. I been able to reproduce this and the block processor is simply not being invoked. I scanned through the asciidoctor source code and couldn't find any indication that extensions are invoked for content inside tables.
I've created https://github.com/asciidoctor/asciidoctor/issues/1300 to get to the bottom of this.

**Comment by mojavelinux** [comment]
Correct, this is not currently supported in Asciidoctor. Of course, it should be. I don't think it will be much of an issue to fix it, but we'll definitely have to handle it upstream in core.

**Comment by pepijnve** [comment]
Replaced by asciidoctor/asciidoctor#1300.
