### ISSUE TITLE
Enable "salt" sketches in plantuml diagrams 

### ISSUE THREAD

**Issue by wimalopaan** [asciidoctor/asciidoctor-diagram#66]
plantuml has an included subproject called "salt".
It should be possible to draw a tree like this:

```
[plantuml,format="svg"]
----
salt
{T
+ A
++ a
+ B
++ b
}
----
```

Unfortunately I get a syntax error here. Suppose that the starting line "salt" isn't sent to plantuml.

**Comment by pepijnve** [comment]
That's odd; I'll look into it.

asciidoctor-diagram wraps the plantuml code you provide in a `@startuml`, `@enduml` pair if it doesn't find `@start` at the beginning of your code. AFAICT from the plantuml documentation that should work. You could try putting `@startsalt`/`@endsalt` in your plantuml block yourself; that might already work.

**Comment by pepijnve** [comment]
I did some quick checks and it seems asciidoctor-diagram is sending the correct code to plantuml, the salt codepath in plantuml is being triggered but it's throwing an IllegalArgumentException.
I'll look into this further later today.

**Comment by wimalopaan** [comment]
Maybe its a version issue with plantuml?

**Comment by pepijnve** [comment]
Perhaps. Updating the plantuml version is on my todo list together with making it possible for users to choose the plantuml version they want to use (and download it from a maven repo)

**Comment by pepijnve** [comment]
FYI, identical error using plantuml 8020

**Comment by pepijnve** [comment]
Whoops, the previous errors were my own fault. After trying a number of things I'm back to the current version of the asciidoctor-diagram code and things just work.
I tried your example on the plantuml demo server and it didn't work there either, so perhaps there's just a syntax error in your salt code. I'm not familiar with that though so no idea what's wrong.

I am going to make an ehancement to the plantuml support in asciidoctor-diagram though. I'll add the 'salt' block type which obviates the need to have `salt` as the first line of your diagram.

**Comment by wimalopaan** [comment]
Mmh, strange ... the following works with the plantuml demo server but not in asciidoc-diagram:

```
salt
{
{T
+A
++a
}
}
```

**Comment by pepijnve** [comment]
Can't reproduce that here I'm afraid. What kind of error are you getting? If you PlantUML is producing a syntax error image then afaict the issue is on the plantuml side of things. When asciidoctor-diagram sends bad data to plantuml I got IllegalArgumentExceptions.
Either way, if you could copy/paste the error messages you're seeing, that would be very helpful.

**Comment by wimalopaan** [comment]
Here are the messages:
```
‡ asciidoctor -r asciidoctor-diagram  --trace -o test.html test.adoc
/home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362:in `rescue in load': asciidoctor: FAILED: /home/lmeier/Lehre/Eigene/Prog2NeuesKonzept/ppc/doc/test.adoc: Failed to parse source, invalid byte sequence in UTF-8 (ArgumentError)
        from /home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1281:in `load'
        from /home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458:in `convert'
        from /home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
        from /home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
        from /home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
        from /home/lmeier/.gem/ruby/2.2.0/gems/asciidoctor-1.5.2/bin/asciidoctor:10:in `<top (required)>'
        from /usr/bin/asciidoctor:23:in `load'
        from /usr/bin/asciidoctor:23:in `<main>'
```


for the folloging file:
```
// -*- mode: adoc ; fill-column: 120 -*-
// ---- Beginn Standardheader
= plusplusC
Wilhelm Meier <wilhelm.meier@hs-kl.de>
$Id: ppcSlide.adoc 868 2015-01-29 13:27:00Z wimalopaan $
:lang: de
:toc:
:toc-title: Inhalt
:toclevels: 4
:numbered:
:src_numbered: 
:icons: font
:title: Test
:sectanchors:
:sectlinks:
:experimental:
:duration: 90
:source-highlighter: coderay
:coderay-css: style
:status:
:menu:
:navigation:
:split:
:goto:
:blank:
:deckjs_theme: swiss
:showtitle:
:deckjs_transition: horizontal-slide
//:stylesdir: ./css
//:stylesheet: wm2.css
:customcss: css/deckjs.css 
:revealjs_theme: beige
:revealjs_slidenumber: true

//include::ppcdefs.adoc[]

== First 

[NOTE]
bla

== Second

.Planuml2
[plantuml,format="svg"]
----
salt
{
{T
+A
++a
}
}
----
```

**Comment by pepijnve** [comment]
Thanks, I'll have a look at that this evening. Could you also let me know which platform you're running on and which regional settings (for Windows) or locale (for Unix like systems) you're using. The bad UTF-8 sequence message makes me think this is a character encoding translation issue somewhere.

**Comment by wimalopaan** [comment]
Here the information:
```
[lmeier:/home/lmeier/Lehre/Eigene/Prog2NeuesKonzept/ppc/doc] ppc ‡ uname -a
Linux h242-meier-x230 3.19.2-1-ck #1 SMP PREEMPT Wed Mar 18 15:48:05 EDT 2015 x86_64 GNU/Linux
[lmeier:/home/lmeier/Lehre/Eigene/Prog2NeuesKonzept/ppc/doc] ppc ‡ locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
[lmeier:/home/lmeier/Lehre/Eigene/Prog2NeuesKonzept/ppc/doc] ppc ‡ asciidoctor --version
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
[lmeier:/home/lmeier/Lehre/Eigene/Prog2NeuesKonzept/ppc/doc] ppc ‡ 
```

**Comment by pepijnve** [comment]
Sorry forgot to ask for some additional info. Which version of asciidoctor-diagram are you using?

**Comment by wimalopaan** [comment]
Will you push that to rugygems?

**Comment by pepijnve** [comment]
Yes of course :) I expect to make a final 1.3.0 this week. There’s a couple of small issues that I would still like to resolve before making that release.
If you like you can already install the preview build (`gem install --prerelease asciidoctor-diagram`). That should already fix the problem for you.

**Comment by wimalopaan** [comment]
Sorry, just did that update to preview.3 but the error remains :-(

**Comment by pepijnve** [comment]
Oops, then my memory is letting me down. Must have fixed this after preview.3 then.

**Comment by pepijnve** [comment]
@wimalopaan I just pushed 1.3.0 preview 4 to rubygems.org which should fix this (and other) issues. If I don't get any complaints I'll push this as 1.3.0 next weekend.

**Comment by wimalopaan** [comment]
Am 29.03.2015 um 20:00 schrieb Pepijn Van Eeckhoudt:
> @wimalopaan <https://github.com/wimalopaan> I just pushed 1.3.0 preview
> 4 to rubygems.org which should fix this (and other) issues. If I don't
> get any complaints I'll push this as 1.3.0 next weekend.

Great!
All my testcases work. Thank you very much!

-- 
Wilhelm

**Comment by mojavelinux** [comment]
It appears that two sets of curly braces are required. The following works for me using 1.3.0.preview.4

```
[salt,format="svg"]
----
{{T
+ src
++ main
+++ java
+++ test
}}
----
```

We can either decide to simply document this or perhaps find a way to eliminate the requirement for one of the sets of curly braces. I don't know the salt syntax well, so I'm not sure if that's assuming too much.

**Comment by pepijnve** [comment]
Whatever you put in the block is passed to plantuml as is. The only transformation that's applied is to check for `@startuml` (or `@startsalt`) and add those (and their `@end` counterpart). IMO we should not go further than that.

If I'm reading the documentation correctly, the outer braces define the 'window'. You need a window at the root level; widgets can't appear directly.
