### ISSUE TITLE
Call ditaa with command line arguments

### ISSUE THREAD

**Issue by saschazelzer** [asciidoctor/asciidoctor-diagram#69]
Hi,

is it possible to specify command line arguments or something equivalent in the asciidoc file when running ditaa? I would like to control effects like box shadows and box separations which is possible via ditaa command line arguments `--no-separation` and `--no-shadows`.

Thanks.

**Comment by pepijnve** [comment]
No that's not yet possible, but shouldn't be too hard to add. I propose adding support for passing ditaa command line arguments as block attributes. For instance:
```
[ditaa,no-

**Comment by pepijnve** [comment]
Resolved by 887a5771aba1b90ba2fa17c4b7470c0ac298293b
I ended up adding support for an options attribute that takes the ditaa command line arguments as value. You can write, for instance,
```
[ditaa, options="--no-shadows --scale 2.5 --round-corner"]
```

**Comment by saschazelzer** [comment]
Awesome, thanks!

However, the image caching mechanism seems to be too aggressive now. Changing the options without changing the ascii image does not regenerate it. Is there some work-around?

**Comment by pepijnve** [comment]
Thanks for catching that one. The options are indeed not taken into account for the cache validation. Oversight on my part. I'll try to fix that this evening.

**Comment by pepijnve** [comment]
5149ac682d3517155c9868ddacbf1c5a11d4b46f makes the ditaa processor take the options attribute into account when deciding if the image needs to be regenerated or not.

**Comment by mojavelinux** [comment]
I'm definitely in support of this approach, but I wonder if we should also have the option of making these customizations globally using document attributes. wdyt? Something like:

```
:ditaa-options: no-shadows,round-corners
```

or even

```
:ditaa-option-no-shadows:
:ditaa-option-round-corners:
```

**Comment by pepijnve** [comment]
Sounds like a good idea. My first implementation actually had the options in the form you're using above; without the double-dashes. That looked more asciidoc-like in my eyes than raw command line arguments. I backed away from that approach thinking that it might be easier for users (and less documentation work) if you could just use the command line arguments of the tool in question as is.

If we go ahead with the above syntax then the same syntax should be supported on the blocks themselves imo.
So you could either do
```
:ditaa-options: no-shadows, round-corners, scale=2.5
```
globally or
```
[ditaa, options="no-shadows,round-corners,scale=2.5"]
```
at the block level.

@saschazelzer any preference from your side? Make it look asciidoc-ish or stick with the raw command line options?

**Comment by mojavelinux** [comment]
I like what you've suggested, esp the document level attribute.

**Comment by saschazelzer** [comment]
I would definitely use document attributes if they were available. As a consequence, the syntax should be the same at the block level, as you already said. Your example above looks good to me. I am not an expert asciidoc user (yet) though.

**Comment by pepijnve** [comment]
Reopening for syntax change and document attribute support

**Comment by pepijnve** [comment]
I ended up implementing the following:

- The Ditaa extension supports the options `scale`, `antialias`, `separation`, `round-corners`, `shadows` and `debug`
- Options can be specified per block as `<option>=<value>` or globally as a document attribute of the form `:ditaa-option-<option>: <value>`
- Block level options override global options
- Default values are Ditaa's defaults

The semantics of the options are

- `scale`: scale factor specified as a decimal number (e.g. `scale=1.5`)
- `antialias`: true to enable antialiasing; false to disable it
- `separation`: true to leave spacing between adjacent blocks; false to remove it
- `round-corners`: true to force round corners everywhere; false to use corner style from diagram 
- `shadows`: true to enable drop shadows; false to disable them
- `debug`: true to display a debug grid in the diagram; false to remove it

**Comment by mojavelinux** [comment]
Huge :+1: !

**Comment by saschazelzer** [comment]
This is great, thanks!
