### ISSUE TITLE
Generated diagram image not found when -D or -o options specified

### ISSUE THREAD

**Issue by MarkCallow** [asciidoctor/asciidoctor-diagram#77]
If you specify the `-D <destination dir>` or `-o <output file>` options to asciidoctor, you get the following warning (which is actually an error as the image is not included in the document.)

```
WARNING: image to embed not found or not readable: <document src dir>/<diagram name>
```

Note that in the failing case `<output file>` is in a directory other than the document source directory.

This error happens because the diagram image is generated in the destination directory while asciidoc is looking for it in the source directory.

**Comment by mojavelinux** [comment]
In this case, I recommend specifying the `imagesoutdir` attribute explicitly so the generated images go to the right place. If that still doesn't work, let's fix that scenario so it does work.

**Comment by pepijnve** [comment]
@msc- could you provide a more detailed description of your directory layout and an asciidoc snippet that resembles your document? It would also be helpful to know which backend is causing the problem.

**Comment by pepijnve** [comment]
Probably the same as #85, but without further details there's not much I can do.
