### ISSUE TITLE
PlantUML working directory fixed at first call only

### ISSUE THREAD

**Issue by s-ga** [asciidoctor/asciidoctor-diagram#82]
The problem only appear on consecutive calls to asciidoctor-diagram **in the same process**.

# Context

I made a Ruby script to convert several adoc located in differents directories.
Some documents include PlantUML blocks including images using the creole syntax (e.g. `<img:my_pic.png>`).
The images for each document are in the same directory of it.

For each document the script changes the working directory using `Dir.chdir` and trigger the conversion using `Asciidoctor.convert`

# Problem

Only the PlantUML blocks of the first rendered document has the creole images rendered correctly. With the next documents there is an error in the drawing saying that the image files were not found.
One can see in the path of the image that the directory of the first document was used instead of the current one.

# My 2 cents analysis

The JVM is only launched once for perfomance concerns.
It will get the working directory set by Ruby and keep it forever.

For testing purpose I patched the `Asciidoctor::Java::Java::CommandServer.instance` method to have it create a new server at each call.
The performances are for sure horrible but all my documents were rendered correctly.

**Comment by pepijnve** [comment]
You're correct that the JVM is launched only once for performance reasons. As you noticed, spawning a new JVM instance per diagram is too slow to be usable.

The JVM is running a mini HTTP server that performs the diagram conversion. This issue can be fixed by passing the working directory to the JVM process via a custom HTTP header and changing the working directory before PlantUML itself is called. I'll have to double check how to do this safely without creating an escape hatch for asciidoctor's safety levels. @mojavelinux any specific things that need to be taken into account?

**Comment by pepijnve** [comment]
Ugh, and now I remember that Java doesn't provide a built-in way to change the working directory of the process. The `user.dir` system property can be set, but that may not fix the issue in all cases (depends on how PlantUML opens the referenced files). I'll try that first, but if it doesn't work we'll need to use https://github.com/jnr/jnr-posix or something similar.

**Comment by pepijnve** [comment]
On second thought, it's probably better and simpler to pre-process the PlantUML source code. It should be straightforward to scan the code for the creole `<img:file>`-like bits and convert any relative paths to absolute ones on the Ruby side. This way asciidoctors safe mode utilities can be used to check the file references for validity.

**Comment by mojavelinux** [comment]
> convert any relative paths to absolute ones on the Ruby side.

Exactly, that gives you the opportunity to use the path resolver functions either in AbstractNode or PathResolver.

**Comment by pepijnve** [comment]
I'm going to fix this, as discussed above, by resolving the paths in `<img>` tags against `imagesdir` using `normalize_system_path`.

**Comment by mojavelinux** [comment]
:+1:

**Comment by s-ga** [comment]
thanks!
