### ISSUE TITLE
Exception when dot is not found not thrown in v1.3.1

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-diagram#83]
In version 1.2.1, when `dot` command was not found,an exception was thrown and the conversion aborted. But in version 1.3.1 the conversion shows the exception in the console, but also inserts it into the generated HTML (see attachment). Seems to me that it is not thrown or asciidoctor (ruby) is not catching it.

I am using the example https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-diagram-example/src/docs/asciidoc/example-manual.adoc with asciidoctorj-1.5.2.1 and asciidoctorj-1.5.3.2 and both have the same behaviour, so I guess it isn't a change in Asciidoctorj.

[example-manual.txt](https://github.com/asciidoctor/asciidoctor-diagram/files/35822/example-manual.txt)

Let me know if you need anything else.

**Comment by pepijnve** [comment]
That change was made in f9d20aafb5a914c77ce323bebf54d9913759a26d to resolve issue #41. It's not an ideal solution, but the best resolution I can come up with is to make this an option (controlled via a document property). Would that be acceptable?

**Comment by abelsromero** [comment]
I understand the history behind it and I realize that the ideal solution would be having a standard solution to "push" exceptions to asciidoctor so it can decide what to do.
But there are two things in this issue:
* First, on error, right now the exception stack is embedded in the generated HTML. I think that at least, this should be fixed, so that in case on error, the original content of the section is returned. Kind of what happens when an include directive points to a non-existing resource.
* Second, what do we do in case of error? do we throw an exception or not? I'm open to debate, but I see that you need a way to capture when the document generation fails. This is important when using asciidoctor in an automated process/CI. Maybe, providing an attribute is a solution that could become standard for all extension, even at asciidoctor level I see this as interesting.

wdyt?

**Comment by pepijnve** [comment]
With which diagram type are you seeing the stack trace in the generated output? The code to handle error cases is at https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/extensions.rb#L106. It should be prepending the exception message to the diagram code and generate a listing block.

 The second issue is one for @mojavelinux to have a look at I think. We talked briefly about the need for a centralised error handling mechanism, but I don't know if any progress has been made in that area. I'm a bit reluctant to add this at the extension level.

**Comment by mojavelinux** [comment]
On Tue, Nov 17, 2015 at 3:39 AM, Pepijn Van Eeckhoudt <
notifications@github.com> wrote:

> We talked briefly about the need for a centralised error handling
> mechanism, but I don't know if any progress has been made in that area.


Not yet. Most likely 1.6.0. Related to
https://github.com/asciidoctor/asciidoctor/issues/44

**Comment by pepijnve** [comment]
I reviewed the relevant code again and figured out why you're getting a stack trace in the output. The Java code is sending back an error response with a plain text body. This body contains a dump of the Java exception that caused the image generation to fail and includes the Java stack trace. This is very useful for debugging, but not so really useful at all for an end-user.

I'm going to switch to a JSON body that contains the error message and Java stack trace dump as two distinct items. When the error is handled on the Ruby side I can then use only the Java message as message on the Ruby side and put the Java stack trace in the Ruby exceptions backtrace.

**Comment by mojavelinux** [comment]
:+1:

**Comment by pepijnve** [comment]
42f68d1 adds support for a `diagram-on-error` document attribute. By default (or if set to `log`) the current logging error handling approach is used. If set to `abort` an exception will be raised instead.
