### ISSUE TITLE
Restore support for `graphvizdot` document attribute

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-diagram#84]
In asciidoctor-diagram 1.2.0 the location of the graphviz `dot` command could be specified using the `graphvizdot` document attribute. Since 1.3.0 this is no longer supported.
Support for this attribute should be restored.

Additionally it would be convenient to support this attribute for graphviz type diagrams as well. Currently only the `dot` document attribute can be used for this.

**Comment by weissreto** [comment]
I have the same problem but using the maven plugin. 
Unfortunately 1.3.2 and 1.4.0 is not yet available in maven central. 
Can you release 1.3.2 and 1.4.0 to maven central?
Thanks

**Comment by pepijnve** [comment]
@weissreto you should request that in the project that publishes the maven plugin in question. That's not something that I've done.

**Comment by mojavelinux** [comment]
AsciidoctorJ bundles this project as a jar for use on the JVM and publishes
it to Maven central, so that's where you want to look.

Keep in mind, though, you can still use the gem directly from AsciidoctorJ.
That jar is merely a convenience.
