### ISSUE TITLE
Support Mermaid

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-diagram#91]
Add support for the [Mermaid](https://knsv.github.io/mermaid/) diagram generator.

- Integrate via the [Mermaid CLI](https://knsv.github.io/mermaid/#mermaid-cli)
- Allow the [sequence diagram configuration](https://knsv.github.io/mermaid/#sequence-diagram-configuration) to be specified using a document attribute that can be overridden per block using a block attribute

**Comment by pepijnve** [comment]
Added support for Mermaid via its CLI. Supports PNG and SVG output. `sequenceConfig` can be specified at the document and block level. `width` can be specified at the block level only.

**Comment by mojavelinux** [comment]
Nice job! I look forward to putting this one to use.

**Comment by JmyL** [comment]
It failed with the error message below.

```
asciidoctor-diagram: ERROR: Failed to generate image: No such file or directory @ sys_fail2 - (/tmp/mermaid20160407-4250-17u1yt5.svg.svg, /tmp/mermaid20160407-4250-4drkwb.svg)
```

'.svg.svg' part looks weird for me.

The test code is here.

```
["mermaid", "glove mode flowchart", "svg"]
------------------------------------------------------------
sequenceDiagram
    Alice->John: Hello John, how are you?
    loop Reply every minute
        John-->Alice: Great!
    end
------------------------------------------------------------
```

**Comment by pepijnve** [comment]
Hi @JmyL,

This issue was to track the addition of the new feature and is already closed. I'll create a new issue with your comment to track the discussion of the problem you described.
