### ISSUE TITLE
Java large pages cause socket error

### ISSUE THREAD

**Issue by metro69** [asciidoctor/asciidoctor-diagram#94]
My CentOS system has issues with large pages on java (it throws _'Cannot allocate memory' (errno=12); Cannot allocate large pages, falling back to regular pages_ errors, but continues).

In java_socket.rb, this causes the java call to silently fail and not create a socket. As a result, asciidoctor-diagram will fail with _Network is unreachable - connect(2) for "localhost" port 0_.

This problem is resolved by adding `args << '-XX:-UseLargePages'` to CommandServer.initialize.

**Comment by pepijnve** [comment]
Enabling that flag by default is a bit risky.

Are you seeing this error right away? If it happens after a while this might be due to a memory leak. 
Do you get the same error if you reduce the initial/max heap size with -Xms/-Xmx?

**Comment by metro69** [comment]
Happens right away. Default heapsizes seem ok:
InitialHeapSize                          := 526065920
MaxHeapSize                            := 8417968128
Changing them with Xms/Xmx does not seem to have any impact on the large page error.

What is the risk of the flag? It is recommended by Oracle in case of large page errors.

**Comment by pepijnve** [comment]
I'm just a bit reluctant to add JVM launch parameters without understanding the full consequences of them. Adding this flag may break things for other people.
I would prefer root causing why this is happening first rather than just fighting the symptoms. Could you provide some more information about your environment (CentOS version, which JVM package/version you're using, amount of memory in the system, large page settings of the OS, etc)?

**Comment by metro69** [comment]
Understood.
CentOS 6.5
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
32GB memory
Huge pages are supported in the kernel.

This looks like a known problem:
https://blogs.oracle.com/poonam/entry/uselargepages_on_linux
http://mail.openjdk.java.net/pipermail/hotspot-dev/2013-July/010117.html

**Comment by pepijnve** [comment]
I spent some time looking through the oracle big database yesterday. It does indeed seem to be a known issue on Linux. Supposedly 7u60 resolves some issues wrt large page usage but details are scarce.
Is it possible for you to update your Java installation to a more recent patch version?

**Comment by pepijnve** [comment]
BTW, what I'm considering as a fix for this is to add support for a document attribute that allows you to specify JVM launch arguments.
I'm not sure if it's a good idea to pass these verbatim to Java. Perhaps if the security mode is set sufficiently lenient this could be allowed. Definitely not a good idea in a server setting.
@mojavelinux any thoughts on this?

**Comment by mojavelinux** [comment]
This is a great example of when I really think we need to be able to connect the options hash to extensions. This gives a way to control behavior outside of the document (and thus not add attack vectors via content). Perhaps we can start discussing this in core.

Of course, in the meantime, you could consider using an attribute in a low safe mode, but to do it right, we may need a change to core.

**Comment by metro69** [comment]
With java updated to 7u80, the problem no longer appears.

Is it possible to add a more meaningful error message when the java call fails?

**Comment by pepijnve** [comment]
Yep I'll fix the error messages. The relevant bit of code is missing error handling code. I'll add checks to make sure the JVM actually launched properly and include stderr output in the raised error.

In your particular case, does the JVM actually launch or does it fail and exit right away?

**Comment by pepijnve** [comment]
Closing this issue since a workaround for the large pages issue was found. New issue for improved error handling has been created.

**Comment by metro69** [comment]
> In your particular case, does the JVM actually launch or does it fail and exit right away?

I am not sure what happens in the  Ruby script.

When I call a java command from the command line using u51 without the -UseLargePages option, the large page errors are printed to the console, but the java command actually succeeds and return code is 0.
