### ISSUE TITLE
blockdiag location override?

### ISSUE THREAD

**Issue by gliptak** [asciidoctor/asciidoctor-diagram#97]
I just got this following message:

```
asciidoctor-diagram: ERROR: Failed to generate image: Could not find the 'blockdiag' executable in PATH; add it to the PATH or specify its location using the 'blockdiag' document attribute
```
Is there an example on how to override these PATHs in a document attribute? I might have missed it in the documentation.

Thanks

**Comment by pepijnve** [comment]
`asciidoctor -a blockdiag=/usr/bin/blockdiag3 ...` should do the trick.

**Comment by gliptak** [comment]
@pepijnve Thank you
https://github.com/asciidoctor/asciidoctor-diagram/pull/99
